---
sidebar: sidebar 
permalink: oracle/host-configuration/windows.html 
keywords: oracle, database, ontap, windows 
summary: Oracle sous ONTAP sous Microsoft Windows 
---
= Microsoft Windows
:allow-uri-read: 


[role="lead"]
Rubriques de configuration spécifiques au système d'exploitation Microsoft Windows.



== NFS

Oracle prend en charge l'utilisation de Microsoft Windows avec le client NFS direct. Cette fonctionnalité offre les avantages de NFS en termes de gestion, notamment la possibilité d'afficher les fichiers dans les différents environnements, de redimensionner les volumes de façon dynamique et d'exploiter un protocole IP moins onéreux. Pour plus d'informations sur l'installation et la configuration d'une base de données sous Microsoft Windows à l'aide de dNFS, reportez-vous à la documentation officielle d'Oracle. Il n'existe pas de meilleures pratiques spéciales.



== SAN

Pour une efficacité de compression optimale, assurez-vous que le système de fichiers NTFS utilise une unité d'allocation de 8 Ko ou plus. L'utilisation d'une unité d'allocation 4K, qui est généralement la valeur par défaut, a un impact négatif sur l'efficacité de la compression.
