---
sidebar: sidebar 
permalink: oracle/virtualization/intro.html 
keywords: oracle, database, ontap, virtualization, esx, hyper-v, KVM 
summary: Introduction à la virtualisation de la base de données 
---
= Virtualisation
:allow-uri-read: 


[role="lead"]
La virtualisation des bases de données avec VMware ESX, Oracle OVM ou KVM est un choix de plus en plus courant pour les clients NetApp qui ont choisi la virtualisation, même pour leurs bases de données les plus stratégiques.

Il existe de nombreuses idées fausses sur les politiques de prise en charge de la virtualisation, en particulier pour les produits VMware. En effet, il n'est pas rare d'entendre qu'Oracle ne prend en charge la virtualisation d'aucune façon. Cette notion est incorrecte et ne permet pas de bénéficier d'opportunités de virtualisation. Oracle Doc ID 249212.1 traite des problèmes connus dans un environnement Oracle et indique également la prise en charge de RAC.

Il peut être demandé à un client dont le problème n'est pas connu d'Oracle de reproduire le problème sur du matériel physique. Un client Oracle exécutant une version de pointe d'un produit peut ne pas vouloir utiliser la virtualisation en raison du risque de nouvelle détection de bogues. Cependant, cette situation n'a pas été un problème dans la pratique pour les clients utilisant des versions de produit généralement disponibles.



== Présentation du stockage

Les clients qui envisagent de virtualiser leurs bases de données doivent baser leurs décisions de stockage sur leurs besoins métier. Bien qu'il s'agisse généralement d'une véritable déclaration pour toutes les décisions INFORMATIQUES, elle est particulièrement importante pour la virtualisation, car la taille et l'étendue des projets varient considérablement.

Il existe quatre options de base pour la présentation du stockage :

* LUN iSCSI gérées par l'initiateur iSCSI sur la machine virtuelle, pas par l'hyperviseur
* Systèmes de fichiers NFS montés par la machine virtuelle, pas un disque de machine virtuelle (VMDK)
* Datastores d'hyperviseur


En règle générale, évitez d'utiliser des datastores pour les fichiers Oracle. Il y a plusieurs raisons à cette recommandation :

* *Transparence.* lorsqu'une machine virtuelle possède ses systèmes de fichiers, il est plus facile pour un administrateur de base de données ou un administrateur système d'identifier la source des systèmes de fichiers pour leurs données.
* *Performance.* les tests ont montré qu'il existe un effet sur les performances en canalisant toutes les E/S via un datastore d'hyperviseur.
* *Gérabilité.* lorsqu'une machine virtuelle possède ses systèmes de fichiers, l'utilisation ou la non-utilisation d'une couche hyperviseur affecte la gestion. Les mêmes procédures de provisionnement, de surveillance, de protection des données, etc. Peuvent être utilisées dans l'ensemble du parc, y compris dans les environnements virtualisés et non virtualisés.
* *Stabilité et dépannage.* lorsqu'une machine virtuelle possède ses systèmes de fichiers, les performances sont stables et les problèmes de dépannage sont beaucoup plus simples car la pile de stockage est entièrement présente sur la machine virtuelle. Le seul rôle de l'hyperviseur est de transporter des trames FC ou IP. Lorsqu'un datastore est inclus dans une configuration, il complique la configuration en introduisant un autre ensemble d'expirations de délai, de paramètres, de fichiers journaux et de bogues potentiels.
* *Portabilité.* lorsqu'une machine virtuelle possède ses systèmes de fichiers, le processus de déplacement d'un environnement Oracle devient beaucoup plus simple. Les systèmes de fichiers peuvent facilement être déplacés entre des invités virtualisés et non virtualisés.
* *Dépendance vis-à-vis d'un fournisseur.* une fois les données placées dans un datastore, il devient très difficile d'utiliser un hyperviseur différent ou de retirer les données de l'environnement virtualisé.
* *Activation Snapshot.* dans certains cas, les sauvegardes dans un environnement virtualisé peuvent devenir problématiques en raison de la bande passante relativement limitée. Par exemple, un agrégat 10 GbE à quatre ports peut suffire pour répondre aux besoins quotidiens en performances de nombreuses bases de données virtualisées. Cependant, un tel agrégat ne suffit pas pour effectuer des sauvegardes à l'aide de RMAN ou d'autres produits de sauvegarde nécessitant le streaming d'une copie complète des données.
+
L'utilisation de systèmes de fichiers appartenant à des machines virtuelles facilite l'exploitation des sauvegardes et des restaurations basées sur des copies Snapshot. Un système de fichiers appartenant à une VM délègue la tâche d'exécution des sauvegardes sur le système de stockage. Il n'est pas nécessaire de surconstruire la configuration de l'hyperviseur uniquement pour prendre en charge les besoins en bande passante et en CPU dans la fenêtre de sauvegarde.




TIP: *NetApp recommande* d'éviter de placer les données Oracle sur un datastore afin d'optimiser les performances et la facilité de gestion. Utilisez des systèmes de fichiers invités, tels que des systèmes de fichiers NFS ou iSCSI gérés par l'invité ou avec des RDM.



== Pilotes paravirtualisés

Pour des performances optimales, l'utilisation de pilotes de réseau paravirtualisés est essentielle. Lorsqu'un datastore est utilisé, un pilote SCSI paravirtualisé est requis. Un pilote de périphérique paravirtualisé permet à un invité de s'intégrer plus profondément dans l'hyperviseur, au lieu d'un pilote émulé dans lequel l'hyperviseur passe plus de temps CPU à imiter le comportement du matériel physique.

Les performances de la plupart des bases de données sont limitées par le stockage. Par conséquent, la latence supplémentaire introduite par un pilote réseau ou SCSI est particulièrement notable. Le support client NetApp a rencontré de nombreuses plaintes de performances qui ont été résolues par l'installation de pilotes paravirtualisés. Au cours d'une démonstration de faisabilité effectuée par un client, les bases de données ont affiché des performances supérieures sous ESX par rapport au même matériel fonctionnant sous bare Metal. Les tests ont été très exigeants en E/S et la différence de performances a été attribuée à l'utilisation de pilotes réseau paravirtualisés ESX.


TIP: *NetApp recommande* d'utiliser toujours des pilotes réseau paravirtualisés et des pilotes SCSI.



== Saturation de la mémoire RAM

La saturation de la mémoire RAM implique la configuration d'une quantité de mémoire RAM virtualisée supérieure à celle qui existe sur le matériel physique sur différents hôtes. Cela peut entraîner des problèmes de performances inattendus. Lors de la virtualisation d'une base de données, les blocs sous-jacents de la SGA d'Oracle ne doivent pas être remplacés par l'hyperviseur vers le stockage. Cela entraîne des résultats de performances très instables.


TIP: *NetApp recommande* de ne pas configurer un hyperviseur de manière à ce que les blocs SGA Oracle puissent être échangés.
