---
sidebar: sidebar 
permalink: oracle/oracle-dp-planning.html 
keywords: data protection, DR, snapshots, CG 
summary: Planification de la protection des données pour les bases de données Oracle 
searchtitle: Planification de la protection des données pour les bases de données Oracle 
---
= Planification de la protection des données
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La bonne architecture de protection des données de base de données Oracle dépend des exigences de l'entreprise en matière de conservation des données, de capacité de restauration et de tolérance aux perturbations lors de divers événements.

Prenons l'exemple du nombre d'applications, de bases de données et de datasets importants pris en compte. Il est relativement simple d'élaborer une stratégie de sauvegarde pour un seul dataset afin d'assurer la conformité aux SLA standard, car la gestion ne comporte pas beaucoup d'objets. À mesure que le nombre de jeux de données augmente, la surveillance devient plus complexe et les administrateurs peuvent être obligés de consacrer de plus en plus de temps aux pannes de sauvegarde. Dès qu'un environnement évolue, il faut adopter une approche totalement différente.

La taille des datasets affecte également la stratégie. Par exemple, le jeu de données étant si petit, de nombreuses options sont possibles pour la sauvegarde et la restauration avec une base de données de 100 Go. En général, la simple copie des données à partir du support de sauvegarde avec des outils classiques permet d'atteindre un RTO suffisant pour la restauration. Une base de données de 100 To a généralement besoin d'une stratégie totalement différente, sauf si le RTO autorise une panne de plusieurs jours. Dans ce cas, une procédure classique de sauvegarde et de restauration basée sur des copies peut être acceptable.

Enfin, il y a des facteurs en dehors du processus de sauvegarde et de restauration lui-même. Par exemple, existe-t-il des bases de données qui prennent en charge les activités de production stratégiques, faisant de la restauration un événement rare uniquement effectué par des administrateurs de bases de données qualifiés ? Ou bien, les bases de données font-elles partie d'un vaste environnement de développement dans lequel la restauration est fréquente et gérée par une équipe INFORMATIQUE généraliste ?



== Un snapshot est-il une sauvegarde ?

L'une des objections les plus fréquentes à l'utilisation des snapshots en tant que stratégie de protection des données est le fait que les « vraies » données et les données de snapshot se trouvent sur les mêmes disques. La perte de ces disques entraînerait la perte des données primaires et de la sauvegarde.

Ce problème est valide. Les snapshots locaux sont utilisés pour les besoins quotidiens de sauvegarde et de restauration, et dans ce sens, le snapshot est une sauvegarde. Dans les environnements NetApp, près de 99 % des scénarios de restauration s'appuient sur des copies Snapshot pour répondre aux exigences de RTO les plus strictes.

Toutefois, les snapshots locaux ne doivent jamais être la seule stratégie de sauvegarde. C'est pourquoi NetApp propose des technologies telles que la réplication SnapMirror pour répliquer rapidement et efficacement des copies Snapshot sur un ensemble indépendant de disques. Dans une solution bien conçue avec des snapshots et une réplication Snapshot, l'utilisation des bandes peut être réduite au minimum, voire même à une archive trimestrielle, ou totalement éliminée.



== Sauvegardes cohérentes après panne

Une sauvegarde cohérente après panne consiste à capturer l'état d'un ensemble de données (ou de plusieurs ensembles de données) à un point atomique unique dans le temps. À titre d'exemple pour une base de données, cela inclut tous les composants de la base de données, tels que les fichiers de données, les fichiers journaux et les autres fichiers directement associés à la base de données. Cela fonctionne avec presque tous les produits de base de données relationnelles, y compris Oracle RDBMS, Microsoft SQL Server, SAP HANA, PostgreSQL, MySQL et MariaDB. La protection d'une configuration VMware avec une sauvegarde de groupe de cohérence serait similaire : capturer tous les datastores et potentiellement les LUN de démarrage ESX à un point atomique unique dans le temps.

La création d'une telle sauvegarde simule essentiellement un incident, c'est pourquoi ces sauvegardes sont appelées sauvegardes cohérentes après panne. Des interrogations subsistent parfois quant à la prise en charge des scénarios de restauration, mais il est important de comprendre qu'aucune procédure de restauration n'est généralement nécessaire. Lorsque l'application redémarre après la restauration d'une sauvegarde de groupe de cohérence, elle effectue les processus habituels de récupération des journaux, les relectures du journal du système de fichiers et d'autres tâches pour rejouer toute E/S qui était en cours au moment de la sauvegarde. L'application démarre ensuite normalement.

Pour l'essentiel, toute application pouvant résister à une panne de courant ou à une panne de serveur sans corruption des données peut être protégée de cette façon. Le fait que cela fonctionne peut également être démontré par le grand nombre d'applications protégées par des produits de mise en miroir synchrone et asynchrone de nombreux fournisseurs différents. Si un incident frappe soudainement le site principal, le site de réplica contient une image cohérente de l'environnement d'origine au moment où l'incident s'est produit. Une fois de plus, aucune procédure de récupération spéciale n'est requise.

L'objectif de point de restauration (RPO) pour cette approche est généralement limité au point de sauvegarde. En règle générale, le RPO minimal pour une sauvegarde cohérente après panne est d'une heure. Par exemple, 48 instantanés horaires plus 30 jours d'instantanés nocturnes constituent une solution raisonnable et n'exigent pas la conservation d'un nombre excessif d'instantanés. Un RPO inférieur à une heure devient plus difficile à atteindre et il n'est pas recommandé sans avoir d'abord consulté les NetApp Professional Services afin de comprendre l'environnement, l'échelle et les exigences en matière de protection des données.

Le RTO se mesure généralement en secondes. Lorsqu'une application est arrêtée, les volumes NFS, les LUN ou les espaces de noms NVMe sont restaurés, puis l'application est redémarrée.

L'approche la plus simple consiste à placer tous les fichiers ou LUN dans un seul volume AFF ou LUN/espace de noms ASA. Lorsqu'un ensemble de données doit s'étendre sur plusieurs ressources de stockage, un groupe de cohérence est nécessaire. Cela peut être configuré à l'aide de System Manager ou d'appels d'API RESTful, et SnapCenter est capable de créer un instantané simple de groupe de cohérence.



== Architecture de réplication et de reprise après incident

Cette section traite de la protection des données à distance, pour laquelle les données sont répliquées vers un site distant à des fins de stockage hors site sécurisé et de reprise sur incident. Notez que ces tableaux ne traitent pas de la protection des données de mise en miroir synchrone. Pour cette exigence, consultez la documentation NetApp MetroCluster, y compris link:oracle-dr-mcc-failover.html["MetroCluster"] et link:oracle-dr-smas-overview.html["Synchronisation active SnapMirror"]

Le RPO de reprise sur incident est limité par la bande passante réseau disponible et la taille totale des données protégées. Une fois le transfert de base initial créé, les mises à jour sont uniquement basées sur les données modifiées, ce qui représente généralement un faible pourcentage de l'empreinte totale des données, même si des exceptions existent.

Par exemple, une base de données de 10 To avec un taux de modification hebdomadaire de 10 % représente en moyenne 6 Go de modifications totales par heure. Avec une connectivité de 10 Gb, ce transfert de base de données prend environ 6 minutes. Le taux de modification varie en fonction des fluctuations du taux de modification de la base de données, mais dans l'ensemble, un intervalle de mise à jour de 15 minutes et un objectif de point de récupération de 15 minutes doivent être atteints. S'il existe 100 bases de données de ce type, 600 minutes sont nécessaires pour transférer les données. Par conséquent, un objectif RPO d'une heure n'est pas possible. De même, une réplique d'une seule base de données de 100 To avec un taux de modification hebdomadaire de 10 % ne peut pas être mise à jour de manière fiable en une heure.

D'autres facteurs peuvent affecter la réplication, tels que la surcharge liée à la réplication et les limitations du nombre d'opérations de réplication simultanées. Cependant, la planification globale d'une stratégie de réplication sur une seule ressource peut être basée sur la bande passante disponible, et un RPO de réplication d'une heure est généralement atteignable. Un RPO inférieur à une heure est plus difficile à obtenir et ne devrait être mis en œuvre qu'après consultation des NetApp Professional Services. Dans certains cas, un délai de 15 minutes est envisageable avec une excellente connectivité réseau entre les sites. Toutefois, de manière générale, lorsqu'un RPO inférieur à une heure est requis, l'architecture de relecture des journaux multi-ressources offre de meilleurs résultats.

Dans un scénario de reprise d'activité, le RTO avec réplication de groupe de cohérence est excellent, généralement mesuré en secondes du point de vue du stockage. L'approche la plus simple est de mettre simplement en miroir et la base de données est prête à être démarrée. Le temps de démarrage de la base de données est généralement d'environ 10 secondes, mais les bases de données très volumineuses qui génèrent un grand nombre de transactions consignées peuvent prendre quelques minutes.

Le facteur le plus important pour déterminer l'objectif de durée de restauration n'est pas le système de stockage, mais l'application et le système d'exploitation hôte sur lesquels il s'exécute. Par exemple, les données répliquées peuvent être disponibles en une ou deux secondes, mais elles ne représentent que les données. Il doit également y avoir un système d'exploitation correctement configuré avec des binaires d'application disponibles pour utiliser les données.

Dans certains cas, les clients ont préparé des instances de reprise après incident à l'avance, avec le stockage prédécouvert sur les systèmes d'exploitation. Dans ce cas, l'activation du scénario de reprise d'activité ne peut nécessiter que la rupture d'un miroir et le démarrage de l'application. Dans d'autres cas, le système d'exploitation et les applications associées peuvent être mis en miroir avec la base de données en tant que disque de machine virtuelle ESX (VMDK). Dans ce cas, le RPO est déterminé par la quantité investie par un client dans l'automatisation pour démarrer rapidement le VMDK afin de pouvoir démarrer les applications.

La durée de conservation est en partie déterminée par la limite de snapshots. Par exemple, les volumes AFF et les LUN ASA dans ONTAP sont limités à 1024 snapshots. Dans certains cas, les clients ont recours à la réplication multiplexée pour augmenter cette limite. Par exemple, si 2000 jours de sauvegardes sont nécessaires, une source peut être répliquée vers deux destinations différentes, les mises à jour étant effectuées un jour sur deux. Cette solution requiert un espace initial plus important, mais elle reste bien plus efficace qu’un système de sauvegarde traditionnel, qui implique plusieurs sauvegardes complètes.



=== groupe de cohérence à volume unique (AFF)

La solution la plus simple consiste à placer tous les fichiers ou LUN dans un seul volume. Un volume constitue un groupe de cohérence à part entière, ce qui signifie que les mises à jour SnapMirror et SnapVault peuvent être planifiées directement sur le système de stockage. Aucun logiciel externe n'est requis.



=== Groupe de cohérence à LUN/namespace unique (ASA)

Bien qu'il puisse paraître étrange de placer une base de données entière sur un seul LUN/espace de noms, cette pratique est de plus en plus courante. Les gestionnaires de volumes ont été initialement créés pour pallier les limitations de performance et de capacité des disques physiques. Avec les baies modernes, un périphérique de stockage par blocs présenté à un hôte est déjà abstrait et réparti sur plusieurs disques. Sa taille peut être ajustée dynamiquement et ses performances sont bien supérieures à celles d'un disque individuel.

Il en résulte que des charges de travail allant d'un datastore ESX à une base de données Oracle peuvent souvent être hébergées sur un seul périphérique de stockage par blocs. Cela simplifie considérablement la gestion des données et présente des avantages indirects, comme des temps de redémarrage des hôtes plus rapides grâce à la réduction du nombre de périphériques à détecter.



=== Groupe de cohérence multivolume

Lorsqu'une base de données doit s'étendre sur des volumes AFF ou des LUN/espaces de noms ASA, une capture instantanée de groupe de cohérence est requise. Comme mentionné ci-dessus, cela peut être configuré à l'aide de System Manager ou d'appels d'API RESTful, et SnapCenter est capable de créer une simple capture instantanée de groupe de cohérence.

Il convient également de prendre en compte un point supplémentaire concernant l'utilisation de snapshots cohérents multi-volumes AFF ou multi-LUN ASA à des fins de reprise après sinistre. Lors de la mise à jour de plusieurs relations SnapMirror, il est possible qu'un sinistre survienne pendant qu'un transfert est encore en cours. Il en résulterait un ensemble de volumes, de LUN ou d'espaces de noms qui ne sont pas cohérents entre eux. Si cela se produisait, certains volumes devraient être restaurés à un état de snapshot antérieur afin de fournir une image de base de données cohérente après panne et prête à l'emploi.



== Reprise après incident : activation



=== NFS

Le processus d'activation de la copie de reprise sur incident dépend du type de stockage. Avec NFS, les systèmes de fichiers peuvent être prémontés sur le serveur de reprise après incident. Ils sont en lecture seule et deviennent en lecture-écriture lorsque le miroir est cassé. Le RPO est ainsi extrêmement faible, et le processus global de reprise sur incident est plus fiable, car la gestion comporte moins de pièces.



=== SAN

L'activation des configurations SAN en cas de reprise après incident devient plus complexe. L'option la plus simple consiste généralement à interrompre temporairement les miroirs et à monter les ressources SAN, notamment à découvrir la configuration LVM (y compris les fonctionnalités spécifiques à l'application telles qu'Oracle Automatic Storage Management [ASM]) et à ajouter des entrées à /etc/fstab.

Le résultat est que les chemins du périphérique LUN, les noms des groupes de volumes et les autres chemins de périphériques sont connus du serveur cible. Ces ressources peuvent ensuite être désactivées, puis les miroirs peuvent être restaurés. Le résultat est un serveur qui est dans un état qui peut rapidement mettre l'application en ligne. Les étapes permettant d'activer des groupes de volumes, de monter des systèmes de fichiers ou de démarrer des bases de données et des applications sont facilement automatisables.

Il faut veiller à ce que l'environnement de reprise d'activité soit à jour. Par exemple, de nouvelles LUN sont susceptibles d'être ajoutées au serveur source, ce qui signifie que les nouvelles LUN doivent être prédécouvertes sur la destination pour s'assurer que le plan de reprise sur incident fonctionne comme prévu.
