---
sidebar: sidebar 
permalink: oracle/oracle-dr-snapmirror-cg.html 
keywords: oracle, data protection, DR, CG 
summary: Réplication de groupe de cohérence pour les bases de données Oracle 
---
= Reprise d'activité par groupe de cohérence
:allow-uri-read: 


[role="lead"]
La réplication de groupe de cohérence peut être aussi simple que la planification de la réplication d'un volume unique via SnapMirror. Notamment les fichiers de données, les fichiers de contrôle, les journaux d'archivage et les journaux de reprise. Chaque mise à jour SnapMirror produit une nouvelle copie cohérente de la base de données sur le site de destination, prête pour l'activation en brisant le miroir.

Si une base de données doit couvrir plusieurs volumes, un Snapshot de groupe de cohérence (cg-snapshot) est nécessaire.

Autre avantage de cette stratégie lorsqu'elle est utilisée avec SnapMirror en mode de réplication de niveau bloc : la réplication complète de tous les snapshots sur le système de stockage source. La gamme complète de sauvegardes est répliquée en plus de la copie de reprise après incident.
