---
permalink: oracle/oracle-asar2-app-config-mbr.html 
sidebar: sidebar 
keywords: oracle, database, ASA r2, ontap, db_file_multiblock_read_count, multiblock 
summary: Paramètres de base de données Oracle - db_file_multiblock_read_count avec ASA r2 
searchtitle: Paramètres de base de données Oracle - db_file_multiblock_read_count avec ASA r2 
---
= db_file_multibloc_read_count
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le `db_file_multiblock_read_count` Paramètre contrôle le nombre maximal de blocs de base de données Oracle lus par Oracle au cours d'une opération, pendant les E/S séquentielles

Les recommandations restent inchangées par rapport aux systèmes AFF/ FAS . Le comportement ONTAP et les meilleures pratiques d'Oracle restent identiques sur les plateformes ASA r2, AFF et FAS .

Toutefois, ce paramètre n'affecte pas le nombre de blocs lus par Oracle au cours des opérations de lecture, ni le nombre d'E/S aléatoires Seule la taille de bloc des E/S séquentielles est affectée.

Oracle recommande à l'utilisateur de ne pas définir ce paramètre. Cela permet au logiciel de base de données de définir automatiquement la valeur optimale. Cela signifie généralement que ce paramètre est défini sur une valeur qui produit une taille d'E/S de 1 Mo. Par exemple, une lecture de 1 Mo de blocs de 8 Ko nécessite la lecture de 128 blocs. La valeur par défaut de ce paramètre est donc 128.

La plupart des problèmes de performance de base de données observés par NetApp sur les sites des clients provenaient de paramètres incorrects. Des raisons valides ont été données pour modifier cette valeur avec les versions 8 et 9 d'Oracle. Par conséquent, le paramètre peut être présent sans le savoir dans `init.ora` Fichiers car la base de données a été mise à niveau vers Oracle 10 et versions ultérieures. La configuration héritée de 8 ou 16, par rapport à la valeur par défaut 128, nuit de manière significative aux performances d'E/S séquentielles.


TIP: *NetApp recommande* de régler le `db_file_multiblock_read_count` le paramètre ne doit pas être présent dans le `init.ora` fichier. NetApp n'a jamais observé d'amélioration des performances suite à la modification de ce paramètre, mais le débit d'E/S séquentielles subit une importante dégradation dans de nombreux cas.
