---
sidebar: sidebar 
permalink: oracle/oracle-dr-smas-fail-restore.html 
keywords: Oracle, SnapMirror active sync, SMBC, failover 
summary: Synchronisation active Oracle et SnapMirror - restauration du service 
searchtitle: Synchronisation active Oracle et SnapMirror - restauration du service 
---
= Restauration du service
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SnapMirror propose une fonctionnalité d'autorétablissement. La synchronisation active SnapMirror détecte automatiquement la présence d'une relation de réplication défectueuse et la ramène à un état RPO=0. Une fois la réplication synchrone rétablie, les chemins reviennent en ligne.

Dans de nombreux cas, les applications en cluster détectent automatiquement le retour des chemins défaillants, et ces applications sont également reconnectées. Dans d'autres cas, une analyse SAN au niveau de l'hôte peut être nécessaire ou les applications doivent être reconnectées manuellement.

Cela dépend de l'application et de la façon dont elle est configurée et, en général, ces tâches peuvent être facilement automatisées. La synchronisation active SnapMirror elle-même est auto-fixing et ne nécessite aucune intervention de l'utilisateur pour reprendre les opérations de stockage avec un objectif de point de récupération de 0 une fois l'alimentation et la connectivité restaurées.
