---
sidebar: sidebar 
permalink: oracle/oracle-dp-snaprestore.html 
keywords: ontap, snaprestore 
summary: Restauration rapide de la base de données Oracle grâce aux snapshots 
searchtitle: Restauration rapide de la base de données Oracle grâce aux snapshots 
---
= SnapRestore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La restauration rapide des données dans ONTAP à partir d'un instantané est assurée par la technologie NetApp SnapRestore, qui vous permet de restaurer instantanément l'état d'un volume AFF ou d'un LUN ASA.

Lorsqu'un dataset stratégique n'est pas disponible, les opérations stratégiques de l'entreprise ne sont pas disponibles. Les bandes peuvent se rompre, et même les restaurations à partir de sauvegardes sur disque peuvent être lentes à transférer sur le réseau. SnapRestore évite ces problèmes en offrant une restauration quasi instantanée des datasets. Même les bases de données de plusieurs pétaoctets peuvent être entièrement restaurées en quelques minutes à peine.

Bien que la technologie de base soit la même sur les plateformes AFF et ASA, leur utilisation diffère légèrement.



== Aperçu du AFF

Il existe deux formes de SnapRestore sur un système AFF : au format fichier et au format volume :

* Les fichiers AFF, les LUN et les espaces de noms individuels, ainsi que les LUN et les espaces de noms ASA individuels, peuvent être restaurés en quelques secondes, qu'il s'agisse d'un LUN de 2 To ou d'un fichier de 4 Ko.
* Le contenu intégral d'un volume AFF peut être restauré en quelques secondes, qu'il s'agisse de 10 Go ou de 100 To de données.


La raison pour laquelle SnapRestore fonctionne aussi rapidement et efficacement s'explique par la nature même d'un instantané, qui est essentiellement une vue parallèle en lecture seule du contenu d'un volume, d'un LUN ou d'un espace de noms à un instant précis. Les blocs actifs sont les vrais blocs qui peuvent être modifiés, tandis que l'instantané est une vue en lecture seule de l'état des blocs constituant les fichiers et les LUN au moment où l'instantané a été créé.

ONTAP n'autorise qu'un accès en lecture seule aux données d'instantané, mais ces données peuvent être réactivées avec SnapRestore. L'instantané est alors réactivé en tant que vue en lecture-écriture des données, restaurant ainsi leur état antérieur. SnapRestore peut s'effectuer au niveau du volume, du fichier, du LUN ou de l'espace de noms. La technologie reste fondamentalement la même, à quelques différences mineures près dans son comportement.



=== Volume AFF SnapRestore

La restauration basée sur le volume SnapRestore permet de rétablir l'intégralité du contenu d'un volume à un état antérieur. Cette opération ne nécessite pas de déplacement des données, ce qui signifie que le processus de restauration est essentiellement instantané, même si l'opération via l'API ou l'interface de ligne de commande peut prendre quelques secondes à être traitée. Restaurer 1 Go de données n'est pas plus complexe ni plus long que de restaurer 1 Po de données. Cette capacité est la principale raison pour laquelle de nombreux clients d'entreprise migrent vers les systèmes de stockage ONTAP. Elle garantit un RTO mesuré en secondes, même pour les ensembles de données les plus volumineux.

L'un des inconvénients des SnapRestore sur volume est le fait que les modifications au sein d'un volume sont cumulées dans le temps. Par conséquent, chaque snapshot et les données de fichier actives dépendent des modifications apportées jusqu'à ce point. Le rétablissement d'un volume à un état antérieur implique la suppression de toutes les modifications ultérieures apportées aux données. Ce qui est moins évident, cependant, c'est qu'il s'agit d'instantanés créés par la suite. Ce n'est pas toujours souhaitable.

Par exemple, un SLA de conservation des données peut spécifier 30 jours de sauvegardes nocturnes. La restauration d'un dataset sur un snapshot créé il y a cinq jours avec SnapRestore du volume abandonnerait tous les snapshots créés les cinq jours précédents, en violation du SLA.

Un certain nombre d'options sont disponibles pour résoudre cette limitation :

. Les données peuvent être copiées à partir d'un instantané précédent, au lieu d'effectuer une SnapRestore du volume entier. Cette méthode fonctionne mieux avec les jeux de données plus petits.
. Un snapshot peut être cloné plutôt que restauré. La limitation à cette approche est que le snapshot source dépend du clone. Par conséquent, elle ne peut pas être supprimée si le clone n'est pas également supprimé ou s'il est divisé en volume indépendant.
. Utilisation d'un SnapRestore basé sur des fichiers.




=== AFF Fichier SnapRestore

La restauration basée sur les fichiers SnapRestore est un processus de restauration plus granulaire basé sur les instantanés, utilisé avec les volumes AFF. Au lieu de rétablir l'état d'un volume entier, l'état d'un fichier, d'un LUN ou d'un espace de noms individuel est rétabli. Aucun instantané n'a besoin d'être supprimé, et cette opération ne crée aucune dépendance à un instantané précédent. Le fichier ou le LUN devient immédiatement disponible dans le volume actif.

Aucun déplacement des données n'est requis lors d'une restauration SnapRestore d'un fichier ou d'un LUN. Toutefois, certaines mises à jour de métadonnées internes sont nécessaires pour refléter le fait que les blocs sous-jacents des données restaurées existent désormais à la fois dans un instantané et dans le volume actif. Ce processus n'a aucun impact sur les performances, mais il bloque la création d'instantanés jusqu'à son achèvement. Le débit de traitement est d'environ 5 Go/s (18 To/h) en fonction de la taille totale des fichiers restaurés.



== Restauration de LUN/namespace ASA

La restauration des données sur ASA est similaire à AFF SnapRestore. Les données sont simplement restaurées à un état antérieur. Le processus est quasi instantané et ne nécessite pas de déplacement des données. Il présente également les mêmes limitations, notamment l'obligation que la restauration d'un snapshot entraîne la suppression des snapshots supprimés ultérieurement. Si cela pose problème, deux solutions sont possibles. Premièrement, un LUN/espace de noms peut être cloné à partir d'un snapshot antérieur sans modifier le volume source. Ce processus est instantané et peu gourmand en espace. Il consiste essentiellement à créer une copie en lecture-écriture du pointeur en lecture seule vers les blocs d'un snapshot. La seconde solution utilise l'API REST, qui exploite la même logique de fichier unique SnapRestore utilisée dans les systèmes AFF. Le résultat est une restauration instantanée d'un LUN/espace de noms à partir des données d'un snapshot et tous les snapshots sont préservés.
