---
sidebar: sidebar 
permalink: oracle/oracle-dr-snapmirror-basics.html 
keywords: ontap, snapmirror 
summary: Bases de données Oracle avec SnapMirror et SyncMirror 
---
= Bases de données Oracle avec SnapMirror et SyncMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Presque toutes les applications nécessitent une réplication des données.

Au niveau le plus élémentaire, la réplication peut signifier une copie sur bande stockée hors site ou une réplication au niveau des applications vers un emplacement de secours. La reprise après incident fait référence à l'utilisation de ces copies de réplica pour mettre un service en ligne en cas de perte catastrophique de service.

ONTAP propose plusieurs options de réplication pour répondre de nombreuses exigences de manière native à l'intérieur de la baie de stockage et couvrir un large éventail de besoins. Ces options peuvent inclure une simple réplication des sauvegardes vers un site distant jusqu'à une solution synchrone et entièrement automatisée qui assure à la fois la reprise après incident et la haute disponibilité sur la même plateforme.

Les principales technologies de réplication ONTAP applicables aux applications sont les technologies NetApp SnapMirror et NetApp SyncMirror. Il ne s'agit pas de produits complémentaires ; ils sont plutôt entièrement intégrés à ONTAP et sont activés par l'ajout simple d'une clé de licence. La réplication au niveau du stockage n'est pas la seule option non plus. La réplication au niveau des applications, comme avec Oracle DataGuard, peut également s'intégrer à une stratégie de protection des données basée sur ONTAP.

Le bon choix dépend des exigences spécifiques en matière de réplication, de restauration et de conservation.



== SnapMirror ONTAP

SnapMirror est la solution de réplication asynchrone NetApp. Elle est idéale pour protéger des datasets volumineux, complexes et dynamiques, tels que les bases de données et les applications associées. Ses valeurs clés sont les suivantes :

* *Gérabilité.* SnapMirror est facile à configurer et à gérer car il fait partie intégrante du logiciel de stockage. Aucun produit complémentaire n'est requis. Les relations de réplication peuvent être établies en quelques minutes et gérées directement sur le système de stockage.
* *Simplicité.* la réplication est basée sur des volumes FlexVol, qui sont des conteneurs de LUN ou de fichiers répliqués comme un seul groupe cohérent.
* *Efficacité.* une fois la relation de réplication initiale établie, seuls les changements sont répliqués. De plus, des fonctionnalités d'efficacité comme la déduplication et la compression sont préservées. De plus, le volume de données à transférer vers un site distant est réduit.
* *Flexibilité.* les miroirs peuvent être temporairement brisés pour permettre le test des procédures de reprise après sinistre, et ensuite la mise en miroir peut être facilement rétablie sans besoin d'une remise en miroir complète. Seules les données modifiées doivent être appliquées pour que les miroirs soient synchronisés. La mise en miroir peut également être inversée pour permettre une resynchronisation rapide après la fin de l'incident et la remise en service du site d'origine. Enfin, les clones en lecture-écriture des données répliquées sont disponibles à des fins de test et de développement.


ONTAP propose plusieurs technologies de réplication, mais la plus flexible est SnapMirror, une option de mise en miroir asynchrone volume à volume.

Comme mentionné précédemment, un volume FlexVol est l'unité de gestion de base des sauvegardes basées sur des copies Snapshot et des restaurations basées sur SnapRestore. Un volume FlexVol est également l'unité de base de la réplication basée sur SnapMirror. La première étape consiste à établir le miroir de base du volume source vers le volume de destination. Une fois cette relation miroir initialisée, toutes les opérations suivantes sont basées uniquement sur la réplication des données modifiées.

Les valeurs clés de SnapMirror sont les suivantes du point de vue de la restauration :

* Les opérations SnapMirror sont simples à comprendre et peuvent être facilement automatisées.
* Une simple mise à jour d'un réplica SnapMirror nécessite la réplication de seules les modifications de delta, ce qui réduit les besoins en bande passante et permet des mises à jour plus fréquentes.
* SnapMirror est hautement granulaire. Elle repose sur de simples relations volume à volume, ce qui permet de créer des centaines de répliques gérées de manière indépendante et d'intervalles de réplication. La réplication n'a pas besoin d'être universelle.
* La direction de symétrie peut être facilement inversée tout en conservant la possibilité de mettre à jour la relation en fonction des modifications seules. Il est ainsi possible de restaurer rapidement le site principal après un incident, comme une panne de courant. Seules les modifications doivent être synchronisées à nouveau vers la source.
* Les miroirs peuvent être facilement brisés et efficacement resynchés pour permettre la répétition des procédures de reprise après sinistre.
* Si SnapMirror fonctionne en mode de réplication complète au niveau des blocs, il réplique non seulement les données d'un volume, mais aussi les copies Snapshot. Cette fonctionnalité permet à la fois de copier les données et d'effectuer un jeu complet de sauvegardes sur le site de reprise après incident.


SnapMirror s'exécutant en mode flexible de la version permet la réplication de snapshots spécifiques, permettant des durées de conservation différentes au niveau des sites principal et secondaire.



== SnapMirror synchrone

SnapMirror synchrone (SM-S) est une amélioration apportée à SnapMirror qui fournit une réplication synchrone RPO=0. Elle est le plus souvent utilisée dans les architectures de stockage où seule une partie du volume total de données nécessite une mise en miroir synchrone.

SM-S peut fonctionner dans deux modes légèrement différents, Sync et StrictSync.

En mode synchrone, les modifications sont répliquées avant d'être acquittées. Cela garantit un RPO de zéro, tant que la réplication est opérationnelle. Si la modification ne peut pas être répliquée, SM-S peut quitter le mode synchrone et permettre aux opérations de continuer. Cela permet à RPO=0 dans des circonstances normales, mais les processus de données ne s'arrêtent pas complètement si la destination de réplication n'est pas disponible.

StrictSync garantit un RPO=0. Si les modifications ne sont pas répliquées, le système génère une erreur d'E/S qui provoque généralement l'arrêt d'une application.

Pour une explication complète de SM-S, voir https://www.netapp.com/media/17174-tr4733.pdf?v=1221202075448P["TR-4733"^] Et la documentation officielle de ONTAP. Des fonctionnalités sont ajoutées en permanence avec les nouvelles versions de ONTAP.



== Groupes de cohérence

ONTAP permet de créer des snapshots de groupes de cohérence. Depuis la version 9.13.1, ONTAP peut répliquer des groupes de volumes (n'oubliez pas qu'un volume dans la terminologie ONTAP n'est pas une LUN, il s'agit d'un conteneur de gestion constitué d'un ou plusieurs fichiers ou LUN) en tant que groupe cohérent.

La réplication SnapMirror et la relation SnapMirror de groupe de cohérence continue préservent la cohérence entre les volumes. Les technologies SnapMirror synchrone et SnapMirror synchrone et la synchronisation active préservent la cohérence entre les volumes constitutifs.

Vous pouvez ainsi répliquer un jeu de données multi-volumes et vous assurer que tous les volumes sont cohérents. Cela permet notamment de réaliser des opérations de reprise après incident « rompez le miroir et Go » sans avoir besoin d'étapes supplémentaires pour la restauration d'applications ou de bases de données.



== MetroCluster et SyncMirror

MetroCluster est également une solution de réplication synchrone conçue pour les workloads stratégiques à grande échelle. La réplication est basée sur SyncMirror. Au niveau de la couche la plus simple, SyncMirror crée deux ensembles complets de données protégées par RAID à deux emplacements différents. Elles peuvent se trouver dans des pièces adjacentes au sein d'un data Center ou bien se trouver à plusieurs kilomètres de distance.

SyncMirror est totalement intégré à ONTAP et fonctionne juste au-dessus du niveau RAID. Par conséquent, toutes les fonctionnalités ONTAP habituelles, telles que les copies Snapshot, SnapRestore et NetApp FlexClone, fonctionnent de manière transparente. Il s'agit toujours d'une technologie ONTAP, qui inclut juste une couche supplémentaire de mise en miroir synchrone des données.

Un ensemble de contrôleurs ONTAP gérant les données SyncMirror est appelé configuration NetApp MetroCluster. L'objectif principal de MetroCluster est de fournir un accès haute disponibilité aux données en miroir synchrones dans de nombreux scénarios de défaillance courants et de reprise après incident.

Les valeurs clés de la protection des données avec MetroCluster et SyncMirror sont les suivantes :

* Dans les opérations normales, SyncMirror fournit une mise en miroir synchrone garantie entre plusieurs sites. Une opération d'écriture n'est pas validée tant qu'elle n'est pas présente sur un support non volatile des deux sites.
* En cas de défaillance de la connectivité entre les sites, SyncMirror passe automatiquement en mode asynchrone pour que le site principal assure le service de données jusqu'à ce que la connectivité soit rétablie. Une fois restaurée, elle permet une resynchronisation rapide en mettant efficacement à jour les modifications qui se sont accumulées sur le site primaire. Une réinitialisation complète n'est pas nécessaire.


SnapMirror est également entièrement compatible avec les systèmes basés sur SyncMirror. Par exemple, une base de données primaire peut s'exécuter sur un cluster MetroCluster réparti sur deux sites géographiques. Cette base de données peut également répliquer les sauvegardes sur un troisième site en tant qu'archives à long terme ou pour créer des clones dans un environnement DevOps.
