---
sidebar: sidebar 
permalink: oracle/oracle-dp-consistency-group-backup.html 
keywords: oracle, data, protection, consistency, group, backup, volume, archive, log, redo, controlfiles 
summary: Sauvegardes de groupes de cohérence pour les bases de données Oracle sur ONTAP 
searchtitle: Sauvegardes de groupes de cohérence de la base de données Oracle 
---
= Sauvegardes de groupes de cohérence
:allow-uri-read: 


[role="lead"]
Pour une sauvegarde aussi simple que possible, il suffit de placer l'intégralité de la base de données Oracle dans un seul volume ONTAP, LUN ou espace de noms NVMe.

La protection des fichiers de données, des journaux d'archivage, des journaux de restauration et des fichiers de contrôle par un seul instantané constitue une méthode de sauvegarde, de restauration et de réplication valide. Cependant, le RPO est limité au point de la sauvegarde lui-même. Elle convient pour un RPO d'une heure ou plus. Si une base de données s'étend sur des volumes AFF ou des unités de stockage ASA, des groupes de cohérence sont nécessaires à l'aide de l'un des outils mentionnés précédemment.

À titre d'exemple, la base de données peut tenir dans un seul volume AFF avec la planification d'instantanés suivante :

* 72 snapshots par heure
* 30 snapshots de nuit
* 12 snapshots mensuels


Cela garantit un RPO d'une heure sur la période glissante des 72 heures précédentes, ainsi que des sauvegardes nocturnes et mensuelles supplémentaires. Plusieurs bases de données ou fichiers d'application peuvent également être inclus dans un volume unique ou un ensemble de snapshots de groupe de cohérence afin d'assurer des sauvegardes cohérentes dans un environnement étendu.
