---
sidebar: sidebar 
permalink: oracle/oracle-network-config-direct-connect.html 
keywords: direct-connect, oracle 
summary: Base de données Oracle et connectivité ONTAP à connexion directe 
searchtitle: Base de données Oracle et connectivité ONTAP à connexion directe 
---
= Réseau à connexion directe
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les administrateurs système préfèrent parfois simplifier leurs infrastructures en supprimant les commutateurs réseau de la configuration. Cela permet de créer une solution plus autonome avec moins de composants et un encombrement réduit dans la baie. Il existe des restrictions importantes qui dépendent du protocole utilisé.



[[fiber-channel]]
=== Fibre Channel

À partir d'ONTAP 9.19.1, la connexion FC directe est prise en charge avec les SAN FC traditionnels (SCSI) et NVMe/FC avec certains adaptateurs FC pour systèmes de stockage. Les HBA établiront une connexion FC point à point standard. Avant ONTAP 9.19.1, les systèmes de stockage ONTAP nécessitent NPIV, ce qui signifie que le système de stockage doit être connecté à un commutateur FC qui prend également en charge NPIV.



[[iscsi-and-nvmetcp]]
=== ISCSI et NVMe/TCP

Un hôte utilisant iSCSI ou NVMe/TCP peut être directement connecté à un système de stockage et fonctionner normalement. La raison en est le chemin d'accès. Les connexions directes à deux contrôleurs de stockage distincts donnent lieu à deux chemins de flux de données indépendants. La perte du chemin, du port ou du contrôleur n'empêche pas l'autre chemin d'être utilisé.



[[nfs]]
=== NFS

Vous pouvez utiliser un stockage NFS à connexion directe, mais avec une limitation importante : le basculement ne fonctionnera pas sans script important, ce qui incombera au client.

Ce qui complique la reprise après incident avec un stockage NFS à connexion directe, c'est le routage qui se produit sur le système d'exploitation local. Par exemple, supposons qu'un hôte a une adresse IP 192.168.1.1/24 et qu'il est directement connecté à un contrôleur ONTAP avec une adresse IP 192.168.1.50/24. Lors du basculement, cette adresse 192.168.1.50 peut basculer vers l'autre contrôleur et sera disponible pour l'hôte, mais comment l'hôte peut-il détecter sa présence ? L'adresse 192.168.1.1 d'origine existe toujours sur la carte réseau hôte qui ne se connecte plus à un système opérationnel. Le trafic destiné à 192.168.1.50 continuerait d'être envoyé à un port réseau inutilisable.

La seconde carte réseau du système d'exploitation pourrait être configurée avec l'adresse 192.168.1.2 et serait capable de communiquer avec l'adresse de basculement 192.168.1.50, mais les tables de routage locales auraient par défaut l'utilisation d'une *et une seule* adresse pour communiquer avec le sous-réseau 192.168.1.0/24. Un administrateur système pourrait créer un cadre de scripts permettant de détecter une défaillance de connexion réseau et de modifier les tables de routage locales ou d'activer/désactiver des interfaces. La procédure exacte dépendrait du système d'exploitation utilisé.

Dans la pratique, les clients NetApp disposent d'un protocole NFS à connexion directe, mais généralement uniquement pour les charges de travail où une pause des E/S est acceptable pendant les basculements. Lorsque des montages durs sont utilisés, aucune erreur d'E/S ne doit se produire lors de ces pauses. L'E/S doit se bloquer jusqu'à ce que les services soient restaurés, soit par un retour arrière, soit par une intervention manuelle pour déplacer les adresses IP entre les cartes réseau de l'hôte.
