---
permalink: oracle/oracle-asar2-app-config-filesystemio_options.html 
sidebar: sidebar 
keywords: oracle, database, ASA r2, ontap, filesystemio_options, filesystemio, async, directio 
summary: 'Paramètres de base de données Oracle - options d"E/S du système de fichiers avec ASA r2' 
searchtitle: 'Paramètres de base de données Oracle - options d"E/S du système de fichiers avec ASA r2' 
---
= filesytemio_options
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le paramètre d'initialisation Oracle `filesystemio_options` Contrôle l'utilisation des E/S asynchrones et directes

Le comportement et les recommandations concernant filesystemio_options sur ASA r2 sont identiques à ceux des systèmes AFF/ FAS , car ce paramètre est spécifique à Oracle et ne dépend pas de la plateforme de stockage. ASA r2 utilise ONTAP comme AFF/ FAS, donc les mêmes bonnes pratiques s'appliquent.

Contrairement à une idée reçue, ces deux types d'E/S ne s'excluent pas mutuellement. NetApp a observé que ce paramètre est souvent mal configuré dans les environnements des clients. Cette configuration incorrecte est la cause directe de nombreux problèmes de performances.

Les E/S asynchrones offrent la possibilité de paralléliser les opérations Oracle d'E/S. Avant la disponibilité des E/S asynchrones sur différents systèmes d'exploitation, les utilisateurs ont configuré de nombreux processus dbwriter et modifié la configuration du processus serveur. Avec les E/S asynchrones, le système d'exploitation lui-même exécute les E/S en parallèle pour le compte du logiciel de base de données. Ce processus ne présente aucun risque pour les données et les opérations critiques, telles que la journalisation de reprise Oracle, sont toujours exécutées de manière synchrone.

Les E/S directes contournent le cache du tampon du système d'exploitation. Sur un système UNIX, les E/S transitent normalement par le cache du tampon du système d'exploitation. Ceci est utile pour les applications qui ne maintiennent pas de cache interne, mais Oracle dispose de son propre cache de tampon dans la SGA. Dans la plupart des cas, il est préférable d'activer les E/S directes et d'allouer la RAM du serveur à la mémoire SGA plutôt que d'utiliser le cache du tampon du système d'exploitation. La SGA exploite la mémoire plus efficacement. En outre, lors de leur transit via le tampon du se, les E/S sont soumises à un traitement supplémentaire, ce qui augmente les latences. Cette augmentation est particulièrement visible lors des E/S intenses en écriture, pour lesquelles la faible latence est primordiale.

Les options pour `filesystemio_options` sont :

* *Async.* Oracle soumet des demandes d'E/S au système d'exploitation pour traitement. Ce qui lui permet d'effectuer d'autres tâches plutôt que d'attendre la fin des E/S et d'augmenter ainsi la parallélisation des E/S.
* *Directio.* Oracle effectue des E/S directement par rapport aux fichiers physiques plutôt que de router les E/S via le cache du système d'exploitation hôte.
* *None.* Oracle utilise des E/S synchrones et mises en tampon Dans cette configuration, le choix entre les processus serveur partagés et dédiés et le nombre de dbwriter est plus important.
* *Setall.* Oracle utilise des E/S asynchrones et directes Dans presque tous les cas, l'utilisation de `setall` est optimale.



NOTE: Dans les environnements ASM, Oracle utilise automatiquement les E/S directes et asynchrones pour les disques gérés par ASM. `filesystemio_options` n'a aucun effet sur les groupes de disques ASM. Pour les déploiements non-ASM (par exemple, les systèmes de fichiers sur des LUN SAN), configurez : `filesystemio_options = setall`. Cela permet des E/S asynchrones et directes pour des performances optimales.

Certains systèmes d'exploitation plus anciens présentaient des problèmes avec les entrées/sorties asynchrones, ce qui a conduit à des conseils obsolètes suggérant de les éviter. Cependant, les E/S asynchrones sont stables et entièrement prises en charge par tous les systèmes d'exploitation actuels. Il n'y a aucune raison de le désactiver à moins qu'un bug spécifique du système d'exploitation ne soit identifié.

Si une base de données utilise des E/S mises en tampon, un switch vers des E/S directes peut également justifier une modification de la taille de la mémoire SGA. La désactivation des E/S mises en tampon élimine le gain de performance fourni par le cache du se hôte pour la base de données. L'ajout de RAM à la SGA résout ce problème. Et devrait améliorer les performances nettes d'E/S.

Bien qu'il soit presque toujours préférable d'utiliser la RAM pour la SGA d'Oracle plutôt que pour le cache du tampon du système d'exploitation, il peut s'avérer impossible de déterminer ce qui est le plus avantageux. Par exemple, il est parfois préférable d'utiliser des E/S mises en tampon avec une mémoire SGA de très petite taille sur un serveur de base de données comportant de nombreuses instances Oracle actives par intermittence. Cette configuration permet à toutes les instances de base de données en cours d'exécution d'utiliser de manière flexible la RAM restante sur le système d'exploitation. Cette situation est très inhabituelle, mais elle a été observée sur certains sites clients.


TIP: * NetApp recommande* de paramétrer `filesystemio_options` à `setall`, mais sachez que dans certaines circonstances, la perte du cache tampon de l'hôte peut nécessiter une augmentation de la SGA d'Oracle. Les systèmes ASA r2 sont optimisés pour les charges de travail SAN à faible latence, l'utilisation de setall s'aligne donc parfaitement avec la conception ASA pour les déploiements Oracle hautes performances.
