---
sidebar: sidebar 
permalink: oracle/oracle-asar2-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM, oracle, ASA r2 
summary: Alignement des LUN avec les bases de données Oracle sur ASA r2 
searchtitle: Alignement LUN pour les E/S de base de données Oracle avec ASA r2 
---
= Alignement de LUN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'alignement des LUN fait référence à l'optimisation des E/S par rapport à la disposition du système de fichiers sous-jacent.

Les systèmes ASA r2 utilisent la même architecture ONTAP que AFF/ FAS mais avec un modèle de configuration simplifié. Les systèmes ASA r2 utilisent des zones de disponibilité de stockage (SAZ) au lieu d'agrégats, mais les principes d'alignement restent les mêmes car ONTAP gère la disposition des blocs de manière cohérente sur toutes les plateformes. Veuillez toutefois noter les points spécifiques à ASA suivants :

* Les systèmes ASA r2 fournissent des chemins symétriques actifs-actifs pour tous les LUN, ce qui élimine les problèmes d'asymétrie de chemin lors de l'alignement.
* Les unités de stockage (LUN) sont provisionnées en mode fin par défaut ; l'alignement ne change pas ce comportement.
* La réservation de snapshots et la suppression automatique des snapshots peuvent être configurées lors de la création du LUN (ONTAP 9.18.1 et versions ultérieures).


Sur un système ONTAP, le stockage est organisé en unités de 4 Ko. Un bloc de 8 Ko de base de données ou de système de fichiers doit être mappé à exactement deux blocs de 4 Ko. Si une erreur de configuration de LUN déplace l'alignement de 1 Ko dans les deux sens, chaque bloc de 8 Ko existerait sur trois blocs de stockage de 4 Ko différents au lieu de deux. Cette configuration entraîne une augmentation de la latence et des E/S supplémentaires au sein du système de stockage.

L'alignement affecte également les architectures LVM. Si un volume physique au sein d'un groupe de volumes logiques est défini sur l'unité entière (aucune partition n'est créée), le premier bloc de 4 Ko de la LUN s'aligne sur le premier bloc de 4 Ko du système de stockage. Il s'agit d'un alignement correct. Des problèmes surviennent avec les partitions car elles déplacent l'emplacement de départ où le système d'exploitation utilise le LUN. Tant que le décalage est décalé en unités entières de 4 Ko, la LUN est alignée.

Dans les environnements Linux, créez des groupes de volumes logiques sur l'ensemble de l'unité de disque. Lorsqu'une partition est requise, vérifiez l'alignement en exécutant et en `fdisk -u` vérifiant que le début de chaque partition est un multiple de huit. Cela signifie que la partition démarre à un multiple de huit secteurs de 512 octets, soit 4 Ko.

Voir également la discussion sur l'alignement des blocs de compression dans la section link:oracle-ontap-config-efficiency.html["Efficacité"]. Toute disposition alignée avec les limites des blocs de compression de 8 Ko est également alignée avec les limites de 4 Ko.



== Avertissements de mauvais alignement

La journalisation des opérations de reprise et des transactions de la base de données génère normalement des E/S non alignées qui peuvent entraîner des avertissements erronés concernant les LUN mal alignées sur ONTAP.

La journalisation effectue une écriture séquentielle du fichier journal avec des écritures de taille variable. Une opération d'écriture de journal qui ne s'aligne pas sur les limites de 4 Ko ne provoque généralement pas de problèmes de performances, car l'opération d'écriture de journal suivante termine le bloc. ONTAP est ainsi en mesure de traiter la quasi-totalité des écritures sous forme de blocs complets de 4 Ko, même si les données de blocs de 4 Ko ont été écrites dans deux opérations distinctes.

Vérifiez l'alignement à l'aide d'utilitaires tels que `sio` ou `dd` qui peut générer des E/S à une taille de bloc définie. Les statistiques d'alignement des E/S sur le système de stockage peuvent être consultées avec le `stats` commande. Voir link:../notes/wafl_alignment_verification.html["Vérification de l'alignement WAFL"] pour plus d'informations.

L'alignement dans les environnements Solaris est plus compliqué. Reportez-vous à la section http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["Configuration de l'hôte SAN ONTAP"^] pour en savoir plus.

[CAUTION]
====
Dans les environnements Solaris x86, prenez davantage soin de l'alignement approprié car la plupart des configurations comportent plusieurs couches de partitions. Les tranches de partition Solaris x86 existent généralement au-dessus d'une table de partition d'enregistrement d'amorçage maître standard.

====
Autres bonnes pratiques :

* Vérifiez les paramètres du micrologiciel HBA et du système d'exploitation par rapport à l'outil de matrice d'interopérabilité NetApp (IMT).
* Utilisez les utilitaires sanlun pour vérifier l'état et l'alignement du chemin.
* Pour Oracle ASM et LVM, assurez-vous que les fichiers de configuration (/etc/lvm/lvm.conf, /etc/sysconfig/oracleasm) sont correctement configurés afin d'éviter les problèmes d'alignement.

