---
sidebar: sidebar 
permalink: oracle/oracle-asar2-host-config-aix.html 
keywords: oracle, database, ASA r2, ontap, aix, cio 
summary: Bases de données Oracle avec AIX sur ASA r2 
searchtitle: Bases de données Oracle avec IBM AIX sur ASA r2 
---
= AIX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sujets de configuration pour la base de données Oracle sur IBM AIX avec ASA r2 ONTAP.

[NOTE]
====
AIX est pris en charge avec NetApp ASA r2 pour l'hébergement de bases de données Oracle, à condition que :

* Vous configurez correctement Oracle pour les E/S simultanées.
* Vous utilisez les protocoles SAN pris en charge (FC/iSCSI/NVMe).
* Vous exécutez ONTAP 9.16.x ou une version ultérieure sur ASA r2.


====


== E/S simultanées

Pour obtenir des performances optimales sur IBM AIX avec ASA r2, il est nécessaire d'utiliser des E/S simultanées. Sans E/S simultanées, les limitations de performances sont probables car AIX effectue des E/S sérialisées et atomiques, ce qui engendre une surcharge importante.

À l'origine, NetApp recommandait d'utiliser `cio` L'option de montage permettait de forcer les E/S simultanées sur le système de fichiers, mais ce processus présentait des inconvénients et n'est plus nécessaire. Depuis l'introduction d'AIX 5.2 et d'Oracle 10gR1, Oracle sur AIX peut ouvrir des fichiers individuels pour des E/S simultanées, au lieu de forcer des E/S simultanées sur l'ensemble du système de fichiers.

La meilleure méthode pour activer les E/S simultanées est de définir le `init.ora` paramètre `filesystemio_options` à `setall`. Oracle peut ainsi ouvrir des fichiers spécifiques pour une utilisation avec des E/S simultanées

L'utilisation de cio comme option de montage force l'utilisation d'E/S simultanées, ce qui peut avoir des conséquences négatives. Par exemple, forcer les E/S simultanées désactive la lecture anticipée sur les systèmes de fichiers, ce qui peut nuire aux performances des E/S effectuées en dehors du logiciel de base de données Oracle, telles que la copie de fichiers et l'exécution de sauvegardes sur bande. De plus, des produits tels qu'Oracle GoldenGate et SAP BR*Tools ne sont pas compatibles avec l'utilisation de l'option de montage cio avec certaines versions d'Oracle.

[TIP]
====
*NetApp recommande* ce qui suit :

* N'utilisez pas le `cio` option de montage au niveau du système de fichiers. Activez plutôt les E/S simultanées via l'utilisation de `filesystemio_options=setall`.
* Utilisez uniquement le `cio` option de montage s'il n'est pas possible de définir `filesystemio_options=setall`.


====

NOTE: Étant donné que ASA r2 ne prend pas en charge le NAS, tous les déploiements Oracle sur AIX doivent utiliser des protocoles de blocs.



== Options de montage AIX jfs/jfs2

Le tableau suivant répertorie les options de montage AIX jfs/jfs2.

|===
| Type de fichier | Options de montage 


| Accueil ADR | Valeurs par défaut 


| fichiers de contrôle | Valeurs par défaut 


| Fichiers de données | Valeurs par défaut 


| Journaux de rétablissement | Valeurs par défaut 


| ORACLE_HOME | Valeurs par défaut 
|===
Avant d'utiliser AIX `hdisk` Dans tous les environnements, y compris les bases de données, vérifiez les paramètres des appareils. `queue_depth`. Ce paramètre ne correspond pas à la profondeur de la file d'attente HBA ; il se rapporte plutôt à la profondeur de la file d'attente SCSI de l'appareil individuel. `hdisk device`. Selon la configuration des LUN ASA r2, la valeur de `queue_depth` Cette valeur pourrait être trop faible pour de bonnes performances. Les tests ont montré que la valeur optimale était de 64.
