---
sidebar: sidebar 
permalink: oracle/oracle-storage-san-config-lun-alignment.html 
keywords: SAN, ASM, LVM 
summary: Alignement des LUN avec les bases de données Oracle 
searchtitle: Alignement des LUN pour les E/S de la base de données Oracle 
---
= Alignement de LUN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
L'alignement des LUN fait référence à l'optimisation des E/S par rapport à la disposition du système de fichiers sous-jacent.

Directive non résolue dans <stdin> - include::lun-alignment.adoc[]

Voir également la discussion sur l'alignement des blocs de compression dans la section link:oracle-ontap-config-efficiency.html["Efficacité"]. Toute disposition alignée avec les limites des blocs de compression de 8 Ko est également alignée avec les limites de 4 Ko.



== Avertissements de mauvais alignement

Directive non résolue dans <stdin> - include::database-alignment-warnings.adoc[]

L'alignement dans les environnements Solaris est plus compliqué. Reportez-vous à la section http://support.netapp.com/documentation/productlibrary/index.html?productID=61343["Configuration de l'hôte SAN ONTAP"^] pour en savoir plus.

|===
| Avertissement 


| Dans les environnements Solaris x86, prenez davantage soin de l'alignement approprié car la plupart des configurations comportent plusieurs couches de partitions. Les tranches de partition Solaris x86 existent généralement au-dessus d'une table de partition d'enregistrement d'amorçage maître standard. 
|===