---
sidebar: sidebar 
permalink: oracle/oracle-dr-smbc-rac.html 
keywords: oracle, smbc, sm-bc, RAC 
summary: Oracle RAC sur ONTAP avec SM-BC 
---
= Oracle RAC avec SM-BC
:allow-uri-read: 


[role="lead"]
SM-BC offre un contrôle granulaire de la réplication des datasets à des fins telles que l'équilibrage de la charge ou le basculement d'applications individuelles. L'architecture globale ressemble à un cluster RAC étendu, mais certaines bases de données sont dédiées à des sites spécifiques et la charge globale est distribuée.

Par exemple, vous pouvez créer un cluster Oracle RAC hébergeant six bases de données individuelles. Le stockage de trois des bases de données serait principalement hébergé sur le site A et le stockage des trois autres bases de données serait hébergé sur le site B. Cette configuration garantit les meilleures performances possibles en minimisant le trafic intersite. En outre, les applications seraient configurées pour utiliser les instances de base de données locales au système de stockage avec les chemins actifs. Cela réduit le trafic d'interconnexion RAC. Enfin, cette conception globale garantit l'utilisation uniforme de toutes les ressources de calcul. À mesure que les workloads changent, les bases de données peuvent faire l'objet d'un échec sélectif entre les sites pour assurer un chargement homogène.

Outre la granularité, les principes et options de base d'Oracle RAC utilisant SM-BC sont les mêmes que link:../metrocluster/mcc-rac.html["Oracle RAC sur MetroCluster"]
