---
sidebar: sidebar 
permalink: oracle/oracle-migration-overview.html 
keywords: oracle, ontap, migrations, TR-4534 
summary: Introduction à la migration du stockage Oracle 
---
= Migration des bases de données Oracle vers les systèmes de stockage NetApp
:allow-uri-read: 


[role="lead"]
L'exploitation des capacités d'une nouvelle plateforme de stockage implique une seule nécessité : les données doivent être placées sur le nouveau système de stockage.


NOTE: Cette documentation remplace le rapport technique _TR-4534 : migration des bases de données Oracle vers des systèmes de stockage NetApp_

Dans le cas d'un nouveau projet de base de données, cela ne pose pas de problème car les environnements de base de données et d'application sont construits en place. Cependant, la migration pose des défis particuliers en ce qui concerne les interruptions d'activité, le temps nécessaire à la réalisation de la migration, les compétences requises et la réduction des risques.



== Scripts

Des exemples de scripts sont fournis dans cette documentation. Ces scripts fournissent des exemples de méthodes d'automatisation de divers aspects de la migration afin de réduire le risque d'erreurs des utilisateurs. Les scripts réduisent les demandes globales de l'équipe INFORMATIQUE responsable de la migration et accélèrent le processus global. Ces scripts sont issus de projets de migration réalisés par les services professionnels de NetApp et les partenaires NetApp. Des exemples de leur utilisation sont présentés dans cette documentation.
