---
sidebar: sidebar 
permalink: oracle/oracle-dr-smbc-rac.html 
keywords: oracle, smbc, sm-bc, RAC 
summary: Oracle RAC avec synchronisation active SnapMirror 
---
= Oracle RAC avec synchronisation active SnapMirror
:allow-uri-read: 


[role="lead"]
La synchronisation active SnapMirror assure un contrôle granulaire de la réplication des jeux de données à des fins telles que l'équilibrage de la charge ou le basculement d'applications individuelles. L'architecture globale ressemble à un cluster RAC étendu, mais certaines bases de données sont dédiées à des sites spécifiques et la charge globale est distribuée.

Par exemple, vous pouvez créer un cluster Oracle RAC hébergeant six bases de données individuelles. Le stockage de trois des bases de données serait principalement hébergé sur le site A et le stockage des trois autres bases de données serait hébergé sur le site B. Cette configuration garantit les meilleures performances possibles en minimisant le trafic intersite. En outre, les applications seraient configurées pour utiliser les instances de base de données locales au système de stockage avec les chemins actifs. Cela réduit le trafic d'interconnexion RAC. Enfin, cette conception globale garantit l'utilisation uniforme de toutes les ressources de calcul. À mesure que les workloads changent, les bases de données peuvent faire l'objet d'un échec sélectif entre les sites pour assurer un chargement homogène.

En dehors de la granularité, les principes et options de base d'Oracle RAC utilisant la synchronisation active SnapMirror s'appliquent de la même façon link:../metrocluster/mcc-rac.html["Oracle RAC sur MetroCluster"]
