---
sidebar: sidebar 
permalink: mssql/mssql-overview.html 
keywords: MS-SQL,mssql,SQL Server,TR-4590 
summary: Microsoft SQL Server sur ONTAP 
---
= Présentation de Microsoft SQL Server
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
SQL Server constitue le socle de la plateforme de données Microsoft. Il apporte les performances stratégiques grâce aux technologies in-memory et permet d'obtenir plus rapidement des informations sur toutes les données, qu'elles soient sur site ou dans le cloud.


NOTE: Cette documentation remplace le rapport technique _TR-4590 : guide des meilleures pratiques pour Microsoft SQL Server avec ONTAP_

Microsoft SQL Server s'appuie sur les fonctionnalités stratégiques des versions précédentes pour offrir des performances, une disponibilité et une gestion exceptionnelles pour les applications stratégiques. Le système de stockage joue un rôle clé dans les performances globales d'une base de données SQL Server. NetApp propose plusieurs produits qui permettent à votre base de données SQL Server de fournir des performances d'entreprise tout en fournissant des outils de pointe pour la gestion de votre environnement.



== But et portée

Cette section décrit les meilleures pratiques et présente des conseils de conception pour déployer SQL Server sur des systèmes de stockage NetApp exécutant le logiciel NetApp ONTAP. Vous pouvez ainsi déployer le stockage de manière efficace et efficace, ainsi que planifier la protection et la conservation des données de bout en bout. Le périmètre de ce guide se limite aux instructions de conception technique basées sur les principes de conception et les normes privilégiées que NetApp recommande pour l'infrastructure de stockage lors du déploiement de SQL Server. La mise en œuvre de bout en bout ne fait pas partie du champ d'application du présent rapport.

Les meilleures pratiques et recommandations décrites dans ce guide permettent aux architectes SQL Server et aux administrateurs de stockage NetApp de planifier un environnement SQL Server hautement disponible et facile à gérer et de répondre à des SLA rigoureux. NetApp suppose que le lecteur a une connaissance pratique des éléments suivants :

* Logiciel NetApp ONTAP
* NetApp SnapCenter en tant que logiciel de sauvegarde, qui inclut :
+
** Plug-in SnapCenter pour Microsoft Windows
** Plug-in SnapCenter pour SQL Server


* Architecture et administration de Microsoft SQL Server


Pour connaître la compatibilité de la configuration sur l'ensemble de la pile NetApp, reportez-vous au link:http://mysupport.netapp.com/NOW/products/interoperability/["Matrice d'interopérabilité NetApp (IMT)"^].
