---
sidebar: sidebar 
permalink: mssql/mssql-shared-vs-dedicated.html 
keywords: MSSQL,SQL Server, multiple instances, dedicated instance, ONTAP 
summary: 'Déploiement d"instances Microsoft SQL Server' 
---
= Instance partagée Microsoft SQL Server par rapport à une instance dédiée
:allow-uri-read: 
:imagesdir: ../media/


[role="lead"]
Plusieurs serveurs SQL peuvent être configurés en tant qu'instance unique par serveur ou en tant que plusieurs instances. La bonne décision dépend généralement de facteurs tels que l'utilisation du serveur pour la production ou le développement, que l'instance soit considérée comme stratégique pour le fonctionnement de l'entreprise et les objectifs de performances.

La configuration initiale des configurations d'instances partagées peut être plus facile à configurer, mais elle peut entraîner des problèmes de division ou de verrouillage des ressources, ce qui entraîne des problèmes de performances pour d'autres applications sur lesquelles des bases de données sont hébergées sur l'instance SQL Server partagée.

La résolution des problèmes de performances peut s'avérer complexe, car vous devez déterminer quelle instance est la cause première. Cette question est comparée aux coûts des licences de systèmes d'exploitation et des licences SQL Server. Si les performances des applications sont primordiales, une instance dédiée est fortement recommandée.

Microsoft octroie des licences SQL Server par cœur au niveau du serveur et non par instance. C'est pourquoi les administrateurs de base de données sont tentés d'installer autant d'instances SQL Server que le serveur peut gérer pour réduire les coûts de licence, ce qui peut entraîner des problèmes de performances majeurs par la suite.


TIP: *NetApp recommande* de choisir des instances SQL Server dédiées chaque fois que possible pour obtenir des performances optimales.
