---
sidebar: sidebar 
permalink: mssql/mssql-data-protection.html 
keywords: MSSQL,SQL Server, SnapCenter, data protection, app-consistent backup, ONTAP 
summary: Protection des bases de données Microsoft SQL Server sur ONTAP avec les commandes SnapCenter et T-SQL. 
searchtitle: Protection des bases de données Microsoft SQL Server sur ONTAP avec les commandes SnapCenter et T-SQL 
---
= Protection des données
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les stratégies de sauvegarde des bases de données doivent être basées sur des exigences métier identifiées, et non sur des capacités théoriques. En combinant la technologie Snapshot de ONTAP et en exploitant les API de Microsoft SQL Server, vous pouvez effectuer rapidement des sauvegardes cohérentes au niveau des applications, quelle que soit la taille des bases de données utilisateur. Pour une gestion des données plus avancée ou scale-out, NetApp propose SnapCenter.



== SnapCenter

SnapCenter est le logiciel NetApp de protection des données pour les applications d'entreprise. Les bases de données SQL Server peuvent être protégées rapidement et facilement grâce au plug-in SnapCenter pour SQL Server et aux opérations du système d'exploitation gérées par le plug-in SnapCenter pour Microsoft Windows.

L'instance SQL Server peut être une instance de cluster d'installation autonome ou de basculement, ou elle peut être toujours sur le groupe de disponibilité. Le résultat est que depuis une fenêtre unique, les bases de données peuvent être protégées, clonées et restaurées à partir d'une copie principale ou secondaire. SnapCenter peut gérer les bases de données SQL Server à la fois sur site, dans le cloud et dans des configurations hybrides.des copies de bases de données peuvent également être créées en quelques minutes sur l'hôte original ou alternatif à des fins de développement ou de reporting.


TIP: *NetApp recommande* d'utiliser SnapCenter pour créer des copies Snapshot. La méthode T-SQL décrite ci-dessous fonctionne également, mais SnapCenter offre une automatisation complète du processus de sauvegarde, de restauration et de clonage. Il effectue également une découverte pour s'assurer que les snapshots corrects sont créés. Aucune préconfiguration n'est requise.

SQL Server nécessite également une coordination entre le système d'exploitation et le stockage pour s'assurer que les données correctes sont présentes dans les snapshots au moment de la création. Dans la plupart des cas, la seule méthode sûre pour ce faire est SnapCenter ou T-SQL. Les snapshots créés sans cette coordination supplémentaire peuvent ne pas être récupérables de manière fiable.

Pour plus d'informations sur le plug-in SQL Server pour SnapCenter, reportez-vous à la section link:https://www.netapp.com/pdf.html?item=/media/12400-tr4714.pdf["Tr-4714 : guide des meilleures pratiques pour SQL Server avec NetApp SnapCenter"^].



== Protection de la base de données à l'aide de snapshots T-SQL

Dans SQL Server 2022, Microsoft a introduit des snapshots T-SQL qui permettent de réaliser des scripts et d'automatiser les opérations de sauvegarde. Au lieu d'effectuer des copies complètes, vous pouvez préparer la base de données pour les snapshots. Une fois la base de données prête pour la sauvegarde, vous pouvez utiliser les API REST de ONTAP pour créer des snapshots.

Voici un exemple de flux de travail de sauvegarde :

. Figez une base de données à l'aide de la commande ALTER. La base de données est ainsi préparée pour un snapshot cohérent sur le stockage sous-jacent. Après le gel, vous pouvez dégeler la base de données et enregistrer le snapshot avec la commande BACKUP.
. Réalisez des instantanés de plusieurs bases de données sur les volumes de stockage simultanément avec les nouvelles commandes de GROUPE DE SAUVEGARDE et de SERVEUR DE SAUVEGARDE.
. Effectuer des sauvegardes COMPLÈTES ou des sauvegardes COMPLÈTES COPY_ONLY. Ces sauvegardes sont également enregistrées dans msdb.
. Effectuez une restauration instantanée à l'aide de sauvegardes de journaux effectuées avec l'approche de streaming standard après la sauvegarde COMPLÈTE des snapshots. Les sauvegardes différentielles en continu sont également prises en charge si nécessaire.


Pour en savoir plus, voir link:https://learn.microsoft.com/en-us/sql/relational-databases/databases/create-a-database-snapshot-transact-sql?view=sql-server-ver16["Documentation Microsoft à connaître sur les snapshots T-SQL"^].
