---
sidebar: sidebar 
permalink: mssql/shared-vs-dedicated.html 
keywords: MS-SQL,mssql,SQL Server 
summary: Microsoft SQL Server sur ONTAP 
---
= Instance partagée Microsoft SQL Server par rapport à une instance dédiée
:allow-uri-read: 


[role="lead"]
Si une application possède de nombreux schémas et procédures stockées, elle peut affecter d'autres applications qui partagent une instance SQL Server.

Les ressources d'instance peuvent potentiellement être divisées ou verrouillées, ce qui entraîne des problèmes de performances pour d'autres applications pour lesquelles des bases de données sont hébergées sur l'instance SQL Server partagée.

La résolution des problèmes de performances peut s'avérer complexe, car vous devez déterminer quelle instance est la cause première. Cette question est comparée aux coûts des licences de systèmes d'exploitation et des licences SQL Server. Si les performances des applications sont primordiales, une instance dédiée est fortement recommandée.

Microsoft octroie des licences SQL Server par cœur au niveau du serveur et non par instance. C'est pourquoi les administrateurs de base de données sont tentés d'installer autant d'instances SQL Server que le serveur peut gérer pour réduire les coûts de licence, ce qui peut entraîner des problèmes de performances majeurs par la suite.


TIP: *NetApp recommande* de choisir des instances SQL Server dédiées chaque fois que possible pour obtenir des performances optimales.
