---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-overview.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: 'ONTAP est une solution de stockage leader pour les environnements VMware vSphere depuis près de vingt ans et continue d"ajouter des fonctionnalités innovantes pour simplifier la gestion tout en réduisant les coûts. Ce document présente la solution ONTAP pour vSphere, comprenant les dernières informations sur les produits et les meilleures pratiques, afin de rationaliser le déploiement, de réduire les risques et de simplifier la gestion.' 
---
= VMware vSphere avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP a servi de solution de stockage de premier plan pour VMware vSphere et, plus récemment, pour les environnements Cloud Foundation depuis son introduction dans le data Center moderne en 2002. Elle continue d'introduire des fonctionnalités innovantes qui simplifient la gestion et réduisent les coûts.

Ce document présente la solution ONTAP pour vSphere et met en avant les dernières informations sur les produits et les meilleures pratiques pour rationaliser le déploiement, limiter les risques et simplifier la gestion.


NOTE: Cette documentation remplace les rapports techniques _TR-4597 : VMware vSphere pour ONTAP_

Les meilleures pratiques complètent d'autres documents, tels que des guides et des listes de compatibilité. Ils sont développés en fonction de tests effectués en laboratoire et d'une vaste expérience sur le terrain par les ingénieurs et les clients NetApp. Non seulement elles sont les seules pratiques prises en charge dans chaque environnement, mais elles constituent généralement les solutions les plus simples qui répondent aux besoins de la plupart des clients.

Ce document est axé sur les fonctionnalités des dernières versions d'ONTAP (9.x) exécutées sur vSphere 7.0 ou version ultérieure. Consultez https://imt.netapp.com/matrix/#search["Matrice d'interopérabilité (IMT)"^] et https://www.vmware.com/resources/compatibility/search.php?deviceCategory=san["Guide de compatibilité VMware"^] pour plus d'informations sur des versions spécifiques.
