---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-cloud_migration_backup.html 
keywords: Data protection, Space reclamation, VM and datastore cloning, Storage efficiency, thin provisioning, QoS, SIOC, Storage Distributed Resource Scheduler, DRS, Active IQ Unified Manager, Encryption 
summary: ONTAP prend en charge le cloud hybride. 
---
= Migration et sauvegarde dans le cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP permet également la prise en charge étendue du cloud hybride en fusionnant les systèmes de votre cloud privé sur site avec des capacités de cloud public. Voici quelques solutions clouds NetApp qui peuvent être utilisées en association avec vSphere :

* *Offres de première main.* Amazon FSx for NetApp ONTAP, Google Cloud NetApp Volumes et Azure NetApp Files fournissent des services de stockage gérés multiprotocoles hautes performances dans les principaux environnements de cloud public. Ils peuvent être utilisés directement par VMware Cloud sur AWS (VMC sur AWS), Azure VMware Solution (AVS) et Google Cloud VMware Engine (GCVE) comme banques de données ou stockage pour les systèmes d'exploitation invités (GOS) et les instances de calcul.
* *Cloud Volumes ONTAP.* le logiciel de gestion des données NetApp Cloud Volumes ONTAP permet de contrôler et de protéger les données et d'optimiser l'efficacité du stockage, tout en bénéficiant de la flexibilité du cloud de votre choix. Cloud Volumes ONTAP est un logiciel de gestion des données cloud basé sur le stockage ONTAP. Utilisez-les conjointement avec Cloud Manager pour déployer et gérer des instances Cloud Volumes ONTAP avec vos systèmes ONTAP sur site. Profitez des fonctionnalités NAS avancées et SAN iSCSI combinées à la gestion unifiée des données, notamment les copies Snapshot et la réplication SnapMirror.
* *Services cloud.* Utilisez NetApp Backup and Recovery ou SnapMirror Cloud pour protéger les données des systèmes sur site à l’aide du stockage cloud public. Cloud Sync permet de migrer et de synchroniser vos données entre les NAS, les magasins d'objets et le stockage Cloud Volumes Service . NetApp Disaster Recovery offre une solution rentable et efficace pour exploiter les technologies NetApp comme base d'une solution de reprise après sinistre robuste et performante pour la reprise après sinistre dans le cloud, la reprise après sinistre sur site et la reprise sur site vers la reprise après sinistre.
* *FabricPool.* FabricPool offre un Tiering simple et rapide pour les données ONTAP. Les blocs inactifs peuvent être migrés vers un magasin d'objets dans des clouds publics ou un magasin d'objets StorageGRID privé. Ils sont automatiquement rappelés lorsque vous accédez de nouveau aux données ONTAP. Vous pouvez également utiliser le Tier objet comme troisième niveau de protection pour les données déjà gérées par SnapVault. Cette approche peut vous permettre de https://www.linkedin.com/pulse/rethink-vmware-backup-again-keith-aasen/["Stockez davantage de snapshots de vos machines virtuelles"^] Sur les systèmes de stockage ONTAP primaires et/ou secondaires.
* *ONTAP Select.* utilisez le stockage Software-defined NetApp pour étendre votre cloud privé sur Internet aux sites et bureaux distants, où vous pouvez utiliser ONTAP Select pour prendre en charge les services de blocs et de fichiers ainsi que les mêmes fonctionnalités de gestion de données vSphere que votre data Center d'entreprise.


Lors de la conception de vos applications basées sur des machines virtuelles, tenez compte de la mobilité future dans le cloud. Par exemple, plutôt que de placer les fichiers d’application et de données ensemble, utilisez une exportation LUN ou NFS distincte pour les données. Cela vous permet de migrer la machine virtuelle et les données séparément vers des services cloud.

Pour en savoir plus sur la sécurité, consultez ces ressources.

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/index.html["Documentation Cloud Volumes ONTAP"]
* link:https://docs.netapp.com/us-en/ontap-select/["Documentation ONTAP Select"]
* link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["Documentation de sauvegarde et de récupération"]
* link:https://docs.netapp.com/us-en/data-services-disaster-recovery/index.html["Documentation sur la reprise après sinistre"]
* link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSX pour NetApp ONTAP"]
* link:https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud sur AWS"]
* link:https://learn.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-introduction["Qu'est-ce que Azure NetApp Files ?
"]
* link:https://azure.microsoft.com/en-us/products/azure-vmware/["Solution Azure VMware"]
* link:https://cloud.google.com/vmware-engine["Moteur VMware Google Cloud"]
* link:https://cloud.google.com/netapp/volumes/docs/discover/overview["Qu'est-ce que Google Cloud NetApp volumes ?"]

