---
sidebar: sidebar 
permalink: vmware/vmware-srm-deployment_best_practices.html 
keywords: vmware, site, recovery manager, vsrm, svm, layout, segmentation, smt, best, practices, deploy, ontap, tools, vvols, srm, vlsr 
summary: 'Avec ONTAP, le concept de machine virtuelle de stockage (SVM) offre une segmentation stricte dans les environnements mutualisés sécurisés.' 
---
= Bonnes pratiques de déploiement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les sections suivantes présentent les meilleures pratiques de déploiement avec ONTAP et VMware SRM.



== Utiliser la dernière version des outils ONTAP 10

Les outils ONTAP 10 offrent des améliorations significatives par rapport aux versions précédentes, notamment :

* basculement de test 8 fois plus rapide*
* nettoyage et reprotection 2 fois plus rapides*
* basculement 32 % plus rapide*
* Évolutivité accrue
* Prise en charge native des mises en page de sites partagés


*Ces améliorations sont basées sur des tests internes et peuvent varier en fonction de votre environnement.



== Disposition des SVM et segmentation pour la colocation sécurisée

Avec ONTAP, le concept de machine virtuelle de stockage (SVM) offre une segmentation stricte dans les environnements mutualisés sécurisés. Les utilisateurs des SVM situés sur un SVM ne peuvent ni accéder aux ressources d'un autre ni les gérer. De cette façon, vous pouvez exploiter la technologie ONTAP en créant des SVM distincts pour différentes unités commerciales qui gèrent leurs propres flux de travail SRM sur le même cluster, pour une efficacité globale supérieure du stockage.

Envisagez de gérer ONTAP avec des comptes SVM-scoped et des LIF de management SVM pour non seulement améliorer les contrôles de sécurité, mais aussi améliorer les performances. Les performances sont supérieures par nature lorsque des connexions SVM-scoped sont utilisées, car SRA n'est pas nécessaire pour traiter toutes les ressources d'un cluster entier, y compris les ressources physiques. Il ne doit plutôt comprendre que les ressources logiques qui sont extraites vers la SVM particulière.



== Meilleures pratiques pour la gestion des systèmes ONTAP 9

Comme mentionné précédemment, il est possible de gérer des clusters ONTAP avec des identifiants cluster ou SVM évalués et des LIF de gestion. Pour des performances optimales, il peut être intéressant d'utiliser des identifiants SVM- scoped lorsque vous n'utilisez pas les vVols. Cependant, ce faisant, vous devriez être conscient de certaines exigences, et que vous perdez certaines fonctionnalités.

* Le compte SVM vsadmin par défaut ne dispose pas du niveau d'accès requis pour effectuer les tâches des outils ONTAP Il faut donc créer un compte SVM. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-user-role-and-privileges.html["Configurer les rôles et privilèges des utilisateurs ONTAP"] Utilisation du fichier JSON inclus. Il peut être utilisé pour les comptes évalués au niveau du SVM ou du cluster.
* Comme le plug-in de l'interface utilisateur vCenter, le fournisseur VASA et le serveur SRA sont tous des microservices entièrement intégrés, vous devez ajouter du stockage à l'adaptateur SRA dans SRM de la même manière que vous ajoutez du stockage dans l'interface utilisateur vCenter pour les outils ONTAP. Sinon, le serveur SRA pourrait ne pas reconnaître les requêtes envoyées depuis SRM via l'adaptateur SRA.
* La vérification du chemin NFS n'est pas effectuée en cas d'utilisation d'identifiants SVM-scoped, sauf si vous êtes le premier dans ONTAP Tools Manager et si vous https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["clusters intégrés"] les associez à vCenters. Car l'emplacement physique est logiquement extrait du SVM. Cela ne pose pas de problème, car les systèmes ONTAP modernes ne subissent plus de déclin perceptible des performances lors de l'utilisation de chemins indirects.
* Il est possible que les économies d'espace réalisées grâce à l'efficacité du stockage ne soient pas signalées.
* Lorsqu'ils sont pris en charge, les miroirs de partage de charge ne peuvent pas être mis à jour.
* Il est possible que la connexion EMS ne soit pas effectuée sur des systèmes ONTAP gérés avec des identifiants évalués par SVM.

