---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-fg.html 
keywords: vSphere, datastore, NFS, nconnect, FlexGroup, session trunking 
summary: 'Cette page décrit les bonnes pratiques d"implémentation des volumes ONTAP FlexGroup dans un environnement VMware vSphere.' 
---
= Volumes FlexGroup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez des volumes ONTAP et FlexGroup avec VMware vSphere pour disposer de datastores simples et évolutifs exploitant toute la puissance d'un cluster ONTAP.

ONTAP 9.8, ainsi que les outils ONTAP pour VMware vSphere 9.8-9.13 et le plug-in SnapCenter pour VMware 4.4 et les versions ultérieures, ont ajouté la prise en charge des datastores FlexGroup avec volumes dans vSphere. Les volumes FlexGroup simplifient la création de grands datastores et créent automatiquement les volumes distribués nécessaires sur le cluster ONTAP afin d'optimiser les performances d'un système ONTAP.

Utilisez les volumes FlexGroup avec vSphere si vous avez besoin d'un datastore vSphere unique et évolutif doté de la puissance d'un cluster ONTAP complet, ou si vous disposez de charges de travail de clonage très volumineuses qui peuvent tirer parti du mécanisme de clonage FlexGroup en conservant constamment le cache de clone au chaud.



== Copie auxiliaire

Outre les tests approfondis du système avec les charges de travail vSphere, ONTAP 9.8 a ajouté un nouveau mécanisme de déchargement des copies pour les datastores FlexGroup. Ce nouveau système utilise un moteur de copie amélioré pour répliquer les fichiers entre les composants en arrière-plan tout en permettant l'accès à la source et à la destination. Ce cache local constitutif est ensuite utilisé pour instancier rapidement les clones de machine virtuelle à la demande.

Pour activer le déchargement de copie optimisé pour FlexGroup, reportez-vous à la section https://kb.netapp.com/onprem/ontap/dm/VAAI/How_to_Configure_ONTAP_FlexGroups_to_allow_VAAI_copy_offload["Comment configurer les volumes ONTAP FlexGroup pour permettre la copie auxiliaire VAAI"]

Si vous utilisez le clonage VAAI, mais que le clonage n'est pas suffisant pour maintenir le cache chaud, vos clones ne seront peut-être pas plus rapides qu'une copie basée sur hôte. Si c'est le cas, vous pouvez régler le délai d'expiration du cache pour mieux répondre à vos besoins.

Prenons le scénario suivant :

* Vous avez créé un nouveau FlexGroup avec 8 composants
* Le délai d'expiration du cache pour le nouveau FlexGroup est défini sur 160 minutes


Dans ce scénario, les 8 premiers clones à terminer seront des copies complètes, et non des clones de fichiers locaux. Tout clonage supplémentaire de cette machine virtuelle avant l'expiration du délai de 160 secondes utilisera le moteur de clonage de fichiers à l'intérieur de chaque composant de manière circulaire pour créer des copies quasi immédiates réparties uniformément sur les volumes constitutifs.

Chaque nouvelle tâche de clonage reçue par un volume réinitialise le délai d'expiration. Si un volume composant de l'exemple FlexGroup ne reçoit pas de requête de clone avant le délai d'expiration, le cache de cette machine virtuelle sera effacé et le volume devra être à nouveau rempli. De même, si la source du clone d'origine change (par exemple, si vous avez mis à jour le modèle), le cache local de chaque composant sera invalidé pour éviter tout conflit. Comme indiqué précédemment, le cache peut être réglé en fonction des besoins de votre environnement.

Pour plus d'informations sur l'utilisation des volumes FlexGroup avec VAAI, consultez l'article de la base de connaissances suivant : https://kb.netapp.com/?title=onprem%2Fontap%2Fdm%2FVAAI%2FVAAI%3A_How_does_caching_work_with_FlexGroups%253F["VAAI : comment la mise en cache fonctionne-t-elle avec les volumes FlexGroup ?"^]

Dans les environnements où vous ne pouvez pas tirer pleinement parti du cache FlexGroup, mais où vous avez toujours besoin d'un clonage rapide entre plusieurs volumes, envisagez d'utiliser les vVols. Le clonage entre volumes avec vVols est beaucoup plus rapide qu'avec les datastores traditionnels et ne repose pas sur un cache.



== Paramètres QoS

La configuration de la qualité de service au niveau FlexGroup à l'aide de ONTAP System Manager ou du shell du cluster est prise en charge, mais elle ne prend pas en charge la reconnaissance des machines virtuelles ni l'intégration de vCenter.

La qualité de service (IOPS max/min) peut être définie sur des VM individuelles ou sur toutes les VM d'un datastore à ce moment dans l'interface utilisateur vCenter ou via les API REST à l'aide des outils ONTAP. La définition de la qualité de service sur toutes les VM remplace tous les paramètres distincts par VM. Les paramètres ne s'étendent pas ultérieurement aux nouvelles machines virtuelles ou aux machines virtuelles migrées ; définissez la qualité de service sur les nouvelles machines virtuelles ou appliquez à nouveau la qualité de service à toutes les machines virtuelles du datastore.

Notez que VMware vSphere traite toutes les E/S d'un datastore NFS comme une seule file d'attente par hôte, et que la limitation de la qualité de service sur une machine virtuelle peut avoir un impact sur les performances des autres machines virtuelles du même datastore pour cet hôte. Cela contraste avec les vVols qui peuvent maintenir leurs paramètres de politique de QoS s'ils migrent vers un autre datastore et n'ont pas d'impact sur les E/S d'autres machines virtuelles lorsqu'ils sont restreints.



== Métriques

ONTAP 9.8 a également ajouté de nouveaux metrics de performance basés sur des fichiers (IOPS, débit et latence) pour FlexGroup Files. Ces metrics peuvent être consultées dans les outils ONTAP pour les rapports sur les machines virtuelles et le tableau de bord VMware vSphere. Les outils ONTAP pour le plug-in VMware vSphere vous permettent également de définir des règles de qualité de service (QoS) en combinant des IOPS minimales et/ou maximales. Ils peuvent être définis au sein de toutes les machines virtuelles d'un datastore ou individuellement pour des machines virtuelles spécifiques.



== Et des meilleures pratiques

* Utilisez les outils ONTAP pour créer des datastores FlexGroup afin de vous assurer que votre FlexGroup est créé de manière optimale et que les règles d'exportation sont configurées pour correspondre à votre environnement vSphere. Cependant, après avoir créé le volume FlexGroup avec les outils ONTAP, vous constaterez que tous les nœuds de votre cluster vSphere utilisent une seule adresse IP pour monter le datastore. Cela pourrait entraîner un goulot d'étranglement sur le port réseau. Pour éviter ce problème, démontez le datastore, puis remontez-le à l'aide de l'assistant standard vSphere datastore en utilisant un nom DNS round-Robin qui équilibre la charge entre les LIF du SVM. Après le remontage, les outils ONTAP pourront à nouveau gérer le datastore. Si les outils ONTAP ne sont pas disponibles, utilisez les paramètres par défaut de FlexGroup et créez votre règle d'export en suivant les instructions de la section link:vmware-vsphere-datastores-nfs.html["Datastores et protocoles - NFS"].
* Lors du dimensionnement d'un datastore FlexGroup, n'oubliez pas que le FlexGroup est constitué de plusieurs petits volumes FlexVol qui créent un espace de noms plus important. Par conséquent, dimensionnez le datastore pour qu'il soit au moins 8 fois (en supposant que les 8 composants par défaut) la taille de votre fichier VMDK le plus volumineux, plus une marge inutilisée de 10 à 20 % pour permettre un rééquilibrage flexible. Par exemple, si votre environnement comporte 6 To de VMDK, dimensionnez le datastore FlexGroup d'une capacité inférieure à 52,8 To (6 x 8 + 10 %).
* VMware et NetApp prennent en charge la mise en circuit de session NFSv4.1 à partir de ONTAP 9.14.1. Pour plus d'informations sur les versions, consultez les notes relatives à la matrice d'interopérabilité NetApp NFS 4.1 (IMT). NFSv3 ne prend pas en charge plusieurs chemins physiques vers un volume, mais prend en charge nconnect à partir de vSphere 8.0U2. Pour plus d'informations sur nconnect, consultez le link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vsphere8-nfs-nconnect.html["Fonctionnalité NFSv3 nConnect avec NetApp et VMware"].
* Utilisez le plug-in NFS pour VMware VAAI pour la copie auxiliaire. Notez que même si le clonage est amélioré dans un datastore FlexGroup, comme mentionné précédemment, ONTAP n'offre pas d'avantages significatifs en termes de performances par rapport à la copie hôte ESXi lors de la copie de machines virtuelles entre des volumes FlexVol et/ou FlexGroup. Prenez donc en compte vos charges de travail de clonage lorsque vous décidez d'utiliser des volumes VAAI ou FlexGroup. L'une des façons d'optimiser le clonage basé sur FlexGroup consiste à modifier le nombre de volumes constitutifs. Tout comme le réglage du délai d'expiration du cache mentionné précédemment.
* Utilisez les outils ONTAP pour VMware vSphere 9.8-9.13 pour surveiller les performances des machines virtuelles FlexGroup à l'aide de metrics ONTAP (tableaux de bord et rapports sur les machines virtuelles) et gérer la qualité de service sur chaque machine virtuelle. Ces metrics ne sont pas encore disponibles via les commandes ou les API ONTAP.
* Le plug-in SnapCenter pour VMware vSphere version 4.4 et ultérieure prend en charge la sauvegarde et la restauration des machines virtuelles dans un datastore FlexGroup sur le système de stockage principal. Le distributeur sélectif 4.6 ajoute la prise en charge de SnapMirror pour les datastores basés sur FlexGroup. L'utilisation de snapshots basés sur les baies et de la réplication est le moyen le plus efficace de protéger vos données.

