---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Les clients choisissent en toute confiance ONTAP pour vSphere en raison de ses solutions de stockage unifié SAN et NAS et de la nouvelle architecture de stockage désagrégée simplifiée, qui figure dans les dernières baies SAN. Cette plateforme offre une protection exceptionnelle des snapshots et des outils de gestion robustes. En transférant les fonctions vers un système de stockage dédié, ONTAP optimise les ressources hôtes, réduit les coûts et maintient des performances optimales. De plus, Storage vMotion peut facilement migrer les workloads sur VMFS, NFS ou vVols. 
---
= Pourquoi choisir ONTAP pour VMware vSphere ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les clients choisissent en toute confiance ONTAP pour vSphere pour les solutions de stockage SAN et NAS.  La nouvelle architecture de stockage désagrégée simplifiée, présente dans les dernières baies All SAN, offre une expérience simplifiée familière aux administrateurs de stockage SAN tout en conservant la plupart des intégrations et des fonctionnalités des systèmes ONTAP traditionnels.  Les systèmes ONTAP offrent une protection exceptionnelle des snapshots et des outils de gestion robustes.  En déchargeant les fonctions vers un stockage dédié, ONTAP maximise les ressources de l'hôte, réduit les coûts et maintient des performances optimales.  De plus, les charges de travail peuvent être facilement migrées à l’aide de Storage vMotion sur VMFS, NFS ou vVols.



== Avantages de l'utilisation de ONTAP pour vSphere

De nombreuses raisons ont poussé des dizaines de milliers de clients à choisir ONTAP comme solution de stockage pour vSphere, par exemple un système de stockage unifié prenant en charge les protocoles SAN et NAS, des fonctionnalités robustes de protection des données à l'aide de copies Snapshot compactes et une multitude d'outils pour vous aider à gérer les données applicatives. En utilisant un système de stockage distinct de l'hyperviseur, vous pouvez décharger de nombreuses fonctions et optimiser votre investissement dans les systèmes hôtes vSphere. En plus de s'assurer que les ressources de vos hôtes sont concentrées sur les charges de travail applicatives, vous évitez également l'impact aléatoire sur les performances des applications en provenance des opérations de stockage.

L’utilisation ONTAP avec vSphere est une excellente combinaison qui vous permet de réduire les dépenses liées au matériel hôte et aux logiciels VMware.  Vous pouvez également protéger vos données à moindre coût avec des performances élevées et constantes.  Étant donné que les charges de travail virtualisées sont mobiles, vous pouvez explorer différentes approches à l’aide de Storage vMotion pour déplacer des machines virtuelles entre des banques de données VMFS, NFS ou vVols , le tout sur le même système de stockage.

Voici les facteurs clés que les clients apprécient aujourd’hui :

* *Stockage unifié.*  Les systèmes exécutant ONTAP sont unifiés de plusieurs manières importantes.  À l’origine, cette approche faisait référence aux protocoles NAS et SAN, et ONTAP continue d’être une plate-forme de premier plan pour le SAN, avec sa force initiale dans le NAS.  Dans le monde vSphere, cette approche pourrait également signifier un système unifié pour l’infrastructure de bureau virtuel (VDI) ainsi que pour l’infrastructure de serveur virtuel (VSI).  Les systèmes exécutant ONTAP sont généralement moins chers pour VSI que les baies d'entreprise traditionnelles et disposent pourtant de capacités d'efficacité de stockage avancées pour gérer VDI dans le même système.  ONTAP unifie également une variété de supports de stockage, des SSD aux SATA, et peut facilement les étendre au cloud.  Il n’est pas nécessaire d’acheter un système d’exploitation de stockage pour les performances, un autre pour les archives et encore un autre pour le cloud.  ONTAP les relie tous ensemble.
* *Baie SAN (ASA).* Les derniers systèmes ONTAP ASA (à partir des modèles A1K, A90, A70, A50, A30 et A20) reposent sur une nouvelle architecture de stockage qui élimine le modèle de stockage ONTAP classique utilisé pour la gestion des agrégats et des volumes. Comme il n'existe aucun partage de système de fichiers, les volumes ne sont pas nécessaires. Tout le stockage rattaché à une paire HA est traité comme une zone de disponibilité du stockage commune (SAZ) dans laquelle les LUN et les espaces de noms NVMe sont provisionnés en tant que « unités de stockage » (MU). Les derniers systèmes ASA sont conçus pour être faciles à gérer et offrent une expérience familière aux administrateurs de stockage SAN. Cette nouvelle architecture est idéale pour les environnements vSphere, car elle facilite la gestion des ressources de stockage et simplifie l'expérience des administrateurs de stockage SAN. L'architecture ASA prend également en charge la dernière technologie NVMe over Fabrics (NVMe-of) qui améliore encore les performances et l'évolutivité des workloads vSphere.
* *Technologie Snapshot.* ONTAP a été le premier à proposer une technologie Snapshot pour la protection des données et reste la plus avancée du secteur. Cette approche peu gourmande en espace pour la protection des données a été étendue pour prendre en charge les API VMware vSphere pour l'intégration de baies (VAAI). Cette intégration vous permet de tirer parti des fonctionnalités Snapshot de ONTAP pour les opérations de sauvegarde et de restauration, réduisant ainsi l'impact sur votre environnement de production. Cette approche vous permet également d'utiliser des snapshots pour une restauration rapide des machines virtuelles, réduisant ainsi le temps et les efforts nécessaires à la restauration des données. De plus, la technologie Snapshot de ONTAP est intégrée aux solutions VLSR (Live site Recovery Manager) de VMware, offrant ainsi une stratégie complète de protection des données pour votre environnement virtualisé.
* *Gestion basée sur des politiques de volumes virtuels et de stockage.*  NetApp a été l'un des premiers partenaires de conception de VMware dans le développement de vSphere Virtual Volumes (vVols), fournissant des contributions architecturales et un support précoce pour vVols et VMware vSphere APIs for Storage Awareness (VASA).  Non seulement cette approche a apporté une gestion granulaire du stockage des machines virtuelles à VMFS, mais elle a également pris en charge l’automatisation du provisionnement du stockage via une gestion basée sur des politiques de stockage.  Cette approche permet aux architectes de stockage de concevoir des pools de stockage dotés de différentes capacités qui peuvent être facilement utilisées par les administrateurs de machines virtuelles.  ONTAP est le leader du secteur du stockage en termes d'échelle vVol, prenant en charge des centaines de milliers de vVols dans un seul cluster, tandis que les fournisseurs de baies d'entreprise et de baies flash plus petites prennent en charge quelques milliers de vVols par baie.  NetApp est également à l’origine de l’évolution de la gestion granulaire des machines virtuelles avec des fonctionnalités à venir.
* *Efficacité de stockage.*  Bien que NetApp ait été le premier à proposer la déduplication pour les charges de travail de production, cette innovation n'était ni la première ni la dernière dans ce domaine.  Tout a commencé avec des instantanés, un mécanisme de protection des données peu encombrant sans effet sur les performances, ainsi que la technologie FlexClone pour créer instantanément des copies en lecture/écriture de machines virtuelles à des fins de production et de sauvegarde.  NetApp a ensuite proposé des fonctionnalités en ligne, notamment la déduplication, la compression et la déduplication zéro bloc, pour tirer le meilleur parti du stockage des SSD coûteux.  ONTAP a également ajouté la possibilité de regrouper des opérations d'E/S et des fichiers plus petits dans un bloc de disque à l'aide de la compaction.  La combinaison de ces capacités a permis aux clients de réaliser des économies allant jusqu'à 5:1 pour VSI et jusqu'à 30:1 pour VDI.  La dernière génération de systèmes ONTAP inclut également la compression et la déduplication accélérées par le matériel, ce qui peut encore améliorer l'efficacité du stockage et réduire les coûts.  Cette approche vous permet de stocker plus de données dans moins d’espace, réduisant ainsi le coût global du stockage et améliorant les performances.  NetApp est tellement confiant dans ses capacités d'efficacité de stockage qu'il propose un lien : https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [Garantie d'efficacité^].
* *Multilocation.*  ONTAP est depuis longtemps un leader en matière de multilocation, vous permettant de créer plusieurs machines virtuelles de stockage (SVM) sur un seul cluster.  Cette approche vous permet d’isoler les charges de travail et de fournir différents niveaux de service à différents locataires, ce qui la rend idéale pour les fournisseurs de services et les grandes entreprises.  La dernière génération de systèmes ONTAP inclut également la prise en charge de la gestion de la capacité des locataires.  Cette fonctionnalité vous permet de définir des limites de capacité pour chaque locataire, garantissant qu'aucun locataire ne peut consommer toutes les ressources disponibles.  Cette approche permet de garantir que tous les locataires reçoivent le niveau de service qu’ils attendent, tout en offrant un niveau élevé de sécurité et d’isolement entre les locataires.  De plus, les capacités multi-tenant d'ONTAP sont intégrées à la plate-forme vSphere de VMware, vous permettant de gérer et de surveiller facilement votre environnement virtualisé via https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Les outils ONTAP pour VMware vSphere"] et https://docs.netapp.com/us-en/data-infrastructure-insights/["Informations exploitables sur l'infrastructure de données"] .
* *Cloud hybride.*  Qu'elles soient utilisées pour un cloud privé sur site, une infrastructure de cloud public ou un cloud hybride combinant le meilleur des deux, les solutions ONTAP vous aident à créer votre structure de données pour rationaliser et optimiser la gestion des données.  Commencez par des systèmes 100 % flash hautes performances, puis associez-les à des systèmes de stockage sur disque ou dans le cloud pour la protection des données et le calcul dans le cloud.  Choisissez parmi Azure, AWS, IBM ou Google Cloud pour optimiser vos coûts et éviter le blocage. Bénéficiez d'une prise en charge avancée d'OpenStack et des technologies de conteneurs selon vos besoins.  NetApp propose également des outils de sauvegarde basés sur le cloud (SnapMirror Cloud, Cloud Backup Service et Cloud Sync) et de hiérarchisation et d'archivage du stockage (FabricPool) pour ONTAP afin de réduire les dépenses d'exploitation et de tirer parti de la large portée du cloud.
* *Et plus.* tirez parti des performances extrêmes des baies NetApp AFF A-Series pour accélérer votre infrastructure virtualisée tout en gérant les coûts. Assurez la continuité totale de l'activité, qu'il s'agisse de la maintenance ou des mises à niveau, ou du remplacement complet de votre système de stockage à l'aide de clusters ONTAP scale-out. Protégez vos données au repos avec les fonctionnalités de chiffrement NetApp, sans frais supplémentaires. Assurez-vous que les performances respectent les niveaux de service grâce à des fonctionnalités de qualité de service très avancées. Elles font toutes partie du vaste éventail de fonctionnalités fournies par ONTAP, le logiciel de gestion des données d'entreprise leader du secteur.

