---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-vvols_and_spbm.html 
keywords: vSphere, vVols, virtual volumes, SPBM, storage police based management, ONTAP 
summary: 'Cette page décrit les bonnes pratiques d"implémentation d"une solution de stockage ONTAP dans un environnement VMware vSphere.' 
---
= Volumes virtuels (vvols) et gestion basée sur des règles de stockage (SPBM)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp a été un partenaire de conception précoce avec VMware dans le développement de vSphere Virtual volumes (vvols), en fournissant des informations architecturales et une prise en charge précoce pour vvols et VMware vSphere API for Storage Awareness (VASA). Non seulement cette approche intègre la gestion du stockage granulaire des machines virtuelles à VMFS, mais elle prend également en charge l'automatisation du provisionnement du stockage via la gestion basée sur des règles de stockage (SPBM).

Grâce à la gestion du stockage basée sur des règles, une structure sert de couche d'abstraction entre les services de stockage disponibles pour votre environnement de virtualisation et les éléments de stockage provisionnés via des règles. Cette approche permet aux architectes du stockage de concevoir des pools de stockage dont les capacités sont facilement utilisable par les administrateurs de machines virtuelles. Les administrateurs peuvent ensuite répondre aux exigences des charges de travail des machines virtuelles par rapport aux pools de stockage provisionnés, ce qui permet un contrôle granulaire des divers paramètres au niveau de chaque machine virtuelle ou disque virtuel.

ONTAP est leader du secteur du stockage dans l'évolutivité de vvols, en gérant des centaines de milliers de vvols dans un seul cluster, alors que les fournisseurs de baies d'entreprise et de baies Flash plus petites prennent en charge aussi peu que plusieurs milliers de vvols par baie. NetApp pilotant également l'évolution de la gestion granulaire des machines virtuelles avec des fonctionnalités à venir en matière de prise en charge de vvols 3.0.


NOTE: Pour plus d'informations sur les volumes virtuels VMware vSphere, SPBM et ONTAP, voir link:vmware-vvols-overview.html["Tr-4400 : volumes virtuels VMware vSphere avec ONTAP"^].
