---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'La solution ONTAP pour VMware VLSR (Live site Recovery) et SRM (site Recovery Manager)' 
---
= Restauration de site en direct VMware avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP est une solution de stockage de premier plan pour VMware vSphere et, plus récemment, Cloud Foundation, depuis l'introduction d'ESX dans les centres de données modernes il y a plus de deux décennies.  NetApp continue d'introduire des systèmes innovants, tels que la dernière génération de la série ASA A, ainsi que des fonctionnalités telles que la synchronisation active SnapMirror .  Ces avancées simplifient la gestion, améliorent la résilience et réduisent le coût total de possession (TCO) de votre infrastructure informatique.

Ce document présente la solution ONTAP pour VMware Live Site Recovery (VLSR), anciennement connu sous le nom de Site Recovery Manager (SRM), le logiciel de reprise après sinistre (DR) leader du secteur de VMware, y compris les dernières informations sur les produits et les meilleures pratiques pour rationaliser le déploiement, réduire les risques et simplifier la gestion continue.


NOTE: Cette documentation remplace le rapport technique précédemment publié _TR-4900 : VMware Site Recovery Manager avec ONTAP_

Les meilleures pratiques complètent d'autres documents, tels que des guides et des outils de compatibilité. Ils sont développés en fonction de tests effectués en laboratoire et d'une vaste expérience sur le terrain par les ingénieurs et les clients NetApp. Dans certains cas, les meilleures pratiques recommandées peuvent ne pas être adaptées à votre environnement. Cependant, ce sont généralement les solutions les plus simples qui répondent aux besoins des plus clients.

Ce document porte sur les fonctionnalités des dernières versions de ONTAP 9 utilisées conjointement avec les outils ONTAP pour VMware vSphere 10.4 (notamment NetApp Storage Replication adapter [SRA] et VASA Provider [VP]), ainsi que sur VMware Live site Recovery 9.



== Pourquoi utiliser ONTAP avec VLSR ou SRM ?

Les plates-formes de gestion de données NetApp optimisées par ONTAP font partie des solutions de stockage les plus largement adoptées pour VLSR.  Les raisons sont nombreuses : une plate-forme de gestion de données sécurisée, hautes performances et unifiée (NAS et SAN ensemble) qui offre une efficacité de stockage définissant le secteur, une multilocation, des contrôles de qualité de service, une protection des données avec des instantanés économes en espace et une réplication avec SnapMirror.  Le tout s'appuyant sur l'intégration multicloud hybride native pour la protection des charges de travail VMware et une pléthore d'outils d'automatisation et d'orchestration à portée de main.

Lorsque vous utilisez SnapMirror pour la réplication basée sur une baie, vous bénéficiez de l’une des technologies les plus éprouvées et les plus matures d’ONTAP.  SnapMirror vous offre l'avantage de transferts de données sécurisés et très efficaces, en copiant uniquement les blocs de système de fichiers modifiés, et non des machines virtuelles ou des banques de données entières.  Même ces blocs bénéficient d’économies d’espace, telles que la déduplication, la compression et le compactage.  Les systèmes ONTAP modernes utilisent désormais SnapMirror indépendant de la version, ce qui vous permet de sélectionner vos clusters source et de destination avec flexibilité.  SnapMirror est véritablement devenu l’un des outils les plus puissants disponibles pour la reprise après sinistre.

Que vous utilisiez des magasins de données traditionnels NFS, iSCSI ou Fibre Channel (désormais avec prise en charge des magasins de données vVols ), VLSR fournit une offre propriétaire robuste qui exploite le meilleur des fonctionnalités ONTAP pour la reprise après sinistre ou la planification et l'orchestration de la migration du centre de données.



== Comment VLSR exploite ONTAP 9

VLSR exploite les technologies avancées de gestion des données des systèmes ONTAP en l'intégrant aux outils ONTAP pour VMware vSphere, une appliance virtuelle qui englobe trois composants principaux :

* Le plug-in vCenter des outils ONTAP, précédemment appelé Virtual Storage Console (VSC), simplifie les fonctionnalités d'efficacité et de gestion du stockage, améliore la disponibilité et réduit les coûts de stockage et les coûts d'exploitation, que vous utilisiez SAN ou NAS. Il s'appuie sur les bonnes pratiques pour le provisionnement des datastores et optimise les paramètres d'hôte ESXi pour les environnements de stockage NFS et bloc. Pour tous ces avantages, NetApp recommande ce plug-in lors de l'utilisation de vSphere avec les systèmes exécutant ONTAP.
* Les outils ONTAP VASA Provider prennent en charge le framework VMware vStorage APIs for Storage Awareness (VASA). Vasa Provider connecte vCenter Server avec ONTAP pour faciliter le provisionnement et la surveillance du stockage des machines virtuelles. Cela a permis la prise en charge des volumes virtuels VMware (vVols) et la gestion des politiques de stockage des machines virtuelles et des performances des vVols des machines virtuelles individuelles. Il fournit également des alarmes pour la surveillance de la capacité et la conformité avec les profils.
* SRA est utilisée en association avec VLSR pour gérer la réplication des données des machines virtuelles entre les sites de production et de reprise après incident pour les datastores VMFS et NFS traditionnels, et pour les tests non disruptives des répliques de DR. Il permet d'automatiser les tâches de détection, de restauration et de reprotection. Il comprend à la fois un serveur SRA et des adaptateurs SRA pour le serveur Windows SRM et le dispositif VLSR.


Après avoir installé et configuré les adaptateurs SRA sur le serveur VLSR pour protéger les banques de données non vVols, vous pouvez commencer la tâche de configuration de votre environnement vSphere pour la reprise après sinistre.

SRA est une interface de commande et de contrôle pour le serveur VLSR afin de gérer les volumes ONTAP FlexVol qui contiennent vos machines virtuelles VMware, ainsi que la réplication SnapMirror qui les protège.

VLSR peut tester votre plan DR sans interruption à l'aide de la technologie propriétaire FlexClone de NetApp pour créer des clones quasi instantanés de vos banques de données protégées sur votre site DR.  VLSR crée un bac à sable pour effectuer des tests en toute sécurité afin que votre organisation et vos clients soient protégés en cas de véritable sinistre, vous donnant confiance dans la capacité de votre organisation à exécuter un basculement en cas de sinistre.

En cas d'incident véritable ou même de migration planifiée, VLSR vous permet d'envoyer les modifications de dernière minute au jeu de données via une mise à jour SnapMirror finale (si vous le souhaitez). Il interrompt ensuite le miroir et monte le datastore sur vos hôtes de reprise après incident. À ce stade, vos machines virtuelles peuvent être automatiquement alimentées dans l'ordre de votre stratégie prédéfinie.


NOTE: Bien que les systèmes ONTAP vous permettent de coupler des SVM au sein du même cluster pour la réplication SnapMirror, ce scénario n'est pas testé et certifié avec VLSR. Par conséquent, il est recommandé d'utiliser uniquement des SVM provenant de différents clusters lors de l'utilisation de VLSR.



== VLSR avec ONTAP et autres cas d'utilisation : cloud hybride et migration

L'intégration de votre déploiement VLSR aux fonctionnalités avancées de gestion des données ONTAP permet une évolutivité et des performances considérablement améliorées par rapport aux options de stockage local. Mais plus que cela, il apporte la flexibilité du cloud hybride. Le cloud hybride vous permet d'économiser de l'argent en hiérarchisant les blocs de données inutilisés de votre baie hautes performances vers votre hyperscaler préféré à l'aide de FabricPool, qui peut être un magasin S3 sur site tel que NetApp StorageGRID. Vous pouvez également utiliser SnapMirror pour les systèmes Edge avec ONTAP Select défini par logiciel ou DR basé sur le cloud à l'aide de https://www.equinix.com/partners/netapp["Stockage NetApp sur Equinix Metal"^], ou d'autres services ONTAP hébergés.

Vous pouvez ensuite effectuer un basculement de test dans le data Center d'un fournisseur de services clouds avec une empreinte de stockage proche de zéro grâce à FlexClone. La protection de votre entreprise peut à présent être plus économique que jamais.

VLSR peut également être utilisé pour exécuter des migrations planifiées en utilisant SnapMirror pour transférer efficacement vos machines virtuelles d'un data Center à un autre ou même au sein d'un même data Center, que vous le soyez propriétaire ou via plusieurs fournisseurs de services partenaires NetApp.
