---
sidebar: sidebar 
permalink: vmware/vmware-srm-overview.html 
keywords: ontap, vsphere, srm, srm, hybrid, cloud, migration, vmware, site, recovery manager, vsrm,VLSR 
summary: 'La solution ONTAP pour VMware VLSR (Live site Recovery) et SRM (site Recovery Manager)' 
---
= Restauration de site en direct VMware avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP a servi de solution de stockage de premier plan pour VMware vSphere et, plus récemment, pour les environnements Cloud Foundation depuis son introduction dans le data Center moderne en 2002. Elle continue d'introduire des fonctionnalités innovantes qui simplifient la gestion et réduisent les coûts.

Ce document présente la solution ONTAP pour VMware Live site Recovery (VLSR), anciennement site Recovery Manager (SRM), le logiciel de reprise après incident de pointe de VMware, et inclut les dernières informations sur les produits et les meilleures pratiques permettant de rationaliser le déploiement, de réduire les risques et de simplifier la gestion au quotidien.


NOTE: Cette documentation remplace le rapport technique _TR-4900 : VMware site Recovery Manager with ONTAP_

Les meilleures pratiques complètent d'autres documents, tels que des guides et des outils de compatibilité. Ils sont développés en fonction de tests effectués en laboratoire et d'une vaste expérience sur le terrain par les ingénieurs et les clients NetApp. Dans certains cas, les meilleures pratiques recommandées peuvent ne pas être adaptées à votre environnement. Cependant, ce sont généralement les solutions les plus simples qui répondent aux besoins des plus clients.

Ce document porte sur les fonctionnalités des dernières versions de ONTAP 9 utilisées conjointement avec les outils ONTAP pour VMware vSphere 10.4 (notamment NetApp Storage Replication adapter [SRA] et VASA Provider [VP]), ainsi que sur VMware Live site Recovery 9.



== Pourquoi utiliser ONTAP avec VLSR ou SRM ?

Les plateformes de gestion de données NetApp optimisées par ONTAP sont parmi les solutions de stockage les plus largement utilisées pour VLSR. Les raisons en sont nombreuses : une plateforme de gestion des données sécurisée, haute performance et multiprotocole unifié (NAS et SAN ensemble) qui fournit l'efficacité du stockage, la colocation, le contrôle de la qualité de service, la protection des données avec des copies Snapshot compactes et la réplication avec SnapMirror. Exploitez l'intégration native du multicloud hybride pour protéger vos charges de travail VMware et bénéficier de nombreux outils d'automatisation et d'orchestration à portée de main.

Lorsque vous utilisez SnapMirror pour la réplication basée sur les baies, vous tirez parti de l'une des technologies ONTAP les plus éprouvées et les plus matures. SnapMirror vous permet de transférer les données de manière sécurisée et efficace en copiant uniquement les blocs du système de fichiers modifiés, et non les machines virtuelles entières ou les datastores. Même ces blocs tirent parti des économies d'espace, telles que la déduplication, la compression et la compaction. Les systèmes ONTAP modernes utilisent désormais SnapMirror, indépendant de la version, pour vous permettre de sélectionner plus de flexibilité vos clusters source et cible. SnapMirror est véritablement devenu l'un des outils les plus puissants disponibles pour la reprise après incident.

Que vous utilisiez des datastores NFS, iSCSI ou Fibre Channel classiques (désormais avec prise en charge des datastores vvols), VLSR constitue une offre commerciale performante qui tire parti des fonctionnalités ONTAP pour la reprise après incident ou la planification et l'orchestration de la migration de data Center.



== Comment VLSR exploite ONTAP 9

VLSR exploite les technologies avancées de gestion des données des systèmes ONTAP en l'intégrant aux outils ONTAP pour VMware vSphere, une appliance virtuelle qui englobe trois composants principaux :

* Le plug-in vCenter des outils ONTAP, précédemment appelé Virtual Storage Console (VSC), simplifie les fonctionnalités d'efficacité et de gestion du stockage, améliore la disponibilité et réduit les coûts de stockage et les coûts d'exploitation, que vous utilisiez SAN ou NAS. Il s'appuie sur les bonnes pratiques pour le provisionnement des datastores et optimise les paramètres d'hôte ESXi pour les environnements de stockage NFS et bloc. Pour tous ces avantages, NetApp recommande ce plug-in lors de l'utilisation de vSphere avec les systèmes exécutant ONTAP.
* Les outils ONTAP VASA Provider prennent en charge le framework VMware vStorage APIs for Storage Awareness (VASA). Vasa Provider connecte vCenter Server avec ONTAP pour faciliter le provisionnement et la surveillance du stockage des machines virtuelles. Cela a permis la prise en charge des volumes virtuels VMware (vVols) et la gestion des politiques de stockage des machines virtuelles et des performances des vVols des machines virtuelles individuelles. Il fournit également des alarmes pour la surveillance de la capacité et la conformité avec les profils.
* SRA est utilisée en association avec VLSR pour gérer la réplication des données des machines virtuelles entre les sites de production et de reprise après incident pour les datastores VMFS et NFS traditionnels, et pour les tests non disruptives des répliques de DR. Il permet d'automatiser les tâches de détection, de restauration et de reprotection. Il comprend à la fois un serveur SRA et des adaptateurs SRA pour le serveur Windows SRM et le dispositif VLSR.


Une fois que vous avez installé et configuré les adaptateurs SRA sur le serveur VLSR pour protéger les datastores non vVols, vous pouvez commencer la tâche de configuration de votre environnement vSphere pour la reprise après incident.

SRA est une interface de commande et de contrôle pour le serveur VLSR afin de gérer les volumes ONTAP FlexVol qui contiennent vos machines virtuelles VMware, ainsi que la réplication SnapMirror qui les protège.

VLSR peut tester votre plan de reprise après incident sans interruption grâce à la technologie FlexClone propriétaire de NetApp pour créer des clones quasi instantanés de vos datastores protégés sur votre site de reprise après incident. VLSR crée un sandbox afin de tester en toute sécurité afin que votre entreprise et vos clients soient protégés en cas d'incident, vous assurant ainsi la confiance de votre entreprise dans la capacité à exécuter un basculement lors d'un incident.

En cas d'incident véritable ou même de migration planifiée, VLSR vous permet d'envoyer les modifications de dernière minute au jeu de données via une mise à jour SnapMirror finale (si vous le souhaitez). Il interrompt ensuite le miroir et monte le datastore sur vos hôtes de reprise après incident. À ce stade, vos machines virtuelles peuvent être automatiquement alimentées dans l'ordre de votre stratégie prédéfinie.


NOTE: Bien que les systèmes ONTAP vous permettent de coupler des SVM au sein du même cluster pour la réplication SnapMirror, ce scénario n'est pas testé et certifié avec VLSR. Par conséquent, il est recommandé d'utiliser uniquement des SVM provenant de différents clusters lors de l'utilisation de VLSR.



== VLSR avec ONTAP et autres cas d'utilisation : cloud hybride et migration

En intégrant votre déploiement de VLSR aux fonctionnalités avancées de gestion des données de ONTAP, vous pouvez améliorer l'évolutivité et les performances par rapport aux options de stockage local. Elle apporte cependant la flexibilité du cloud hybride. Grâce au cloud hybride, vous pouvez réaliser des économies en transférant les blocs de données non utilisés de votre baie haute performance vers votre hyperscaler préférée, via FabricPool, qui peut être un magasin S3 sur site tel que NetApp StorageGRID. Vous pouvez également utiliser SnapMirror pour les systèmes basés en périphérie avec une ONTAP Select Software-defined ou une reprise après incident dans le cloud à l'aide de Cloud Volumes ONTAP (CVO) ou https://www.equinix.com/partners/netapp["Stockage NetApp sur Equinix Metal®"^], ou d'autres services ONTAP hébergés.

Vous pouvez ensuite effectuer un basculement de test dans le data Center d'un fournisseur de services clouds avec une empreinte de stockage proche de zéro grâce à FlexClone. La protection de votre entreprise peut à présent être plus économique que jamais.

VLSR peut également être utilisé pour exécuter des migrations planifiées en utilisant SnapMirror pour transférer efficacement vos machines virtuelles d'un data Center à un autre ou même au sein d'un même data Center, que vous le soyez propriétaire ou via plusieurs fournisseurs de services partenaires NetApp.
