---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-datastores-top.html 
keywords: vSphere, datastore, VMFS, FC, NVMe/FC, NVMe/TCP, iSCSI, NFS, vVols 
summary: 'Cette page décrit les bonnes pratiques d"implémentation d"une solution de stockage ONTAP dans un environnement VMware vSphere.' 
---
= Présentation des fonctionnalités de datastore et de protocole vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Six protocoles sont utilisés pour connecter VMware vSphere aux datastores d'un système exécutant ONTAP :

* FCP
* NVMe/FC
* NVMe/TCP
* ISCSI
* NFS v3
* NFS v4.1


FCP, NVMe/FC, NVMe/TCP et iSCSI sont des protocoles en mode bloc qui utilisent VMFS (Virtual machine File System) vSphere pour stocker des machines virtuelles dans des LUN ONTAP ou des namespaces NVMe contenus dans un ONTAP FlexVol volume. NFS est un protocole de fichier qui place les machines virtuelles dans des datastores (qui sont simplement des volumes ONTAP) sans avoir besoin de VMFS. SMB (CIFS), iSCSI, NVMe/TCP ou NFS peuvent également être utilisés directement d'un système d'exploitation invité à ONTAP.

Les tableaux suivants présentent les fonctionnalités de datastore traditionnel prises en charge par vSphere avec ONTAP. Ces informations ne s'appliquent pas aux datastores vvols, mais elles s'appliquent généralement aux versions vSphere 6.x et ultérieures utilisant des versions ONTAP prises en charge. Vous pouvez également consulter le link:https://configmax.broadcom.com/guest?vmwareproduct=vSphere&release=vSphere%208.0&categories=2-0["Outil VMware Configuration Maximums"^] pour connaître les versions de vSphere spécifiques afin de confirmer les limites spécifiques.

|===
| Capacités/fonctionnalités | FC | ISCSI | NVMe-of | NFS 


| Format | Mappage de périphériques VMFS ou bruts (RDM) | VMFS ou RDM | VMFS | s/o 


| Nombre maximal de datastores ou de LUN | 1024 LUN par hôte | 1024 LUN par serveur | 256 Namespeces par serveur | 256 connexions NFS par hôte (impactées par nconnect et session Trunking) NFS par défaut. MaxVolumes est 8. Utilisez les outils ONTAP pour VMware vSphere et augmentez jusqu'à 256. 


| Taille maximale des datastores | 64 TO | 64 TO | 64 TO | FlexVol volume 300 To ou plus avec un volume FlexGroup 


| Taille maximale des fichiers du datastore | 62TO | 62TO | 62TO | 62 To avec ONTAP 9.12.1P2 et versions ultérieures 


| Profondeur de file d'attente optimale par LUN ou par système de fichiers | 64-256 | 64-256 | Négociation automatique | Se reporter à NFS.MaxQueueDepth dans link:vmware-vsphere-settings.html["Hôte ESXi recommandé et autres paramètres ONTAP recommandés"^]. 
|===
Le tableau suivant répertorie les fonctionnalités de stockage VMware prises en charge.

|===
| Capacité/fonctionnalité | FC | ISCSI | NVMe-of | NFS 


| VMotion | Oui. | Oui. | Oui. | Oui. 


| Stockage vMotion | Oui. | Oui. | Oui. | Oui. 


| Haute disponibilité VMware | Oui. | Oui. | Oui. | Oui. 


| Storage Distributed Resource Scheduler (SDRS) | Oui. | Oui. | Oui. | Oui. 


| Logiciel de sauvegarde compatible VADP (VMware vStorage APIs for Data protection) | Oui. | Oui. | Oui. | Oui. 


| Microsoft Cluster Service (MSCS) ou mise en cluster de basculement au sein d'une machine virtuelle | Oui. | Oui ^1^ | Oui ^1^ | Non pris en charge 


| Tolérance aux pannes | Oui. | Oui. | Oui. | Oui. 


| Live site Recovery Manager/site Recovery Manager | Oui. | Oui. | Non ^2^ | V3 uniquement ^2^ 


| Machines virtuelles à provisionnement fin (disques virtuels) | Oui. | Oui. | Oui. | Oui.
Ce paramètre est le paramètre par défaut pour toutes les machines virtuelles sur NFS lorsqu'elles n'utilisent pas VAAI. 


| Chemins d'accès multiples natifs VMware | Oui. | Oui. | Oui. | L'agrégation de sessions NFS v4.1 requiert ONTAP 9.14.1 et versions ultérieures 
|===
Le tableau suivant répertorie les fonctionnalités de gestion du stockage ONTAP prises en charge.

|===
| Capacités/fonctionnalités | FC | ISCSI | NVMe-of | NFS 


| Déduplication des données | D'économies sur la baie | D'économies sur la baie | D'économies sur la baie | Économies au niveau du datastore 


| Provisionnement fin | Datastore ou RDM | Datastore ou RDM | Datastore | Datastore 


| Redimensionnement datastore | Évoluer uniquement | Évoluer uniquement | Évoluer uniquement | Croissance, croissance automatique et réduction des volumes 


| Plug-ins SnapCenter pour applications Windows, Linux (invités) | Oui. | Oui. | Oui. | Oui. 


| Contrôle et configuration de l'hôte à l'aide des outils ONTAP pour VMware vSphere | Oui. | Oui. | Oui. | Oui. 


| Provisionnement avec les outils ONTAP pour VMware vSphere | Oui. | Oui. | Oui. | Oui. 
|===
Le tableau suivant répertorie les fonctionnalités de sauvegarde prises en charge.

|===
| Capacités/fonctionnalités | FC | ISCSI | NVMe-of | NFS 


| Snapshots ONTAP | Oui. | Oui. | Oui. | Oui. 


| SRM pris en charge par les sauvegardes répliquées | Oui. | Oui. | Non ^2^ | V3 uniquement ^2^ 


| SnapMirror volume | Oui. | Oui. | Oui. | Oui. 


| Accès image VMDK | Logiciels de sauvegarde compatibles SnapCenter et VADP | Logiciels de sauvegarde compatibles SnapCenter et VADP | Logiciels de sauvegarde compatibles SnapCenter et VADP | Logiciel de sauvegarde compatible SnapCenter et VADP, client vSphere et navigateur de datastore du client Web vSphere 


| Accès niveau fichier VMDK | Logiciel de sauvegarde compatible SnapCenter et VADP, Windows uniquement | Logiciel de sauvegarde compatible SnapCenter et VADP, Windows uniquement | Logiciel de sauvegarde compatible SnapCenter et VADP, Windows uniquement | Logiciels de sauvegarde compatibles SnapCenter et VADP et applications tierces 


| Granularité NDMP | Datastore | Datastore | Datastore | Datastore ou VM 
|===
^1^ *NetApp recommande* d'utiliser iSCSI dans l'invité pour les clusters Microsoft plutôt que des VMDK compatibles avec les enregistreurs multiples dans un datastore VMFS. Cette approche est entièrement prise en charge par Microsoft et VMware. Elle offre une grande flexibilité avec ONTAP (SnapMirror vers les systèmes ONTAP sur site ou dans le cloud), est facile à configurer et à automatiser, et peut être protégée avec SnapCenter. VSphere 7 ajoute une nouvelle option VMDK en cluster. Ceci est différent des VMDK compatibles avec le multiwriter, qui nécessitent un datastore VMFS 6 dont la prise en charge des VMDK en cluster est activée. D'autres restrictions s'appliquent. Consultez la documentation de VMware link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/setup-for-windows-server-failover-clustering.html["Configuration de Windows Server Failover Clustering"^]pour obtenir des instructions de configuration.

Les datastores ^2^ utilisant NVMe-of et NFS v4.1 requièrent une réplication vSphere. La réplication basée sur les baies pour NFS v4.1 n'est pas actuellement prise en charge par SRM. La réplication basée sur la baie avec NVMe-of n'est actuellement pas prise en charge par l'outil ONTAP pour VMware vSphere Storage Replication adapter (SRA).



== Sélection d'un protocole de stockage

Les systèmes exécutant ONTAP prennent en charge les principaux protocoles de stockage. Les clients peuvent ainsi choisir l'environnement le mieux adapté à leur environnement, en fonction de l'infrastructure réseau existante et planifiée, et des compétences du personnel. Historiquement, les tests NetApp ont généralement montré peu de différence entre les protocoles s'exécutant à des vitesses de ligne similaires et le nombre de connexions. Cependant, NVMe-of (NVMe/TCP et NVMe/FC) montre des gains remarquables en matière d'IOPS, de réduction de la latence et de réduction d'au moins 50 % de la consommation du processeur hôte par les E/S de stockage. À l'autre extrémité du spectre, NFS offre une flexibilité et une facilité de gestion optimales, en particulier pour un grand nombre de machines virtuelles. Tous ces protocoles peuvent être utilisés et gérés avec les outils ONTAP pour VMware vSphere, qui offrent une interface simple pour créer et gérer des datastores.

Les facteurs suivants peuvent être utiles lors de l'examen d'un choix de protocole :

* *Environnement de fonctionnement actuel.* Bien que les équipes INFORMATIQUES soient généralement compétentes en matière de gestion de l'infrastructure IP Ethernet, elles ne sont pas toutes compétentes en matière de gestion d'une structure SAN FC. Cependant, l'utilisation d'un réseau IP générique non conçu pour le trafic de stockage risque de ne pas fonctionner correctement. Considérez l'infrastructure de réseau que vous avez en place, toutes les améliorations planifiées, ainsi que les compétences et la disponibilité du personnel pour les gérer.
* *Simplicité d'installation.* au-delà de la configuration initiale de la structure FC (commutateurs et câblage supplémentaires, segmentation et vérification de l'interopérabilité des HBA et des micrologiciels), les protocoles de bloc exigent également la création et le mappage de LUN, ainsi que la découverte et le formatage par le système d'exploitation invité. Une fois les volumes NFS créés et exportés, ils sont montés par l'hôte ESXi et prêts à être utilisés. Avec NFS, il n'a pas de qualification de matériel ni de firmware à gérer.
* * Facilité de gestion.* Avec les protocoles SAN, si vous avez besoin de plus d'espace, plusieurs étapes sont nécessaires, notamment la croissance d'un LUN, la nouvelle analyse pour découvrir la nouvelle taille, puis l'expansion du système de fichiers). Bien que la croissance d'une LUN soit possible, la réduction de sa taille n'est pas le cas. NFS facilite le dimensionnement et le redimensionnement peut être automatisé par le système de stockage. SAN offre une récupération d'espace via les commandes DEALLOCATE/TRIM/UNMAP du système d'exploitation invité, ce qui permet de renvoyer dans la baie l'espace des fichiers supprimés. Ce type de récupération d'espace n'est pas difficile avec les datastores NFS.
* *Transparence de l'espace de stockage.* l'utilisation du stockage est généralement plus facile à voir dans les environnements NFS parce que le provisionnement fin renvoie immédiatement des économies. De même, les économies de déduplication et de clonage sont immédiatement disponibles pour les autres VM dans le même datastore ou pour les autres volumes du système de stockage. La densité des machines virtuelles est également meilleure généralement dans un datastore NFS, ce qui permet d'améliorer les économies de déduplication et de réduire les coûts de gestion en utilisant moins de datastores à gérer.




== Disposition des datastores

Les systèmes de stockage ONTAP offrent une grande flexibilité de création de datastores pour les machines virtuelles et les disques virtuels. Bien que de nombreuses bonnes pratiques ONTAP soient appliquées lors de l'utilisation des outils ONTAP pour provisionner des datastores pour vSphere (répertoriés dans la section link:vmware-vsphere-settings.html["Hôte ESXi recommandé et autres paramètres ONTAP recommandés"]), voici quelques instructions supplémentaires à prendre en compte :

* Le déploiement de vSphere avec des datastores NFS ONTAP offre une implémentation très performante et facile à gérer qui fournit des ratios VM/datastore qui ne peuvent pas être obtenus avec des protocoles de stockage de niveau bloc. Cette architecture peut entraîner une multiplication par dix de la densité des datastores avec une corrélation réduction du nombre de datastores. Bien qu'un datastore plus volumineux puisse bénéficier de l'efficacité du stockage et offrir des avantages opérationnels, envisagez d'utiliser au moins quatre datastores (volumes FlexVol) par nœud pour stocker vos machines virtuelles sur un seul contrôleur ONTAP afin d'optimiser les performances des ressources matérielles. Cette approche vous permet également de créer des datastores avec différentes règles de restauration. Certaines peuvent être sauvegardées ou répliquées plus fréquemment que d'autres, en fonction des besoins de l'entreprise. Les volumes FlexGroup n'ont pas besoin de plusieurs datastores pour améliorer les performances, car ils évoluent indépendamment de la conception.
* *NetApp recommande* l'utilisation de volumes FlexVol pour la plupart des datastores NFS. À partir de ONTAP 9.8, les volumes FlexGroup sont également pris en charge en tant que datastores et sont généralement recommandés pour certaines utilisations. Les autres conteneurs de stockage ONTAP, tels que les qtrees, ne sont généralement pas recommandés, car ils ne sont actuellement pas pris en charge par les outils ONTAP pour VMware vSphere ou par le plug-in NetApp SnapCenter pour VMware vSphere.
* La taille correcte des datastores de volumes FlexVol est d'environ 4 To à 8 To. Cette taille constitue un bon équilibre pour les performances, la facilité de gestion et la protection des données. Démarrer petit (disons 4 To) et développer le datastore en fonction des besoins (jusqu'au maximum 300 To) Les datastores plus petits peuvent être plus rapides à restaurer depuis la sauvegarde ou après un incident, et déplacés rapidement dans l'ensemble du cluster. Envisagez d'utiliser la fonction de dimensionnement automatique de ONTAP pour augmenter et réduire automatiquement le volume en fonction des modifications de l'espace utilisé. L'assistant ONTAP Tools for VMware vSphere datastore Provisioning utilise le dimensionnement automatique par défaut pour les nouveaux datastores. Vous pouvez également personnaliser davantage les seuils d'extension et de réduction ainsi que la taille maximale et minimale, avec System Manager ou la ligne de commandes.
* Les datastores VMFS peuvent également être configurés avec des LUN ou des espaces de noms NVMe (appelés unités de stockage dans les nouveaux systèmes ASA) accessibles via FC, iSCSI, NVMe/FC ou NVMe/TCP. VMFS permet à chaque serveur ESX d'un cluster d'accéder simultanément aux datastores. Les datastores VMFS peuvent être jusqu'à 64 To et comprennent jusqu'à 32 LUN de 2 To (VMFS 3) ou un seul LUN de 64 To (VMFS 5). La taille de LUN maximale de la baie ONTAP est de 128 To sur les systèmes AFF, ASA et FAS. NetApp recommande toujours d'utiliser une LUN unique et volumineuse pour chaque datastore, plutôt que d'utiliser les extensions. Comme pour NFS, envisagez d'utiliser plusieurs datastores (volumes ou unités de stockage) pour optimiser les performances sur un seul contrôleur ONTAP.
* Les anciens systèmes d'exploitation invités (OS) devaient s'aligner sur le système de stockage pour obtenir des performances et une efficacité du stockage optimales. Cependant, les systèmes d'exploitation actuels pris en charge par les fournisseurs de Microsoft et de distributeurs Linux tels que Red Hat ne nécessitent plus d'ajustements pour aligner la partition du système de fichiers sur les blocs du système de stockage sous-jacent dans un environnement virtuel. Si vous utilisez un ancien système d'exploitation qui peut nécessiter un alignement, recherchez dans la base de connaissances du support NetApp des articles « alignement des machines virtuelles » ou demandez une copie de l'article TR-3747 à un contact partenaire ou commercial NetApp.
* Évitez d'utiliser des utilitaires de défragmentation au sein du système d'exploitation invité, car cela n'améliore pas les performances et affecte l'efficacité du stockage et l'utilisation de l'espace Snapshot. Envisagez également de désactiver l'indexation des recherches sur le système d'exploitation invité pour les postes de travail virtuels.
* ONTAP s'est leader du marché en proposant des fonctionnalités innovantes d'efficacité du stockage qui vous permettent d'exploiter au maximum votre espace disque utilisable. Les systèmes AFF renforcent cette efficacité avec la compression et la déduplication à la volée par défaut. Les données sont dédupliquées sur tous les volumes d'un agrégat. Ainsi, vous n'avez plus besoin de regrouper des systèmes d'exploitation similaires et des applications similaires au sein d'un même datastore pour optimiser les économies.
* Dans certains cas, vous n'aurez même pas besoin d'un datastore. Envisagez des systèmes de fichiers invités, tels que NFS, SMB, NVMe/TCP ou iSCSI gérés par l'invité. Pour une assistance spécifique aux applications, consultez les rapports techniques de NetApp pour votre application. Par exemplelink:../oracle/oracle-overview.html["Les bases de données Oracle sur ONTAP"], a une section sur la virtualisation avec des détails utiles.
* Les disques de première classe (ou des disques virtuels améliorés) permettent de gérer des disques gérés par vCenter indépendamment d'une machine virtuelle dotée de vSphere 6.5 et versions ultérieures. Lorsqu'elles sont principalement gérées par API, elles peuvent être utiles avec vvols, en particulier lorsqu'elles sont gérées par les outils OpenStack ou Kubernetes. Ils sont pris en charge par ONTAP ainsi que par les outils ONTAP pour VMware vSphere.




== Migration des datastores et des machines virtuelles

Lorsque vous migrez des machines virtuelles depuis un datastore existant sur un autre système de stockage vers ONTAP, voici quelques principes à prendre en compte :

* Utilisez Storage vMotion pour déplacer la masse de vos machines virtuelles vers ONTAP. Cette approche n'assure pas seulement une exécution sans interruption des machines virtuelles. Elle permet également d'exploiter des fonctionnalités d'efficacité du stockage de ONTAP, comme la déduplication et la compression à la volée, pour traiter les données lors de leur migration. Envisagez d'utiliser les fonctionnalités de vCenter pour sélectionner plusieurs machines virtuelles dans la liste d'inventaire, puis planifiez la migration (utilisez la touche Ctrl tout en cliquant sur actions) à un moment opportun.
* Bien que vous puissiez planifier avec soin une migration vers des datastores de destination appropriés, il est souvent plus simple de les migrer en bloc, puis de les organiser ultérieurement, si nécessaire. Utilisez cette approche pour orienter la migration vers différents datastores si vous avez besoin de protection des données spécifique, par exemple des calendriers Snapshot différents. De plus, une fois les VM sur le cluster NetApp, le stockage vMotion peut utiliser les délestages VAAI pour déplacer des VM entre les datastores du cluster sans nécessiter de copie basée sur l'hôte. Notez que NFS ne décharge pas le stockage vMotion des machines virtuelles optimisées, mais VMFS.
* Les machines virtuelles qui nécessitent une migration plus minutieuse incluent les bases de données et les applications qui utilisent le stockage associé. De manière générale, envisagez l'utilisation des outils de l'application pour gérer la migration. Pour Oracle, envisagez d'utiliser des outils Oracle tels que RMAN ou ASM pour migrer les fichiers de base de données. Voir https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-overview.html["Migration des bases de données Oracle vers des systèmes de stockage ONTAP"^] pour plus d'informations. De même, pour SQL Server, envisagez d'utiliser soit SQL Server Management Studio, soit des outils NetApp tels qu'SnapManager pour SQL Server, soit SnapCenter.




== Les outils ONTAP pour VMware vSphere

La meilleure pratique la plus importante lors de l'utilisation de vSphere avec des systèmes exécutant ONTAP consiste à installer et à utiliser le plug-in ONTAP Tools for VMware vSphere (anciennement Virtual Storage Console). Ce plug-in vCenter simplifie la gestion du stockage, améliore la disponibilité et réduit les coûts de stockage et la surcharge opérationnelle, que ce soit avec SAN ou NAS, sur ASA, AFF, FAS ou même ONTAP Select (une version Software-defined ONTAP exécutée sur une machine virtuelle VMware ou KVM). Il tire parti des bonnes pratiques pour le provisionnement des datastores et optimise les paramètres des hôtes ESXi pour les délais entre les chemins d'accès multiples et les HBA (ces paramètres sont décrits dans l'annexe B). Comme il s'agit d'un plug-in vCenter, il est disponible pour tous les clients Web vSphere qui se connectent au serveur vCenter.

Le plug-in permet également d'utiliser d'autres outils ONTAP dans les environnements vSphere. Il vous permet d'installer le plug-in NFS pour VMware VAAI, ce qui permet d'alléger la copie vers ONTAP pour les opérations de clonage de machines virtuelles, de réserver de l'espace pour les fichiers de disques virtuels lourds et de décharger les snapshots ONTAP.


NOTE: Sur les clusters vSphere basés sur image, vous voulez toujours ajouter le plug-in NFS à votre image afin qu'ils ne soient pas hors conformité lors de l'installation avec les outils ONTAP.

Les outils ONTAP sont également l'interface de gestion de nombreuses fonctions du fournisseur VASA pour ONTAP, prenant en charge la gestion basée sur des règles de stockage avec vVols.

En général, *NetApp recommande* d'utiliser les outils ONTAP pour l'interface VMware vSphere dans vCenter pour provisionner les datastores traditionnels et vVols afin de s'assurer du respect des bonnes pratiques.



== Réseau général

La configuration des paramètres réseau lors de l'utilisation de vSphere avec des systèmes exécutant ONTAP est simple et similaire à celle des autres configurations réseau. Voici quelques points à prendre en compte :

* Trafic du réseau de stockage séparé des autres réseaux Un réseau distinct peut être obtenu à l'aide d'un VLAN dédié ou de commutateurs distincts pour le stockage. Si le réseau de stockage partage des chemins physiques, tels que des liaisons ascendantes, vous pouvez avoir besoin de la qualité de service ou de ports supplémentaires pour garantir une bande passante suffisante. Ne connectez pas les hôtes directement au stockage ; utilisez les commutateurs pour disposer de chemins redondants et permettez à VMware HA de fonctionner sans intervention. Voir link:vmware-vsphere-network.html["Connexion directe au réseau"] pour plus d'informations.
* Les trames Jumbo peuvent être utilisées si vous le souhaitez et prises en charge par votre réseau, en particulier lors de l'utilisation d'iSCSI. Si elles sont utilisées, assurez-vous qu'elles sont configurées de manière identique sur tous les périphériques réseau, VLAN, etc. Dans le chemin entre le stockage et l'hôte ESXi. Vous pourriez voir des problèmes de performances ou de connexion. La MTU doit également être définie de manière identique sur le switch virtuel ESXi, le port VMkernel et également sur les ports physiques ou les groupes d'interface de chaque nœud ONTAP.
* NetApp recommande uniquement de désactiver le contrôle de flux réseau sur les ports d'interconnexion de cluster au sein d'un cluster ONTAP. NetApp ne recommande pas d'autres recommandations sur les meilleures pratiques pour les ports réseau restants utilisés pour le trafic de données. Vous devez activer ou désactiver si nécessaire. Voir https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["TR-4182"^] pour plus d'informations sur le contrôle de flux.
* Lorsque les baies de stockage VMware ESXi et ONTAP sont connectées aux réseaux de stockage Ethernet, *NetApp recommande* de configurer les ports Ethernet auxquels ces systèmes se connectent en tant que ports de périphérie RSTP (Rapid Spanning Tree Protocol) ou en utilisant la fonction PortFast de Cisco. *NetApp recommande* d'activer la fonctionnalité Spanning-Tree PortFast trunk dans les environnements qui utilisent la fonctionnalité Cisco PortFast et dont l'agrégation VLAN 802.1Q est activée sur le serveur VMware ESXi ou sur les baies de stockage ONTAP.
* *NetApp recommande* les meilleures pratiques suivantes pour l'agrégation de liens :
+
** Utilisez des commutateurs qui prennent en charge l'agrégation de liens des ports sur deux châssis de commutateurs distincts grâce à une approche de groupe d'agrégation de liens multichâssis, telle que Virtual PortChannel (VPC) de Cisco.
** Désactiver LACP pour les ports de switch connectés à ESXi, sauf si vous utilisez dvswitches 5.1 ou version ultérieure avec LACP configuré.
** Utilisez LACP pour créer des agrégats de liens pour les systèmes de stockage ONTAP avec des groupes d'interfaces multimode dynamiques avec un hachage de port ou d'IP. Reportez-vous à la section https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html#dynamic-multimode-interface-group["Gestion de réseau"^] pour obtenir des conseils supplémentaires.
** Utilisez une stratégie de regroupement de hachage IP sur ESXi lors de l'agrégation de liens statiques (EtherChannel, par exemple) et des vSwitch standard ou de l'agrégation de liens basée sur LACP avec des commutateurs distribués vSphere. Si l'agrégation de liens n'est pas utilisée, utilisez plutôt « route basée sur l'ID de port virtuel d'origine ».



