---
sidebar: sidebar 
permalink: vmware/vmware-srm-ontap-tools-features.html 
keywords: vmware, site, recovery manager, vsrm, vsphere, ipv6, support, rest, api, replication, ccols, spbm, srm, appliance based 
summary: Prise en charge des fonctionnalités, limites et vVols avec les outils ONTAP. 
---
= Nouvelles fonctionnalités des outils VLSR/SRM et ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avec la transition de l'appliance virtuelle existante, les outils ONTAP apportent une richesse de nouvelles fonctionnalités, de limites plus élevées, et de la prise en charge de nouveaux vvols.



== Dernières versions de vSphere et de site Recovery Manager

NetApp a partagé un partenariat étroit avec VMware depuis près de deux décennies, et s'efforce de fournir une assistance pour les dernières versions dès que possible. Vérifiez toujours le NetApp https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité (IMT)"^] pour connaître les dernières combinaisons de logiciels qualifiées.



== Prise en charge d'IPv6

IPv6 est désormais pris en charge avec les limites suivantes :

* Non pris en charge avec SRM 8.2 (8.1, 8.3 et 8). 4 et les versions ultérieures sont prises en charge)
* Vérifiez les dernières versions qualifiées sur le https://mysupport.netapp.com/matrix/imt.jsp?components=84943;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité (IMT)"^].




== Évolutivité accrue

Les outils ONTAP 10.4 SRA prennent désormais en charge l'échelle maximale de VLSR/SRM.

* Nombre total de VM protégées = 5000
* Nombre de VM par groupe de protection = 1000
* Nombre total de plans de reprise = 250
* Nombre total de groupes de protection par plan de reprise = 250
* Nombre total de datastores répliqués = 255
* Nombre total de plans de reprise en cours d'exécution simultanée. = 10




== Réplication synchrone

Une nouvelle fonctionnalité très attendue et très attendue est la version SnapMirror synchrone (SM-S) avec ONTAP 9.5 et versions ultérieures, qui offre une solution de réplication des données avec un RPO nul et granulaire pour vos applications stratégiques. SM-S requiert ONTAP Tools 9.8 ou version ultérieure.



== Prise en charge des API REST

La configuration du serveur SRA peut désormais être gérée par les API REST. Une interface utilisateur swagger a été ajoutée pour vous aider à créer vos workflows d'automatisation. Elle est disponible sur votre appliance d'outils ONTAP à l'adresse `https://<appliance>:8443/`.
