---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-why.html 
keywords: introduction, unified storage, virtual volumes, storage efficiency, hybrid cloud 
summary: Les clients choisissent en toute confiance ONTAP pour vSphere en raison de ses solutions de stockage unifié SAN et NAS et de la nouvelle architecture de stockage désagrégée simplifiée, qui figure dans les dernières baies SAN. Cette plateforme offre une protection exceptionnelle des snapshots et des outils de gestion robustes. En transférant les fonctions vers un système de stockage dédié, ONTAP optimise les ressources hôtes, réduit les coûts et maintient des performances optimales. De plus, Storage vMotion peut facilement migrer les workloads sur VMFS, NFS ou vVols. 
---
= Pourquoi choisir ONTAP pour VMware vSphere ?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En toute confiance, les entreprises choisissent ONTAP pour vSphere à la fois pour les solutions de stockage SAN et NAS.la nouvelle architecture de stockage désagrégée simplifiée, incluse dans les dernières baies SAN, offre une expérience simplifiée aux administrateurs de stockage SAN tout en conservant la plupart des intégrations et l'ensemble de fonctionnalités des systèmes ONTAP classiques. Les systèmes ONTAP offrent une protection exceptionnelle des snapshots et des outils de gestion robustes. En transférant les fonctions vers un système de stockage dédié, ONTAP optimise les ressources hôtes, réduit les coûts et maintient des performances optimales. De plus, Storage vMotion peut facilement migrer les workloads sur VMFS, NFS ou vVols.



== Avantages de l'utilisation de ONTAP pour vSphere

De nombreuses raisons ont poussé des dizaines de milliers de clients à choisir ONTAP comme solution de stockage pour vSphere, par exemple un système de stockage unifié prenant en charge les protocoles SAN et NAS, des fonctionnalités robustes de protection des données à l'aide de copies Snapshot compactes et une multitude d'outils pour vous aider à gérer les données applicatives. En utilisant un système de stockage distinct de l'hyperviseur, vous pouvez décharger de nombreuses fonctions et optimiser votre investissement dans les systèmes hôtes vSphere. En plus de s'assurer que les ressources de vos hôtes sont concentrées sur les charges de travail applicatives, vous évitez également l'impact aléatoire sur les performances des applications en provenance des opérations de stockage.

L'association de ONTAP et de vSphere permet de réduire les dépenses liées au matériel hôte et aux logiciels VMware. Vous pouvez également protéger vos données à moindre coût grâce à des performances élevées et prévisibles. Les charges de travail virtualisées étant mobiles, vous pouvez explorer différentes approches à l'aide de Storage vMotion afin de déplacer des ordinateurs virtuels entre des datastores VMFS, NFS ou vvols, le tout sur un même système de stockage.

Voici les principaux facteurs dont la valeur aujourd'hui est :

* *Stockage unifié.* Les systèmes qui exécutent ONTAP sont unifiés de plusieurs manières. À l'origine, cette approche était appelée protocoles NAS et SAN, et ONTAP continue d'être une plateforme SAN de premier plan en plus de ses capacités d'origine dans le stockage NAS. Dans le monde de vSphere, cette approche peut également se traduire par un système unifié d'infrastructure de postes de travail virtuels (VDI) avec une infrastructure de serveurs virtuels (VSI). Les systèmes qui exécutent ONTAP sont généralement moins onéreux pour VSI que les baies d'entreprise traditionnelles, tout en offrant des fonctionnalités avancées d'efficacité du stockage pour la gestion de l'infrastructure VDI dans le même système. ONTAP unifie également une grande variété de supports de stockage, des SSD aux SATA, et peut s'étendre facilement au cloud. Il n'est pas nécessaire d'acheter un système d'exploitation du stockage pour les performances, un autre pour les archives et un autre pour le cloud. ONTAP les lie tous ensemble.
* *Baie SAN (ASA).* Les derniers systèmes ONTAP ASA (à partir des modèles A1K, A90, A70, A50, A30 et A20) reposent sur une nouvelle architecture de stockage qui élimine le modèle de stockage ONTAP classique utilisé pour la gestion des agrégats et des volumes. Comme il n'existe aucun partage de système de fichiers, les volumes ne sont pas nécessaires. Tout le stockage rattaché à une paire HA est traité comme une zone de disponibilité du stockage commune (SAZ) dans laquelle les LUN et les espaces de noms NVMe sont provisionnés en tant que « unités de stockage » (MU). Les derniers systèmes ASA sont conçus pour être faciles à gérer et offrent une expérience familière aux administrateurs de stockage SAN. Cette nouvelle architecture est idéale pour les environnements vSphere, car elle facilite la gestion des ressources de stockage et simplifie l'expérience des administrateurs de stockage SAN. L'architecture ASA prend également en charge la dernière technologie NVMe over Fabrics (NVMe-of) qui améliore encore les performances et l'évolutivité des workloads vSphere.
* *Technologie Snapshot.* ONTAP a été le premier à proposer une technologie Snapshot pour la protection des données et reste la plus avancée du secteur. Cette approche peu gourmande en espace pour la protection des données a été étendue pour prendre en charge les API VMware vSphere pour l'intégration de baies (VAAI). Cette intégration vous permet de tirer parti des fonctionnalités Snapshot de ONTAP pour les opérations de sauvegarde et de restauration, réduisant ainsi l'impact sur votre environnement de production. Cette approche vous permet également d'utiliser des snapshots pour une restauration rapide des machines virtuelles, réduisant ainsi le temps et les efforts nécessaires à la restauration des données. De plus, la technologie Snapshot de ONTAP est intégrée aux solutions VLSR (Live site Recovery Manager) de VMware, offrant ainsi une stratégie complète de protection des données pour votre environnement virtualisé.
* *Gestion basée sur les volumes virtuels et les stratégies de stockage.* NetApp a été un partenaire de conception précoce avec VMware dans le développement de vSphere Virtual volumes (vvols), en fournissant des informations architecturales et une prise en charge précoce pour vvols et VMware vSphere API for Storage Awareness (VASA). Non seulement cette approche intègre la gestion granulaire du stockage des machines virtuelles à VMFS, mais elle a également pris en charge l'automatisation du provisionnement du stockage via la gestion basée sur des règles de stockage. Cette approche permet aux architectes du stockage de concevoir des pools de stockage dont les capacités sont facilement utilisable par les administrateurs de machines virtuelles. ONTAP est leader du secteur du stockage en matière d'évolutivité vvol, en gérant des centaines de milliers de vvols dans un seul cluster, alors que les fournisseurs de baies d'entreprise et de baies Flash de plus petite taille prennent en charge à peine plusieurs milliers de vvols par baie. NetApp favorise également l'évolution de la gestion granulaire des serveurs virtuels avec des fonctionnalités à venir.
* *Efficacité du stockage.* Bien que NetApp ait été le premier à fournir la déduplication pour les charges de travail de production, cette innovation n'a pas été la première ou la dernière dans ce domaine. Il a commencé par les copies Snapshot, un mécanisme de protection des données peu encombrant et sans impact sur les performances, ainsi que la technologie FlexClone, qui permet de réaliser instantanément des copies en lecture/écriture des machines virtuelles pour la production et la sauvegarde. NetApp a continué à proposer des fonctionnalités en ligne, notamment la déduplication, la compression et la déduplication des blocs « zéro », afin d'exploiter tout le stockage provenant de disques SSD très coûteux. ONTAP a également ajouté la possibilité de stocker des opérations et des fichiers d'E/S plus petits dans un bloc de disque à l'aide de la compaction. L'association de ces fonctionnalités a permis aux clients d'économiser jusqu'à 5:1 pour VSI et jusqu'à 30:1 pour VDI. La nouvelle génération de systèmes ONTAP inclut également la compression et la déduplication à accélération matérielle, ce qui permet d'améliorer l'efficacité du stockage et de réduire les coûts. Cette approche vous permet de stocker plus de données en utilisant moins d'espace, ce qui réduit le coût global du stockage et améliore les performances. NetApp a une telle confiance dans ses fonctionnalités d'efficacité du stockage qu'elle offre un lien :https://www.netapp.com/pdf.html?item=/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf [garantie d'efficacité^].
* *Colocation.* ONTAP a longtemps été l'un des leaders de la colocation, ce qui vous permet de créer plusieurs serveurs virtuels de stockage (SVM) sur un seul cluster. Cette approche vous permet d'isoler des charges de travail et de fournir différents niveaux de service à différents locataires, ce qui en fait la solution idéale pour les fournisseurs de services et les grandes entreprises. La dernière génération de systèmes ONTAP inclut également la prise en charge de la gestion de la capacité. Cette fonctionnalité vous permet de définir des limites de capacité pour chaque locataire, afin qu'aucun locataire ne puisse consommer toutes les ressources disponibles. Cette approche permet de s'assurer que tous les locataires reçoivent le niveau de service qu'ils attendent, tout en assurant un niveau élevé de sécurité et d'isolation entre eux. De plus, les fonctionnalités de colocation de ONTAP sont intégrées à la plateforme vSphere de VMware, ce qui vous permet de gérer et de surveiller facilement votre environnement virtualisé via https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["Les outils ONTAP pour VMware vSphere"] et https://docs.netapp.com/us-en/data-infrastructure-insights/["Informations exploitables sur l'infrastructure de données"].
* *Cloud hybride.* qu'il soit utilisé pour le cloud privé sur site, une infrastructure de cloud public ou un cloud hybride qui associe le meilleur des deux types de clouds, les solutions ONTAP vous aident à créer votre Data Fabric pour rationaliser et optimiser la gestion des données. Commencez par des systèmes 100 % Flash haute performance, puis coupler les avec des systèmes de stockage sur disque ou cloud pour la protection des données et le cloud computing. Vous pouvez choisir entre des clouds Azure, AWS, IBM ou Google pour optimiser les coûts et éviter l'enfermement propriétaire. Bénéficiez de la prise en charge avancée des technologies OpenStack et de conteneur, selon vos besoins. NetApp propose également des solutions de sauvegarde cloud (SnapMirror Cloud, Cloud Backup Service et Cloud Sync), ainsi que des outils de Tiering du stockage et d'archivage (FabricPool) pour ONTAP afin de réduire les dépenses d'exploitation et d'exploiter la portée du cloud.
* *Et plus.* tirez parti des performances extrêmes des baies NetApp AFF A-Series pour accélérer votre infrastructure virtualisée tout en gérant les coûts. Assurez la continuité totale de l'activité, qu'il s'agisse de la maintenance ou des mises à niveau, ou du remplacement complet de votre système de stockage à l'aide de clusters ONTAP scale-out. Protégez vos données au repos avec les fonctionnalités de chiffrement NetApp, sans frais supplémentaires. Assurez-vous que les performances respectent les niveaux de service grâce à des fonctionnalités de qualité de service très avancées. Elles font toutes partie du vaste éventail de fonctionnalités fournies par ONTAP, le logiciel de gestion des données d'entreprise leader du secteur.

