---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-settings.html 
keywords: VMware,vSphere,ESXi,settings,NFS,iSCSI,FC,FCP 
summary: Ce document classe et énumère les paramètres de stockage et de réseau recommandés. 
---
= Hôte ESXi recommandé et autres paramètres ONTAP recommandés
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp a développé un ensemble de paramètres hôtes ESXi optimaux pour les protocoles NFS et les protocoles en mode bloc. Des conseils spécifiques sont également fournis concernant les paramètres de chemins d'accès multiples et de délai d'expiration des HBA pour un comportement correct avec ONTAP basé sur les tests internes NetApp et VMware.

Ces valeurs sont facilement définies à l'aide des outils ONTAP pour VMware vSphere : dans la page de présentation des outils ONTAP, faites défiler vers le bas et cliquez sur appliquer les paramètres recommandés dans le portlet conformité des hôtes ESXi.

Voici les paramètres d'hôte recommandés pour toutes les versions de ONTAP actuellement prises en charge.

|===
| *Paramètres hôte* | *Valeur recommandée par NetApp* | *Redémarrer requis* 


3+| *Configuration avancée ESXi* 


| VMFS3.HardwareAccélérationde la localisation | Conserver la valeur par défaut (1) | Non 


| VMFS3.EnableBlockDelete | Conserver la valeur par défaut (0), mais peut être modifiée si nécessaire. Pour plus d'informations, voir link:https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-provisioning-and-space-reclamation-in-vsphere/storage-space-reclamation-in-vsphere/space-reclamation-for-guest-operating-systems.html["Récupération d'espace pour les machines virtuelles VMFS5"] | Non 


| VMFS3.EnableVMFS6Unmap | Conserver la valeur par défaut (1) pour plus d'informations, voir link:https://www.vmware.com/docs/vmw-vmware-vsphere-apis-array-integration-vaai["API VMware vSphere : intégration des baies (VAAI)"] | Non 


3+| *Paramètres NFS* 


| NewSyncInterval | Si vous n'utilisez pas vSphere CSI pour Kubernetes, définissez-le comme indiqué https://knowledge.broadcom.com/external/article/386364/reducing-excessive-vsan-cnssync-warnings.html["VMware KB 386364"^] | Non 


| Net.TcpipeHeapSize | VSphere 6.0 ou version ultérieure, défini sur 32.
Toutes les autres configurations NFS, définies sur 30 | Oui. 


| Net.TcpipeHeapMax | Défini sur 512 Mo pour la plupart des versions vSphere 6.X.
Réglez sur la valeur par défaut (1024 Mo) pour 6.5U3, 6.7U3 et 7.0 ou ultérieure. | Oui. 


| NFS.MaxVolumes | VSphere 6.0 ou version ultérieure, défini sur 256
Toutes les autres configurations NFS définies sur 64. | Non 


| NFS41.Maxvolumes | VSphere 6.0 ou version ultérieure, défini sur 256. | Non 


| NFS.MaxQueueDepth^1^ | VSphere 6.0 ou version ultérieure, défini sur 128 | Oui. 


| NFS.HeartbeatMaxFailures | Définissez sur 10 pour l'ensemble des configurations NFS | Non 


| NFS.HeartbeatFrequency | Définissez la valeur 12 pour toutes les configurations NFS | Non 


| NFS.HeartbeatTimeout | Définissez sur 5 pour l'ensemble des configurations NFS. | Non 


| Sunrpc.MaxConnPerIP | vSphere 7.0 à 8.0, défini sur 128.  Ce paramètre est ignoré dans les versions ESXi ultérieures à 8.0. | Non 


3+| *Paramètres FC/FCoE* 


| Stratégie de sélection de chemin | Définissez-le sur RR (Round Robin) lorsque des chemins FC avec ALUA sont utilisés. Défini sur FIXE pour toutes les autres configurations.
La définition de cette valeur sur RR permet d'équilibrer la charge sur l'ensemble des chemins actifs/optimisés.
La valeur FIXÉE est pour les anciennes configurations non ALUA et contribue à empêcher les E/S proxy En d'autres termes, il contribue à empêcher les E/S de se diriger vers l'autre nœud d'une paire haute disponibilité dans un environnement doté de Data ONTAP 7-mode | Non 


| Disk.QFullSampleSize | Définissez sur 32 pour toutes les configurations.
La définition de cette valeur permet d'éviter les erreurs d'E/S. | Non 


| Disk.QFullThreshold | Réglez à 8 pour toutes les configurations.
La définition de cette valeur permet d'éviter les erreurs d'E/S. | Non 


| Délais d'expiration de la carte HBA FC Emulex | Utilisez la valeur par défaut. | Non 


| Délais de connexion HBA FC QLogic | Utilisez la valeur par défaut. | Non 


3+| *Paramètres iSCSI* 


| Stratégie de sélection de chemin | Définissez à RR (Round Robin) pour tous les chemins iSCSI.
La définition de cette valeur sur RR permet d'équilibrer la charge sur l'ensemble des chemins actifs/optimisés. | Non 


| Disk.QFullSampleSize | Définissez sur 32 pour toutes les configurations.
La définition de cette valeur permet d'éviter les erreurs d'E/S. | Non 


| Disk.QFullThreshold | Réglez à 8 pour toutes les configurations.
La définition de cette valeur permet d'éviter les erreurs d'E/S. | Non 
|===

NOTE: Option de configuration avancée NFS MaxQueueDepth peut ne pas fonctionner comme prévu lors de l'utilisation de VMware vSphere ESXi 7.0.1 et de VMware vSphere ESXi 7.0.2. Référence link:https://kb.vmware.com/s/article/86331?lang=en_US["VMware KB 86331"] pour plus d'informations.

Lors de la création de volumes et de LUN ONTAP FlexVol, les outils ONTAP permettent également de spécifier certains paramètres par défaut :

|===


| *Outil ONTAP* | *Paramètre par défaut* 


| Réserve Snapshot (-percent-snapshot-space) | 0 


| Réserve fractionnaire (-réserve fractionnaire) | 0 


| Mise à jour de l'heure d'accès (-atime-update) | Faux 


| Lecture minimum (-min-lecture anticipée) | Faux 


| Snapshots planifiés | Aucune 


| Efficacité du stockage | Activé 


| Garantie de volume | Aucune (provisionnement fin) 


| Taille automatique du volume | augmenter_réduire 


| Réservation d'espace par LUN | Désactivé 


| Allocation d'espace de la LUN | Activé 
|===


== Paramètres de chemins d'accès multiples pour les performances

Bien qu'il ne soit pas actuellement configuré par les outils ONTAP disponibles, NetApp suggère les options de configuration suivantes :

* Lorsque vous utilisez des systèmes non ASA dans des environnements hautes performances ou lorsque vous testez les performances avec une seule banque de données LUN, envisagez de modifier le paramètre d'équilibrage de charge de la stratégie de sélection de chemin (PSP) à tour de rôle (VMW_PSP_RR) du paramètre IOPS par défaut de 1 000 à une valeur de 1.  Voirlink:https://knowledge.broadcom.com/external/article?legacyId=2069356["VMware KB 2069356"^] pour plus d'infos.
* Dans vSphere 6.7 Update 1, VMware a introduit un nouveau mécanisme d’équilibrage de charge de latence pour le Round Robin PSP.  L'option de latence est désormais également disponible lors de l'utilisation du HPP (High Performance Plugin) avec les espaces de noms NVMe et avec vSphere 8.0u2 et versions ultérieures, les LUN connectés iSCSI et FCP.  La nouvelle option prend en compte la bande passante d'E/S et la latence du chemin lors de la sélection du chemin optimal pour les E/S.  NetApp recommande d'utiliser l'option de latence dans les environnements avec une connectivité de chemin non équivalente, comme dans les cas avec plus de sauts réseau sur un chemin que sur un autre, ou lors de l'utilisation d'un système NetApp ASA .  Voir https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts.html#GUID-1940AE9E-04CF-40BE-BB71-398621F0642E-en["Modifier les paramètres par défaut pour le tour de latence"^] pour plus d'informations.




== Documentation complémentaire

Pour FCP et iSCSI avec vSphere 7, des informations supplémentaires sont disponibles à l'adresse link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_7.html["Utilisez VMware vSphere 7.x avec ONTAP"^] pour FCP et iSCSI avec vSphere 8. Vous trouverez plus de détails à l'adresse link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["Utilisez VMware vSphere 8.x avec ONTAP"^] concernant NVMe-of avec vSphere 7. Des informations plus détaillées sont disponibles à l'adresse link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_7.html["Pour plus de détails sur NVMe-of, consultez la page Configuration d'hôte NVMe-of pour ESXi 7.x avec ONTAP"^] concernant NVMe-of avec vSphere 8. Des informations plus détaillées sont disponibles à l'adresse link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["Pour plus de détails sur NVMe-of, consultez la page Configuration d'hôte NVMe-of pour ESXi 8.x avec ONTAP"^]
