---
sidebar: sidebar 
permalink: vmware/vmware-srm-additional-information.html 
keywords: vmware, site, recovery manager, vsrm, hybrid, cloud, additional, information 
summary: Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web. 
---
= Informations supplémentaires
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les informations données dans ce livre blanc, consultez ces documents et/ou sites web :

* Tr-4597 : VMware vSphere pour ONTAP
link:vmware-vsphere-overview.html["https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html"]
* Tr-4400 : volumes virtuels VMware vSphere avec ONTAP
link:vmware-vvols-overview.html["https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vvols-overview.html"]
* Tr-4015 Guide des meilleures pratiques en matière de configuration de SnapMirror pour ONTAP 9
link:https://www.netapp.com/media/17229-tr4015.pdf?v=127202175503P["https://www.netapp.com/media/17229-tr4015.pdf?v=127202175503P"]
* Créateur d'utilisateurs RBAC pour ONTAP
link:https://mysupport.netapp.com/site/tools/tool-eula/rbac["https://mysupport.netapp.com/site/tools/tool-eula/rbac"]
* Outils ONTAP pour les ressources VMware vSphere
link:https://mysupport.netapp.com/site/products/all/details/otv/docsandkb-tab["https://mysupport.netapp.com/site/products/all/details/otv/docsandkb-tab"]
* Documentation VMware site Recovery Manager
link:https://docs.vmware.com/en/Site-Recovery-Manager/index.html["https://docs.vmware.com/en/Site-Recovery-Manager/index.html"]


Reportez-vous à la link:http://mysupport.netapp.com/matrix["Matrice d'interopérabilité (IMT)"] Le site de support NetApp vous assure que les versions de produits et de fonctionnalités mentionnées dans le présent document sont prises en charge par votre environnement. NetApp IMT définit les composants et versions de produits qu'il est possible d'utiliser pour créer des configurations prises en charge par NetApp. Les résultats dépendent des installations de chaque client et de leur conformité aux spécifications publiées.
