---
sidebar: sidebar 
permalink: vmware/vmware-srm-vvol-troubleshooting.html 
keywords: vmware, site, recovery manager, vlsr, hybrid, cloud, srm, vvols, replication 
summary: La réplication des vVols avec VASA offre des fonctionnalités uniques par rapport à SRA et aux datastores classiques. 
---
= Dépannage de VLSRM/SRM lors de l'utilisation de la réplication vVols
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de l'utilisation des outils ONTAP 9.13P2, le workflow au sein de VLSR et de SRM est très différent lors de l'utilisation de la réplication vVols par rapport à l'utilisation de SRA et des datastores traditionnels. Par exemple, il n'existe pas de concept de gestionnaire de baie. Ainsi, `discoverarrays` les commandes et `discoverdevices` ne sont jamais vues.

Lors du dépannage, il est utile de comprendre les nouveaux flux de travail répertoriés ci-dessous :

. QueryReplicationPeer : détecte les accords de réplication entre deux domaines de défaillance.
. QueryFaultDomain : détecte la hiérarchie du domaine de pannes.
. QueryReplicationGroup : détecte les groupes de réplication présents dans les domaines source ou cible.
. SyncReplicationGroup : synchronise les données entre la source et la cible.
. QueryPointInTimeReplica : détecte le point dans le temps des répliques sur une cible.
. TestFailoverReplicationGroupStart : démarre le basculement de test.
. TestFailoverReplicationGroupStop : met fin au basculement de test.
. PromoteReplicationGroup : promeut un groupe actuellement en cours de test à la production.
. PreparFailoverReplicationTM : prépare une reprise après sinistre.
. FailoverReplicationGroup : exécute la reprise après incident.
. ReverseReplicateGroup : lance la réplication inverse.
. QueryMatchingContainer : recherche les conteneurs (ainsi que les hôtes ou les groupes de réplication) susceptibles de satisfaire une demande de provisionnement avec une règle donnée.
. QueryResourceMetadata : recherche les métadonnées de toutes les ressources du fournisseur VASA, l'utilisation des ressources peut être renvoyée comme réponse à la fonction queryMatchingContainer.


L'erreur la plus courante lors de la configuration de la réplication vvols est une incapacité à découvrir les relations SnapMirror. En effet, les volumes et les relations SnapMirror sont créés en dehors de la purView des outils ONTAP. Il est donc recommandé de toujours s'assurer que votre relation SnapMirror est totalement initialisée et que vous avez exécuté une redécouverte dans les outils ONTAP sur les deux sites avant de tenter de créer un datastore vvols répliqué.
