---
sidebar: sidebar 
permalink: vmware/vmware-vsphere-flexgroups.html 
keywords: vSphere, datastore, VMFS, FC, FCoE, NVMe/FC, iSCSI, NFS, vVols 
summary: 'Cette page décrit les meilleures pratiques relatives à l"implémentation d"une solution de stockage NetApp ONTAP dans un environnement VMware vSphere.' 
---
= Groupes flexibles
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revnumber: 9.8 adds support for FlexGroup datastores in vSphere
:revdate: along with the ONTAP tools for VMware vSphere 9.8 release.


FlexGroup simplifie la création de datastores volumineux et crée automatiquement un certain nombre de volumes constitutifs afin d'optimiser les performances d'un système ONTAP. Utilisez FlexGroup avec vSphere pour créer un datastore vSphere unique et évolutif tout en bénéficiant de la puissance d'un cluster ONTAP complet.

En plus des tests exhaustifs sur les charges de travail vSphere, ONTAP 9.8 propose également un nouveau mécanisme d'allègement de la charge de données pour les datastores FlexGroup. Un moteur de copie amélioré permet de copier des fichiers entre les composants en arrière-plan tout en permettant l'accès à la source et à la destination. Plusieurs copies utilisent les clones de fichiers instantanément disponibles dans un composant, si nécessaire, en fonction des évolutions.

ONTAP 9.8 propose également de nouvelles mesures de performance basées sur les fichiers (IOPS, débit et latence) pour les fichiers FlexGroup. Ces metrics sont également consultables dans le tableau de bord et les rapports des machines virtuelles de ONTAP pour VMware vSphere. Les outils ONTAP pour le plug-in VMware vSphere vous permettent également de définir des règles de qualité de service (QoS) en combinant des IOPS minimales et/ou maximales. Ils peuvent être définis au sein de toutes les machines virtuelles d'un datastore ou individuellement pour des machines virtuelles spécifiques.

Voici quelques meilleures pratiques supplémentaires que NetApp a développées :

* Utilisez les valeurs par défaut de provisionnement FlexGroup. Les outils ONTAP pour VMware vSphere sont recommandés, car ils créent et montés FlexGroup dans vSphere, mais ONTAP System Manager ou la ligne de commandes peuvent être utilisés pour des besoins particuliers. Ensuite, utilisez les valeurs par défaut, telles que le nombre de membres constitutifs par nœud, car c'est ce qui a été testé avec vSphere.
* Lors du dimensionnement d'un datastore FlexGroup, n'oubliez pas que le FlexGroup est constitué de plusieurs petits volumes FlexVol qui créent un espace de noms plus important. Par conséquent, dimensionnez le datastore pour qu'il soit au moins 8x de la taille de votre plus grande machine virtuelle. Par exemple, si votre environnement contient une machine virtuelle de 6 To, sa taille FlexGroup n'est pas inférieure à 48 To.
* Autoriser FlexGroup à gérer l'espace du datastore. La taille automatique et le dimensionnement souple ont été testés avec les datastores vSphere. Si la capacité totale du datastore est proche de celle maximale, utilisez les outils ONTAP pour VMware vSphere ou un autre outil pour redimensionner le volume FlexGroup. FlexGroup permet d'équilibrer la capacité et les inodes entre les composants, en hiérarchisant les fichiers d'un dossier (VM) vers le même composant si la capacité le permet.
* Actuellement, VMware et NetApp ne prennent pas en charge une approche commune de mise en réseau multivoie. Pour NFSv4.1, NetApp prend en charge pNFS, tandis que VMware prend en charge l'agrégation de sessions. NFSv3 ne prend pas en charge plusieurs chemins physiques vers un volume. Pour les environnements FlexGroup avec ONTAP 9.8, nous vous recommandons de laisser les outils ONTAP pour VMware vSphere effectuer le montage unique, car les effets de l'accès indirect sont généralement minimes (microsecondes). Il est possible d'utiliser un DNS round-Robin pour distribuer les hôtes ESXi sur les LIF de différents nœuds de la FlexGroup, mais cela nécessiterait la création et le montage de la FlexGroup sans les outils ONTAP pour VMware vSphere. Dans ce cas, les fonctionnalités de gestion des performances ne sont pas disponibles.
* La prise en charge du datastore FlexGroup vSphere a été testée jusqu'à 1500 machines virtuelles dans la version 9.8.
* Utilisez le plug-in NFS pour VMware VAAI pour la copie auxiliaire. Notez que même si le clonage est amélioré dans un datastore FlexGroup, ONTAP ne fournit pas d'avantages significatifs en termes de performances par rapport à la copie d'hôte ESXi lors de la copie de machines virtuelles entre des volumes FlexVol et/ou FlexGroup.
* Utilisez les outils ONTAP pour VMware vSphere 9.8 pour surveiller les performances des machines virtuelles FlexGroup à l'aide de metrics de ONTAP (tableau de bord et rapports sur les machines virtuelles), et pour gérer la qualité de service sur des machines virtuelles individuelles. Ces metrics ne sont pas encore disponibles via les commandes ou les API ONTAP.
* À ce moment-là, la qualité de service (IOPS max/min) peut être définie sur des machines virtuelles individuelles ou sur toutes les machines virtuelles d'un datastore. La définition de la qualité de service sur toutes les VM remplace tous les paramètres distincts par VM. Les paramètres ne s'étendent pas ultérieurement aux nouvelles machines virtuelles ou aux machines virtuelles migrées ; définissez la qualité de service sur les nouvelles machines virtuelles ou appliquez à nouveau la qualité de service à toutes les machines virtuelles du datastore.
* Le plug-in SnapCenter pour VMware vSphere version 4.4 prend en charge la sauvegarde et la restauration des machines virtuelles dans un datastore FlexGroup sur le système de stockage primaire. Même si SnapMirror peut être utilisé manuellement pour répliquer un FlexGroup sur un système secondaire, le distributeur sélectif n° 4.4 ne gère pas les copies secondaires.

