---
sidebar: sidebar 
permalink: oracle/dr/oracle-dr-overview.html 
keywords: metrocluster, syncmirror, oracle 
summary: Reprise après incident Oracle avec ONTAP 
---
= Reprise après incident avec ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La reprise d'activité consiste à restaurer les services de données après une catastrophe, par exemple un incendie qui détruit un système de stockage, voire un site entier.


NOTE: Cette documentation remplace les rapports techniques _TR-4591 : Oracle Data protection_ et _TR-4592 : Oracle on MetroCluster._

La reprise après incident peut être effectuée par une simple réplication des données à l'aide de SnapMirror, bien sûr, lorsque de nombreux clients mettent à jour les réplicas en miroir toutes les heures.

Pour la plupart des clients, la reprise après incident ne suffit pas à posséder une copie distante des données. Il est donc nécessaire de pouvoir les exploiter rapidement. NetApp propose deux technologies pour répondre à ce besoin : MetroCluster et SnapMirror Business Continuity (SM-BC)

MetroCluster fait référence à ONTAP dans une configuration matérielle qui inclut un stockage en miroir synchrone de faible niveau et de nombreuses fonctionnalités supplémentaires. Les solutions intégrées telles que MetroCluster simplifient les bases de données, les applications et les infrastructures de virtualisation complexes et évolutives. Elle remplace plusieurs produits et stratégies externes de protection des données par une seule baie de stockage centrale simple. Elle offre également des fonctionnalités intégrées de sauvegarde, de restauration, de reprise après incident et de haute disponibilité au sein d'un seul système de stockage en cluster.

La continuité de l'activité SnapMirror (SM-BC) est basée sur la technologie SnapMirror synchrone. Avec MetroCluster, chaque contrôleur ONTAP est responsable de la réplication des données de son disque vers un emplacement distant. Avec SM-BC, vous disposez essentiellement de deux systèmes ONTAP différents qui conservent des copies indépendantes de vos données LUN, mais qui coopèrent pour présenter une seule instance de ce LUN. Du point de vue de l'hôte, il s'agit d'une entité LUN unique.

Bien que SM-BC et MetroCluster fonctionnent très différemment en interne, le résultat est très similaire pour un hôte. La principale différence est la granularité. Si vous n'avez besoin que de workloads spécifiques pour la réplication synchrone, la solution SM-BC est la mieux adaptée. Si vous devez répliquer des environnements entiers, voire des data centers, MetroCluster est la meilleure option. Par ailleurs, SM-BC est actuellement réservé aux environnements SAN, tandis que MetroCluster est multiprotocole, y compris SAN, NFS et SMB.
