---
sidebar: sidebar 
permalink: epic/epic-example-platforms.html 
keywords: epic,cache,iris 
summary: Exemple de déploiement Epic sur ONTAP - protocoles 
---
= Exemple de déploiement Epic sur ONTAP - plateformes
:allow-uri-read: 


[role="lead"]
Pour les bases de données ODB, les journaux et les workloads applicatifs Epic recommande de présenter le stockage aux serveurs sous forme de LUN FCP.

NetApp prend également en charge l'utilisation de NVMe/FC (si certaines versions des systèmes d'exploitation AIX et RHEL sont compatibles) et améliore les performances. FCP et NVMe/FC peuvent coexister sur la même structure.

Les clients NetApp ont exécuté avec succès toutes les charges de travail Epic dans le cloud Azure.  AWS et Google Cloud sont également capables d’exécuter des charges de travail Epic.  NetApp fournit les fonctionnalités de classe entreprise et les performances requises pour exécuter efficacement Epic dans le cloud.  Les options cloud NetApp offrent un blocage sur iSCSI et un fichier sur NFS ou SMB.
