---
sidebar: sidebar 
permalink: mysql/mysql-innodb_io_capacity.html 
keywords: MySQL,MariaDB,innodb_io_capacity 
summary: MySQL et innodb_io_Capacity 
searchtitle: MySQL et innodb_io_Capacity 
---
= innodb_io_capacity
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans le plug-in InnoDB, un nouveau paramètre appelé innodb_io_Capacity a été ajouté à partir de MySQL 5.7.

Il contrôle le nombre maximal d'IOPS qu'InnoDB exécute (qui inclut la vitesse de vidage des pages sales ainsi que la taille de lot du tampon d'insertion [ibuf]). Le paramètre innodb_io_Capacity définit une limite supérieure sur les IOPS par les tâches d'arrière-plan InnoDB, telles que le vidage des pages du pool de mémoire tampon et la fusion des données à partir du tampon de changement.

Définissez le paramètre innodb_io_Capacity sur le nombre approximatif d'opérations d'E/S que le système peut effectuer par seconde. Idéalement, maintenez le paramètre aussi bas que possible, mais pas si bas que les activités en arrière-plan ralentissent. Si le paramètre est trop élevé, les données sont supprimées du pool de mémoire tampon et la mémoire tampon est insérée trop rapidement pour que la mise en cache offre un avantage significatif.


TIP: *NetApp recommande* que si vous utilisez ce paramètre sur NFS, analysez le résultat du test d'IOPS (SysBench/FiO) et définissez le paramètre en conséquence. Utilisez la plus petite valeur possible pour le vidage et la purge pour continuer à fonctionner, sauf si vous voyez plus de pages modifiées ou sales que vous le souhaitez dans le pool de mémoire tampon InnoDB.


CAUTION: N'utilisez pas de valeurs extrêmes telles que 20,000 ou plus, sauf si vous avez prouvé que des valeurs inférieures ne suffisent pas à votre charge de travail.

Le paramètre InnoDB_IO_Capacity régule les débits de rinçage et les E/S associées


CAUTION: Vous pouvez sérieusement nuire aux performances en définissant ce paramètre ou le paramètre innodb_io_Capacity_max trop élevé et gaspillé
