---
sidebar: sidebar 
permalink: mysql/mysql-innodb_lru_scan_depth.html 
keywords: MySQL,MariaDB,innodb_lru_scan_depth 
summary: MySQL et innodb_lru_scan_depth 
---
= innodb_lru_scan_depth
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `innodb_lru_scan_depth` Le paramètre influence les algorithmes et les heuristiques de l'opération de vidage pour le pool de mémoire tampon InnoDB.

Ce paramètre intéresse principalement les experts en performances qui s'intéressent au réglage des charges de travail exigeantes en E/S. Pour chaque instance de pool de mémoire tampon, ce paramètre indique la distance vers le bas dans la liste de pages LRU (least recently used) que le thread de nettoyage de page doit poursuivre la numérisation, en recherchant les pages sales à vider. Cette opération d'arrière-plan est effectuée une fois par seconde.

Vous pouvez régler la valeur vers le haut ou vers le bas pour réduire le nombre de pages libres. Ne définissez pas la valeur beaucoup plus haut que nécessaire, car les analyses peuvent avoir un coût de performance important. Pensez également à ajuster ce paramètre lors de la modification du nombre d'instances de pool de mémoire tampon, car `innodb_lru_scan_depth * innodb_buffer_pool_instances` définit la quantité de travail effectuée par le thread de nettoyage de page chaque seconde.

Un paramètre inférieur à celui par défaut convient à la plupart des workloads. Envisagez d'augmenter la valeur uniquement si vous disposez d'une capacité d'E/S disponible pour une charge de travail classique. Inversement, si une charge de travail exigeante en écriture sature votre capacité d'E/S, diminuez la valeur, en particulier si vous disposez d'un pool de mémoire tampon important.
