---
sidebar: sidebar 
permalink: mysql/mysql-mysql-over-nfs.html 
keywords: MySQL,MariaDB,NFS 
summary: MySQL avec NFS 
searchtitle: MySQL avec NFS 
---
= NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La documentation MySQL recommande d'utiliser NFSv4 pour les déploiements NAS.



== Tailles de transfert NFS ONTAP

Par défaut, ONTAP limite les tailles d'E/S NFS à 64 Ko. Les E/S aléatoires avec une base de données MySQL utilisent une taille de bloc bien inférieure à la taille maximale de 64 Ko. Les E/S de bloc volumineux sont généralement parallélisées de sorte que le maximum de 64 000 ne constitue pas non plus une limitation.

Dans certains cas, le maximum de 64 000 charges de travail entraîne une limitation. En particulier, les opérations à thread unique, telles que les opérations de sauvegarde d'analyse de table complète, s'exécuteront plus rapidement et plus efficacement si la base de données peut exécuter moins d'E/S, mais de plus grande taille. La taille optimale de gestion des E/S pour ONTAP avec charges de travail de base de données est de 256 Ko. Les options de montage NFS répertoriées pour les systèmes d'exploitation spécifiques ci-dessous ont été mises à jour de 64 Ko à 256 Ko en conséquence.

La taille maximale de transfert pour un SVM ONTAP donné peut être modifiée comme suit :

[listing]
----
Cluster01::> set advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.

Do you want to continue? {y|n}: y

Cluster01::*> nfs server modify -vserver vserver1 -tcp-max-xfer-size 262144
----

CAUTION: Ne diminuez jamais la taille de transfert maximale autorisée sur ONTAP en dessous de la valeur de rsize/wsize des systèmes de fichiers NFS actuellement montés. Cela peut provoquer des blocages ou même une corruption des données avec certains systèmes d'exploitation. Par exemple, si les clients NFS sont actuellement définis sur une taille rsize/wsize de 65536, la taille maximale du transfert ONTAP peut être ajustée entre 65536 et 1048576 sans effet car les clients eux-mêmes sont limités. Réduire la taille de transfert maximale en dessous de 65536 peut endommager la disponibilité ou les données.

[TIP]
====
*NetApp recommande*

Définition du paramètre NFSv4 fstab (/etc/fstab) suivant :

`nfs4 rw, hard,nointr,bg,vers=4,proto=tcp,noatime,rsize=262144,wsize=262144`

====

NOTE: NFSv3 présentait fréquemment un problème de verrouillage des fichiers journaux InnoDB après une panne de courant. L'utilisation du temps ou la commutation des fichiers journaux a résolu ce problème. Cependant, NFSv4 dispose d'opérations de verrouillage et assure le suivi des fichiers ouverts et des délégations.
