---
sidebar: sidebar 
permalink: oracle/dr/metrocluster/mc-mcc-nvfail.html 
keywords: oracle, metrocluster, extended rac, rac, nvfail, switchover 
summary: Oracle sur MetroCluster - NVFAIL 
---
= MetroCluster et NVFAIL
:allow-uri-read: 


[role="lead"]
NVFAIL est une fonctionnalité d'intégrité générale des données de ONTAP, particulièrement essentielle pour la charge de travail de la base de données. Elle est détaillée dans le link:../ontap-configuration/oracle_and_nvfail.html["NVFAIL"]. Il existe également des considérations spécifiques à MetroCluster pour NVFAIL.



== RAC étendu avec NVFAIL forcé manuellement

L'option la plus sûre pour forcer un basculement avec un cluster RAC étendu est de spécifier `-force-nvfail-all` en ligne de commande. Cette option est disponible en tant que mesure d'urgence pour s'assurer que toutes les données mises en cache sont vidées. Si un hôte utilise des ressources de stockage initialement situées sur le site sinistré, il reçoit des erreurs d'E/S ou un descripteur de fichier obsolète (`ESTALE`) erreur. Les bases de données Oracle planent et les systèmes de fichiers passent entièrement hors ligne ou en mode lecture seule.

Une fois le basculement terminé, le `in-nvfailed-state` L'indicateur doit être effacé et les LUN doivent être mis en ligne. Une fois cette activité terminée, la base de données peut être redémarrée. Ces tâches peuvent être automatisées afin de réduire le RTO.



== RAC étendu avec dr-force-nvfail

La configuration la plus sûre est de définir le `dr-force-nvfail` marquer tous les volumes accessibles à partir d'un site distant. Par conséquent, les volumes deviennent indisponibles lorsqu'ils entrent `in-nvfailed-state` lors d'un basculement. Une fois le basculement terminé, le `in-nvfailed-state` L'indicateur doit être effacé et les LUN doivent être mis en ligne. Une fois ces activités terminées, la base de données peut être redémarrée. Ces tâches peuvent être automatisées afin de réduire le RTO.

Le résultat est similaire à l'utilisation du `-force-nvfail-all` drapeau. Toutefois, le nombre de volumes affectés peut être limité aux volumes qui doivent être protégés contre les applications ou les systèmes d'exploitation dotés de caches obsolètes.



== RAC étendu sans dr-force-nvfail

Il existe deux exigences critiques pour un environnement qui n'utilise pas `dr-force-nvfail` sur les volumes de base de données :

* Un basculement forcé ne doit pas se produire plus de 30 secondes après la perte du site principal.
* Il n'est pas nécessaire de procéder à un basculement lors des tâches de maintenance ou dans tout autre cas où les plexes SyncMirror ou la réplication NVRAM ne sont pas synchronisés. Les premières exigences peuvent être satisfaites à l'aide du logiciel disjoncteur d'attache configuré pour effectuer un basculement dans les 30 secondes qui suivent une panne sur un site. Cela ne signifie pas que le basculement doit être effectué dans les 30 secondes qui suivent la détection d'une défaillance de site. Cela signifie qu'il n'est plus sûr de forcer un basculement si 30 secondes se sont écoulées depuis qu'un site a été confirmé opérationnel.


Le deuxième critère peut être partiellement respecté en désactivant toutes les fonctionnalités de basculement automatisé lorsque la configuration MetroCluster est désynchronisée. Il est préférable d'opter pour une solution disjoncteur d'attache capable de surveiller l'état de santé de la réplication NVRAM et des plexes SyncMirror. Si le cluster n'est pas entièrement synchronisé, le disjoncteur d'attache ne doit pas déclencher de basculement.

Le logiciel MCTB de NetApp ne peut pas contrôler l'état de la synchronisation. Il doit donc être désactivé lorsque MetroCluster n'est pas synchronisé pour quelque raison que ce soit. ClusterLion inclut des fonctionnalités de surveillance NVRAM et plex et peut être configuré pour ne pas déclencher le basculement à moins que le système MetroCluster ne soit entièrement synchronisé.
