---
sidebar: sidebar 
permalink: microsoft/win_deploy_hyperv_replica_oce.html 
keywords: Windows,Hyper-V,VHDX,VM,Virtual 
summary: 'Cette annexe décrit le déploiement d"un réplica Hyper-V en dehors d"un environnement en cluster.' 
---
= Déployez le réplica Hyper-V en dehors d'un environnement en cluster
:allow-uri-read: 


[role="lead"]
Cette annexe décrit le déploiement d'un réplica Hyper-V en dehors d'un environnement en cluster.



== Prérequis

* Vous avez besoin de serveurs Hyper-V autonomes situés dans le même emplacement géographique ou dans des emplacements distincts servant de serveurs principaux et de serveurs de réplica.
* Si des sites distincts sont utilisés, le pare-feu de chaque site doit être configuré pour permettre la communication entre les serveurs principal et de réplica.
* Le serveur de réplica doit disposer d'un espace suffisant pour stocker les charges de travail répliquées.




== Déploiement

. Configurez le serveur de réplica.
+
.. Pour que les règles de pare-feu entrantes autorisent le trafic de réplication entrant, exécutez l'applet de commande PowerShell suivante :
+
 Enable-Netfirewallrule -displayname "Hyper-V Replica HTTP Listener (TCP-In)"
.. Ouvrez Hyper-V Manager dans la section Outils de Server Manager.
.. Cliquez sur Paramètres Hyper-V dans actions.
.. Cliquez sur Configuration de la réplication et sélectionnez Activer cet ordinateur en tant que serveur de réplica.
.. Dans la section authentification et ports, sélectionnez la méthode et le port d'authentification.
.. Dans la section autorisation et stockage, spécifiez l'emplacement où stocker les machines virtuelles et les fichiers répliqués.


. Activez la réplication des machines virtuelles sur le serveur principal. La réplication des machines virtuelles est activée par machine virtuelle, et non pour l'ensemble du serveur Hyper-V.
+
.. Dans Hyper-V Manager, cliquez avec le bouton droit de la souris sur un serveur virtuel, puis cliquez sur Activer la réplication pour ouvrir l'assistant Activer la réplication.
.. Indiquez le nom du serveur de réplica sur lequel la machine virtuelle doit être répliquée.
.. Indiquez le type d'authentification et le port du serveur de réplica qui a été configuré pour recevoir le trafic de réplication sur le serveur de réplica.
.. Sélectionnez les VHD à répliquer.
.. Choisissez la fréquence (durée) à laquelle les modifications sont envoyées au serveur de réplica.
.. Configurez les points de récupération pour spécifier le nombre de points de récupération à conserver sur le serveur de réplica.
.. Choisissez méthode de réplication initiale pour spécifier la méthode de transfert de la copie initiale des données de la machine virtuelle vers le serveur de réplica.
.. Vérifiez le résumé et cliquez sur Terminer.
.. Ce processus crée une réplique de machine virtuelle sur le serveur de réplica.






== La réplication

. Exécutez un basculement de test pour vous assurer que la machine virtuelle de réplica fonctionne correctement sur le serveur de réplica. Le test crée une machine virtuelle temporaire sur le serveur de réplica.
+
.. Connectez-vous au serveur de réplica.
.. Dans Hyper-V Manager, cliquez avec le bouton droit de la souris sur un serveur virtuel de réplica, cliquez sur réplication, puis sur Test Failover.
.. Choisissez le point de restauration à utiliser.
.. Ce processus crée un VM du même nom ajouté à -Test.
.. Vérifier la machine virtuelle pour s'assurer que tout fonctionne correctement.
.. Après le basculement, la machine virtuelle de test de réplica est supprimée si vous sélectionnez Arrêter le basculement de test pour elle.


. Exécutez un basculement planifié pour répliquer les dernières modifications sur la machine virtuelle principale vers la machine virtuelle de réplica.
+
.. Connectez-vous au serveur principal.
.. Désactivez la machine virtuelle à basculer.
.. Dans Hyper-V Manager, cliquez avec le bouton droit de la souris sur le serveur virtuel désactivé, cliquez sur réplication, puis sur basculement planifié.
.. Cliquez sur basculement pour transférer les dernières modifications apportées à la machine virtuelle vers le serveur de réplica.


. Exécuter un basculement non planifié en cas de défaillance de la machine virtuelle principale.
+
.. Connectez-vous au serveur de réplica.
.. Dans Hyper-V Manager, cliquez avec le bouton droit de la souris sur un serveur virtuel de réplica, cliquez sur réplication, puis sur basculement.
.. Choisissez le point de restauration à utiliser.
.. Cliquez sur basculement pour basculer le serveur virtuel.



