---
sidebar: sidebar 
permalink: postgres/postgres-snapshot-dp.html 
keywords: PostgreSQL,database,postgres 
summary: Bases de données PostgreSQL et snapshots de stockage 
---
= Bases de données PostgreSQL et snapshots de stockage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Les sauvegardes basées sur des copies Snapshot avec PostgreSQL requièrent la configuration de snapshots pour les fichiers de données, les fichiers WAL et les fichiers WAL archivés afin d'assurer une restauration complète ou instantanée.

Pour les bases de données PostgreSQL, la durée moyenne de sauvegarde avec des copies Snapshot est comprise entre quelques secondes et quelques minutes. Cette vitesse de sauvegarde est 60 à 100 fois plus rapide que `pg_basebackup` et d'autres approches de sauvegarde basées sur le système de fichiers.

Les copies Snapshot situées sur un système de stockage NetApp peuvent être à la fois cohérentes après panne et cohérentes au niveau des applications. Un snapshot cohérent après panne est créé sur un système de stockage sans interrompre la base de données, tandis qu'un Snapshot cohérent avec les applications est créé lorsque la base de données est en mode de sauvegarde. NetApp garantit également que les copies Snapshot suivantes sont des sauvegardes incrémentielles à l'infini pour promouvoir les économies de stockage et l'efficacité réseau.

Comme les snapshots sont rapides et n'affectent pas les performances du système, vous pouvez planifier plusieurs copies Snapshot chaque jour au lieu de créer une sauvegarde quotidienne comme avec les autres technologies de sauvegarde en streaming. Lorsqu'une opération de restauration et de restauration est nécessaire, le temps d'interruption du système est réduit grâce à deux fonctionnalités clés :

* Avec la technologie de restauration des données NetApp SnapRestore, la restauration s'exécute en quelques secondes.
* Les objectifs de point de restauration (RPO) agressifs signifient qu'il faut moins de journaux de base de données et que la restauration par progression est également accélérée.


Pour sauvegarder PostgreSQL, vous devez vous assurer que les volumes de données sont protégés simultanément avec WAL (groupe de cohérence) et les journaux archivés. Lorsque vous utilisez la technologie Snapshot pour copier des fichiers WAL, assurez-vous de les exécuter `pg_stop` Pour vider toutes les entrées WAL qui doivent être archivées. Si vous videz les entrées WAL pendant la restauration, il vous suffit d'arrêter la base de données, de démonter ou de supprimer le répertoire de données existant et d'effectuer une opération SnapRestore sur le stockage. Une fois la restauration terminée, vous pouvez monter le système et le ramener à son état actuel. Pour la restauration instantanée, vous pouvez également restaurer les journaux WAL et d'archivage ; PostgreSQL décide alors du point le plus cohérent et le récupère automatiquement.

Les groupes de cohérence sont une fonctionnalité de ONTAP recommandée lorsque plusieurs volumes sont montés sur une seule instance ou une base de données avec plusieurs tablespaces. Une copie Snapshot de groupe de cohérence garantit que tous les volumes sont regroupés et protégés. Pour gérer efficacement un groupe de cohérence, ONTAP vous pouvez même le cloner et créer une copie d'instance d'une base de données à des fins de test ou de développement.
