---
sidebar: sidebar 
permalink: postgres/postgres-overview.html 
keywords: PostgreSQL,database,postgres 
summary: Bases de données PostgreSQL sur ONTAP 
searchtitle: Bases de données PostgreSQL sur ONTAP 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
PostgreSQL est fourni avec des variantes incluant PostgreSQL, PostgreSQL plus et EDB Postgres Advanced Server (EPAS). PostgreSQL est généralement déployé en tant que base de données interne pour les applications multiniveaux. Il est pris en charge par les logiciels middleware courants (tels que PHP, Java, Python, Tcl/TK, ODBC, Et JDBC) et a toujours été un choix populaire pour les systèmes de gestion de bases de données open source. ONTAP constitue un excellent choix pour l'exécution des bases de données PostgreSQL et ses fonctionnalités de gestion des données fiables, performantes et efficaces.


NOTE: Cette documentation sur ONTAP et la base de données PostgreSQL remplace la base de données _TR-4770: PostgreSQL sur les meilleures pratiques ONTAP._

Avec la croissance exponentielle des données, la gestion des données devient de plus en plus complexe pour les entreprises. Cette complexité augmente les coûts de licence, d'exploitation, de support et de maintenance. Pour réduire le coût total de possession, envisagez de passer de bases de données commerciales à des bases de données open source grâce à un stockage interne fiable et haute performance.

ONTAP est une plateforme idéale, car ONTAP est littéralement conçu pour les bases de données. De nombreuses fonctionnalités, telles que l'optimisation de la latence d'E/S aléatoire, pour la qualité de service (QoS) avancée et les fonctionnalités FlexClone de base, ont été spécialement conçues pour répondre aux besoins des charges de travail des bases de données.

Des fonctionnalités supplémentaires, telles que les mises à niveau sans interruption (y compris le remplacement du stockage), assurent la disponibilité de vos bases de données stratégiques. Vous pouvez également bénéficier d'une reprise après incident instantanée pour les environnements volumineux via MetroCluster ou sélectionner des bases de données à l'aide de la synchronisation active SnapMirror.

Plus important encore, ONTAP offre des performances inégalées avec la possibilité de dimensionner la solution en fonction de vos besoins spécifiques. Nos systèmes haut de gamme peuvent fournir plus de 1 million d'IOPS à des latences mesurées en microsecondes. Toutefois, si vous n'avez besoin que de 100 000 IOPS, vous pouvez ajuster la taille de votre solution de stockage à l'aide d'un contrôleur plus petit, qui exécute toujours le même système d'exploitation du stockage.
